package world

import "github.com/alexykot/cncraft/pkg/protocol/tags"

var vanillaDimentionsCodec = tags.DimensionCodec{
	Dimensions: tags.DimensionRegistry{
		Type: "minecraft:dimension_type",
		RegistryEntries: []tags.DimensionRegistryEntry{
			{
				Name: "minecraft:overworld",
				ID:   0,
				Element: tags.Dimension{
					PiglinSafe:         0x0,
					Natural:            0x1,
					AmbientLight:       0,
					Infiniburn:         "minecraft:infiniburn_overworld",
					RespawnAnchorWorks: 0x0,
					HasSkylight:        0x1,
					BedWorks:           0x1,
					Effects:            "minecraft:overworld",
					HasRaids:           0x1,
					LogicalHeight:      256,
					CoordinateScale:    1,
					Ultrawarm:          0x0,
					HasCeiling:         0x0,
					FixedTime:          0,
				},
			}, {
				Name: "minecraft:overworld_caves",
				ID:   1,
				Element: tags.Dimension{
					PiglinSafe:         0x0,
					Natural:            0x1,
					AmbientLight:       0,
					Infiniburn:         "minecraft:infiniburn_overworld",
					RespawnAnchorWorks: 0x0,
					HasSkylight:        0x1,
					BedWorks:           0x1,
					Effects:            "minecraft:overworld",
					HasRaids:           0x1,
					LogicalHeight:      256,
					CoordinateScale:    1,
					Ultrawarm:          0x0,
					HasCeiling:         0x1,
					FixedTime:          0,
				},
			}, {
				Name: "minecraft:the_nether",
				ID:   2,
				Element: tags.Dimension{
					PiglinSafe:         0x1,
					Natural:            0x0,
					AmbientLight:       0.1,
					Infiniburn:         "minecraft:infiniburn_nether",
					RespawnAnchorWorks: 0x1,
					HasSkylight:        0x0,
					BedWorks:           0x0,
					Effects:            "minecraft:the_nether",
					HasRaids:           0x0,
					LogicalHeight:      128,
					CoordinateScale:    8,
					Ultrawarm:          0x1,
					HasCeiling:         0x1,
					FixedTime:          18000,
				},
			}, {
				Name: "minecraft:the_end",
				ID:   3,
				Element: tags.Dimension{
					PiglinSafe:         0x0,
					Natural:            0x0,
					AmbientLight:       0,
					Infiniburn:         "minecraft:infiniburn_end",
					RespawnAnchorWorks: 0x0,
					HasSkylight:        0x0,
					BedWorks:           0x0,
					Effects:            "minecraft:the_end",
					HasRaids:           0x1,
					LogicalHeight:      256,
					CoordinateScale:    1,
					Ultrawarm:          0x0,
					HasCeiling:         0x0,
					FixedTime:          6000,
				},
			},
		},
	},
	Biomes: tags.BiomeRegistry{
		Type: "minecraft:worldgen/biome",
		RegistryEntries: []tags.BiomeRegistryEntry{
			{
				Name: "minecraft:ocean",
				ID:   0,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:plains",
				ID:   1,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.125,
					Temperature:   0.8,
					Scale:         0.05,
					Downfall:      0.4,
					Category:      "plains",
					Effects: tags.BiomeEffects{
						SkyColor:           7907327,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:desert",
				ID:   2,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.125,
					Temperature:   2,
					Scale:         0.05,
					Downfall:      0,
					Category:      "desert",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:mountains",
				ID:   3,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         1,
					Temperature:   0.2,
					Scale:         0.5,
					Downfall:      0.3,
					Category:      "extreme_hills",
					Effects: tags.BiomeEffects{
						SkyColor:           8233727,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:forest",
				ID:   4,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.7,
					Scale:         0.2,
					Downfall:      0.8,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           7972607,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:taiga",
				ID:   5,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.25,
					Scale:         0.2,
					Downfall:      0.8,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8233983,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:swamp",
				ID:   6,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -0.2,
					Temperature:   0.8,
					Scale:         0.1,
					Downfall:      0.9,
					Category:      "swamp",
					Effects: tags.BiomeEffects{
						SkyColor:           7907327,
						WaterFogColor:      2302743,
						FogColor:           12638463,
						WaterColor:         6388580,
						FoliageColor:       6975545,
						GrassColorModifier: "swamp",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:river",
				ID:   7,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -0.5,
					Temperature:   0.5,
					Scale:         0,
					Downfall:      0.5,
					Category:      "river",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:nether_wastes",
				ID:   8,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   2,
					Scale:         0.2,
					Downfall:      0,
					Category:      "nether",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           3344392,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "minecraft:ambient.nether_wastes.loop",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "minecraft:music.nether.nether_wastes",
							MaxDelay:            24000,
							MinDelay:            12000,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "minecraft:ambient.nether_wastes.additions",
							TickChance: 0.0111,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.nether_wastes.mood",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:the_end",
				ID:   9,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   0.5,
					Scale:         0.2,
					Downfall:      0.5,
					Category:      "the_end",
					Effects: tags.BiomeEffects{
						SkyColor:           0,
						WaterFogColor:      329011,
						FogColor:           10518688,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:frozen_ocean",
				ID:   10,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         -1,
					Temperature:   0,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8364543,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         3750089,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:frozen_river",
				ID:   11,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         -0.5,
					Temperature:   0,
					Scale:         0,
					Downfall:      0.5,
					Category:      "river",
					Effects: tags.BiomeEffects{
						SkyColor:           8364543,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         3750089,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:snowy_tundra",
				ID:   12,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         0.125,
					Temperature:   0,
					Scale:         0.05,
					Downfall:      0.5,
					Category:      "icy",
					Effects: tags.BiomeEffects{
						SkyColor:           8364543,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:snowy_mountains",
				ID:   13,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         0.45,
					Temperature:   0,
					Scale:         0.3,
					Downfall:      0.5,
					Category:      "icy",
					Effects: tags.BiomeEffects{
						SkyColor:           8364543,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:mushroom_fields",
				ID:   14,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.9,
					Scale:         0.3,
					Downfall:      1,
					Category:      "mushroom",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:mushroom_field_shore",
				ID:   15,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0,
					Temperature:   0.9,
					Scale:         0.025,
					Downfall:      1,
					Category:      "mushroom",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:beach",
				ID:   16,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0,
					Temperature:   0.8,
					Scale:         0.025,
					Downfall:      0.4,
					Category:      "beach",
					Effects: tags.BiomeEffects{
						SkyColor:           7907327,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:desert_hills",
				ID:   17,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.45,
					Temperature:   2,
					Scale:         0.3,
					Downfall:      0,
					Category:      "desert",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:wooded_hills",
				ID:   18,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.45,
					Temperature:   0.7,
					Scale:         0.3,
					Downfall:      0.8,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           7972607,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:taiga_hills",
				ID:   19,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.45,
					Temperature:   0.25,
					Scale:         0.3,
					Downfall:      0.8,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8233983,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:mountain_edge",
				ID:   20,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.8,
					Temperature:   0.2,
					Scale:         0.3,
					Downfall:      0.3,
					Category:      "extreme_hills",
					Effects: tags.BiomeEffects{
						SkyColor:           8233727,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:jungle",
				ID:   21,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.95,
					Scale:         0.2,
					Downfall:      0.9,
					Category:      "jungle",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:jungle_hills",
				ID:   22,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.45,
					Temperature:   0.95,
					Scale:         0.3,
					Downfall:      0.9,
					Category:      "jungle",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:jungle_edge",
				ID:   23,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.95,
					Scale:         0.2,
					Downfall:      0.8,
					Category:      "jungle",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:deep_ocean",
				ID:   24,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1.8,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:stone_shore",
				ID:   25,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.2,
					Scale:         0.8,
					Downfall:      0.3,
					Category:      "none",
					Effects: tags.BiomeEffects{
						SkyColor:           8233727,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:snowy_beach",
				ID:   26,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         0,
					Temperature:   0.05,
					Scale:         0.025,
					Downfall:      0.3,
					Category:      "beach",
					Effects: tags.BiomeEffects{
						SkyColor:           8364543,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4020182,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:birch_forest",
				ID:   27,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.6,
					Scale:         0.2,
					Downfall:      0.6,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           8037887,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:birch_forest_hills",
				ID:   28,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.45,
					Temperature:   0.6,
					Scale:         0.3,
					Downfall:      0.6,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           8037887,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:dark_forest",
				ID:   29,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.7,
					Scale:         0.2,
					Downfall:      0.8,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           7972607,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "dark_forest",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:snowy_taiga",
				ID:   30,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         0.2,
					Temperature:   -0.5,
					Scale:         0.2,
					Downfall:      0.4,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8625919,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4020182,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:snowy_taiga_hills",
				ID:   31,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         0.45,
					Temperature:   -0.5,
					Scale:         0.3,
					Downfall:      0.4,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8625919,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4020182,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:giant_tree_taiga",
				ID:   32,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.3,
					Scale:         0.2,
					Downfall:      0.8,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8168447,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:giant_tree_taiga_hills",
				ID:   33,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.45,
					Temperature:   0.3,
					Scale:         0.3,
					Downfall:      0.8,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8168447,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:wooded_mountains",
				ID:   34,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         1,
					Temperature:   0.2,
					Scale:         0.5,
					Downfall:      0.3,
					Category:      "extreme_hills",
					Effects: tags.BiomeEffects{
						SkyColor:           8233727,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:savanna",
				ID:   35,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.125,
					Temperature:   1.2,
					Scale:         0.05,
					Downfall:      0,
					Category:      "savanna",
					Effects: tags.BiomeEffects{
						SkyColor:           7711487,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:savanna_plateau",
				ID:   36,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         1.5,
					Temperature:   1,
					Scale:         0.025,
					Downfall:      0,
					Category:      "savanna",
					Effects: tags.BiomeEffects{
						SkyColor:           7776511,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:badlands",
				ID:   37,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   2,
					Scale:         0.2,
					Downfall:      0,
					Category:      "mesa",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       10387789,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:wooded_badlands_plateau",
				ID:   38,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         1.5,
					Temperature:   2,
					Scale:         0.025,
					Downfall:      0,
					Category:      "mesa",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       10387789,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:badlands_plateau",
				ID:   39,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         1.5,
					Temperature:   2,
					Scale:         0.025,
					Downfall:      0,
					Category:      "mesa",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       10387789,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:small_end_islands",
				ID:   40,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   0.5,
					Scale:         0.2,
					Downfall:      0.5,
					Category:      "the_end",
					Effects: tags.BiomeEffects{
						SkyColor:           0,
						WaterFogColor:      329011,
						FogColor:           10518688,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:end_midlands",
				ID:   41,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   0.5,
					Scale:         0.2,
					Downfall:      0.5,
					Category:      "the_end",
					Effects: tags.BiomeEffects{
						SkyColor:           0,
						WaterFogColor:      329011,
						FogColor:           10518688,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:end_highlands",
				ID:   42,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   0.5,
					Scale:         0.2,
					Downfall:      0.5,
					Category:      "the_end",
					Effects: tags.BiomeEffects{
						SkyColor:           0,
						WaterFogColor:      329011,
						FogColor:           10518688,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:end_barrens",
				ID:   43,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   0.5,
					Scale:         0.2,
					Downfall:      0.5,
					Category:      "the_end",
					Effects: tags.BiomeEffects{
						SkyColor:           0,
						WaterFogColor:      329011,
						FogColor:           10518688,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:warm_ocean",
				ID:   44,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      270131,
						FogColor:           12638463,
						WaterColor:         4445678,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:lukewarm_ocean",
				ID:   45,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      267827,
						FogColor:           12638463,
						WaterColor:         4566514,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:cold_ocean",
				ID:   46,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4020182,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:deep_warm_ocean",
				ID:   47,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1.8,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      270131,
						FogColor:           12638463,
						WaterColor:         4445678,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:deep_lukewarm_ocean",
				ID:   48,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1.8,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      267827,
						FogColor:           12638463,
						WaterColor:         4566514,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:deep_cold_ocean",
				ID:   49,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1.8,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4020182,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:deep_frozen_ocean",
				ID:   50,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -1.8,
					Temperature:   0.5,
					Scale:         0.1,
					Downfall:      0.5,
					Category:      "ocean",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         3750089,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:the_void",
				ID:   127,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   0.5,
					Scale:         0.2,
					Downfall:      0.5,
					Category:      "none",
					Effects: tags.BiomeEffects{
						SkyColor:           8103167,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:sunflower_plains",
				ID:   129,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.125,
					Temperature:   0.8,
					Scale:         0.05,
					Downfall:      0.4,
					Category:      "plains",
					Effects: tags.BiomeEffects{
						SkyColor:           7907327,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:desert_lakes",
				ID:   130,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.225,
					Temperature:   2,
					Scale:         0.25,
					Downfall:      0,
					Category:      "desert",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:gravelly_mountains",
				ID:   131,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         1,
					Temperature:   0.2,
					Scale:         0.5,
					Downfall:      0.3,
					Category:      "extreme_hills",
					Effects: tags.BiomeEffects{
						SkyColor:           8233727,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:flower_forest",
				ID:   132,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.7,
					Scale:         0.4,
					Downfall:      0.8,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           7972607,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:taiga_mountains",
				ID:   133,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.3,
					Temperature:   0.25,
					Scale:         0.4,
					Downfall:      0.8,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8233983,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:swamp_hills",
				ID:   134,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         -0.1,
					Temperature:   0.8,
					Scale:         0.3,
					Downfall:      0.9,
					Category:      "swamp",
					Effects: tags.BiomeEffects{
						SkyColor:           7907327,
						WaterFogColor:      2302743,
						FogColor:           12638463,
						WaterColor:         6388580,
						FoliageColor:       6975545,
						GrassColorModifier: "swamp",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:ice_spikes",
				ID:   140,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         0.425,
					Temperature:   0,
					Scale:         0.45000002,
					Downfall:      0.5,
					Category:      "icy",
					Effects: tags.BiomeEffects{
						SkyColor:           8364543,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:modified_jungle",
				ID:   149,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.95,
					Scale:         0.4,
					Downfall:      0.9,
					Category:      "jungle",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:modified_jungle_edge",
				ID:   151,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.95,
					Scale:         0.4,
					Downfall:      0.8,
					Category:      "jungle",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:tall_birch_forest",
				ID:   155,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.6,
					Scale:         0.4,
					Downfall:      0.6,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           8037887,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:tall_birch_hills",
				ID:   156,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.55,
					Temperature:   0.6,
					Scale:         0.5,
					Downfall:      0.6,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           8037887,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:dark_forest_hills",
				ID:   157,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.7,
					Scale:         0.4,
					Downfall:      0.8,
					Category:      "forest",
					Effects: tags.BiomeEffects{
						SkyColor:           7972607,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "dark_forest",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:snowy_taiga_mountains",
				ID:   158,
				Element: tags.Biome{
					Precipitation: "snow",
					Depth:         0.3,
					Temperature:   -0.5,
					Scale:         0.4,
					Downfall:      0.4,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8625919,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4020182,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:giant_spruce_taiga",
				ID:   160,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.25,
					Scale:         0.2,
					Downfall:      0.8,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8233983,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:giant_spruce_taiga_hills",
				ID:   161,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.2,
					Temperature:   0.25,
					Scale:         0.2,
					Downfall:      0.8,
					Category:      "taiga",
					Effects: tags.BiomeEffects{
						SkyColor:           8233983,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:modified_gravelly_mountains",
				ID:   162,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         1,
					Temperature:   0.2,
					Scale:         0.5,
					Downfall:      0.3,
					Category:      "extreme_hills",
					Effects: tags.BiomeEffects{
						SkyColor:           8233727,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:shattered_savanna",
				ID:   163,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.3625,
					Temperature:   1.1,
					Scale:         1.225,
					Downfall:      0,
					Category:      "savanna",
					Effects: tags.BiomeEffects{
						SkyColor:           7776767,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:shattered_savanna_plateau",
				ID:   164,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         1.05,
					Temperature:   1,
					Scale:         1.2125001,
					Downfall:      0,
					Category:      "savanna",
					Effects: tags.BiomeEffects{
						SkyColor:           7776511,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:eroded_badlands",
				ID:   165,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   2,
					Scale:         0.2,
					Downfall:      0,
					Category:      "mesa",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       10387789,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:modified_wooded_badlands_plateau",
				ID:   166,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.45,
					Temperature:   2,
					Scale:         0.3,
					Downfall:      0,
					Category:      "mesa",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       10387789,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:modified_badlands_plateau",
				ID:   167,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.45,
					Temperature:   2,
					Scale:         0.3,
					Downfall:      0,
					Category:      "mesa",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       10387789,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:bamboo_jungle",
				ID:   168,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.1,
					Temperature:   0.95,
					Scale:         0.2,
					Downfall:      0.9,
					Category:      "jungle",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:bamboo_jungle_hills",
				ID:   169,
				Element: tags.Biome{
					Precipitation: "rain",
					Depth:         0.45,
					Temperature:   0.95,
					Scale:         0.3,
					Downfall:      0.9,
					Category:      "jungle",
					Effects: tags.BiomeEffects{
						SkyColor:           7842047,
						WaterFogColor:      329011,
						FogColor:           12638463,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "",
							MaxDelay:            0,
							MinDelay:            0,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "",
							TickChance: 0,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.cave",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "",
							},
						},
					},
				},
			}, {
				Name: "minecraft:soul_sand_valley",
				ID:   170,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   2,
					Scale:         0.2,
					Downfall:      0,
					Category:      "nether",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           1787717,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "minecraft:ambient.soul_sand_valley.loop",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "minecraft:music.nether.soul_sand_valley",
							MaxDelay:            24000,
							MinDelay:            12000,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "minecraft:ambient.soul_sand_valley.additions",
							TickChance: 0.0111,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.soul_sand_valley.mood",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0.00625,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "minecraft:ash",
							},
						},
					},
				},
			}, {
				Name: "minecraft:crimson_forest",
				ID:   171,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   2,
					Scale:         0.2,
					Downfall:      0,
					Category:      "nether",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           3343107,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "minecraft:ambient.crimson_forest.loop",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "minecraft:music.nether.crimson_forest",
							MaxDelay:            24000,
							MinDelay:            12000,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "minecraft:ambient.crimson_forest.additions",
							TickChance: 0.0111,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.crimson_forest.mood",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0.025,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "minecraft:crimson_spore",
							},
						},
					},
				},
			}, {
				Name: "minecraft:warped_forest",
				ID:   172,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   2,
					Scale:         0.2,
					Downfall:      0,
					Category:      "nether",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      329011,
						FogColor:           1705242,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "minecraft:ambient.warped_forest.loop",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "minecraft:music.nether.warped_forest",
							MaxDelay:            24000,
							MinDelay:            12000,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "minecraft:ambient.warped_forest.additions",
							TickChance: 0.0111,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.warped_forest.mood",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0.01428,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "minecraft:warped_spore",
							},
						},
					},
				},
			}, {
				Name: "minecraft:basalt_deltas",
				ID:   173,
				Element: tags.Biome{
					Precipitation: "none",
					Depth:         0.1,
					Temperature:   2,
					Scale:         0.2,
					Downfall:      0,
					Category:      "nether",
					Effects: tags.BiomeEffects{
						SkyColor:           7254527,
						WaterFogColor:      4341314,
						FogColor:           6840176,
						WaterColor:         4159204,
						FoliageColor:       0,
						GrassColorModifier: "",
						AmbientSound:       "minecraft:ambient.basalt_deltas.loop",
						Music: tags.BiomeEffectsMusic{
							ReplaceCurrentMusic: 0x0,
							Sound:               "minecraft:music.nether.basalt_deltas",
							MaxDelay:            24000,
							MinDelay:            12000,
						},
						AdditionsSound: tags.BiomeEffectsAdditionsSound{
							Sound:      "minecraft:ambient.basalt_deltas.additions",
							TickChance: 0.0111,
						},
						MoodSound: tags.BiomeEffectsMoodSound{
							Sound:             "minecraft:ambient.basalt_deltas.mood",
							TickDelay:         6000,
							Offset:            2,
							BlockSearchExtend: 0,
						},
						Particle: tags.BiomeEffectsParticle{
							Probability: 0.118093334,
							Options: tags.BiomeEffectsParticleOptions{
								ParticleType: "minecraft:white_ash",
							},
						},
					},
				},
			},
		},
	},
}
