// Code generated by "stringer -type=DiggingAction status.go"; DO NOT EDIT.

package player

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StartedDigging-0]
	_ = x[CancelledDigging-1]
	_ = x[FinishedDigging-2]
	_ = x[DropItemStack-3]
	_ = x[DropItem-4]
	_ = x[ShootArrowFinishEating-5]
	_ = x[SwapItemInHand-6]
}

const _DiggingAction_name = "StartedDiggingCancelledDiggingFinishedDiggingDropItemStackDropItemShootArrowFinishEatingSwapItemInHand"

var _DiggingAction_index = [...]uint8{0, 14, 30, 45, 58, 66, 88, 102}

func (i DiggingAction) String() string {
	if i < 0 || i >= DiggingAction(len(_DiggingAction_index)-1) {
		return "DiggingAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiggingAction_name[_DiggingAction_index[i]:_DiggingAction_index[i+1]]
}
