package objects

type ItemID uint32

func (b ItemID) String() string { return itemNamesMap[b] }
func (b ItemID) ID() uint32     { return uint32(b) }

const (
	ItemAir                             ItemID = 0
	ItemStone                           ItemID = 1
	ItemGranite                         ItemID = 2
	ItemPolishedGranite                 ItemID = 3
	ItemDiorite                         ItemID = 4
	ItemPolishedDiorite                 ItemID = 5
	ItemAndesite                        ItemID = 6
	ItemPolishedAndesite                ItemID = 7
	ItemGrassBlock                      ItemID = 8
	ItemDirt                            ItemID = 9
	ItemCoarseDirt                      ItemID = 10
	ItemPodzol                          ItemID = 11
	ItemCrimsonNylium                   ItemID = 12
	ItemWarpedNylium                    ItemID = 13
	ItemCobblestone                     ItemID = 14
	ItemOakPlanks                       ItemID = 15
	ItemSprucePlanks                    ItemID = 16
	ItemBirchPlanks                     ItemID = 17
	ItemJunglePlanks                    ItemID = 18
	ItemAcaciaPlanks                    ItemID = 19
	ItemDarkOakPlanks                   ItemID = 20
	ItemCrimsonPlanks                   ItemID = 21
	ItemWarpedPlanks                    ItemID = 22
	ItemOakSapling                      ItemID = 23
	ItemSpruceSapling                   ItemID = 24
	ItemBirchSapling                    ItemID = 25
	ItemJungleSapling                   ItemID = 26
	ItemAcaciaSapling                   ItemID = 27
	ItemDarkOakSapling                  ItemID = 28
	ItemBedrock                         ItemID = 29
	ItemSand                            ItemID = 30
	ItemRedSand                         ItemID = 31
	ItemGravel                          ItemID = 32
	ItemGoldOre                         ItemID = 33
	ItemIronOre                         ItemID = 34
	ItemCoalOre                         ItemID = 35
	ItemNetherGoldOre                   ItemID = 36
	ItemOakLog                          ItemID = 37
	ItemSpruceLog                       ItemID = 38
	ItemBirchLog                        ItemID = 39
	ItemJungleLog                       ItemID = 40
	ItemAcaciaLog                       ItemID = 41
	ItemDarkOakLog                      ItemID = 42
	ItemCrimsonStem                     ItemID = 43
	ItemWarpedStem                      ItemID = 44
	ItemStrippedOakLog                  ItemID = 45
	ItemStrippedSpruceLog               ItemID = 46
	ItemStrippedBirchLog                ItemID = 47
	ItemStrippedJungleLog               ItemID = 48
	ItemStrippedAcaciaLog               ItemID = 49
	ItemStrippedDarkOakLog              ItemID = 50
	ItemStrippedCrimsonStem             ItemID = 51
	ItemStrippedWarpedStem              ItemID = 52
	ItemStrippedOakWood                 ItemID = 53
	ItemStrippedSpruceWood              ItemID = 54
	ItemStrippedBirchWood               ItemID = 55
	ItemStrippedJungleWood              ItemID = 56
	ItemStrippedAcaciaWood              ItemID = 57
	ItemStrippedDarkOakWood             ItemID = 58
	ItemStrippedCrimsonHyphae           ItemID = 59
	ItemStrippedWarpedHyphae            ItemID = 60
	ItemOakWood                         ItemID = 61
	ItemSpruceWood                      ItemID = 62
	ItemBirchWood                       ItemID = 63
	ItemJungleWood                      ItemID = 64
	ItemAcaciaWood                      ItemID = 65
	ItemDarkOakWood                     ItemID = 66
	ItemCrimsonHyphae                   ItemID = 67
	ItemWarpedHyphae                    ItemID = 68
	ItemOakLeaves                       ItemID = 69
	ItemSpruceLeaves                    ItemID = 70
	ItemBirchLeaves                     ItemID = 71
	ItemJungleLeaves                    ItemID = 72
	ItemAcaciaLeaves                    ItemID = 73
	ItemDarkOakLeaves                   ItemID = 74
	ItemSponge                          ItemID = 75
	ItemWetSponge                       ItemID = 76
	ItemGlass                           ItemID = 77
	ItemLapisOre                        ItemID = 78
	ItemLapisBlock                      ItemID = 79
	ItemDispenser                       ItemID = 80
	ItemSandstone                       ItemID = 81
	ItemChiseledSandstone               ItemID = 82
	ItemCutSandstone                    ItemID = 83
	ItemNoteBlock                       ItemID = 84
	ItemPoweredRail                     ItemID = 85
	ItemDetectorRail                    ItemID = 86
	ItemStickyPiston                    ItemID = 87
	ItemCobweb                          ItemID = 88
	ItemGrass                           ItemID = 89
	ItemFern                            ItemID = 90
	ItemDeadBush                        ItemID = 91
	ItemSeagrass                        ItemID = 92
	ItemSeaPickle                       ItemID = 93
	ItemPiston                          ItemID = 94
	ItemWhiteWool                       ItemID = 95
	ItemOrangeWool                      ItemID = 96
	ItemMagentaWool                     ItemID = 97
	ItemLightBlueWool                   ItemID = 98
	ItemYellowWool                      ItemID = 99
	ItemLimeWool                        ItemID = 100
	ItemPinkWool                        ItemID = 101
	ItemGrayWool                        ItemID = 102
	ItemLightGrayWool                   ItemID = 103
	ItemCyanWool                        ItemID = 104
	ItemPurpleWool                      ItemID = 105
	ItemBlueWool                        ItemID = 106
	ItemBrownWool                       ItemID = 107
	ItemGreenWool                       ItemID = 108
	ItemRedWool                         ItemID = 109
	ItemBlackWool                       ItemID = 110
	ItemDandelion                       ItemID = 111
	ItemPoppy                           ItemID = 112
	ItemBlueOrchid                      ItemID = 113
	ItemAllium                          ItemID = 114
	ItemAzureBluet                      ItemID = 115
	ItemRedTulip                        ItemID = 116
	ItemOrangeTulip                     ItemID = 117
	ItemWhiteTulip                      ItemID = 118
	ItemPinkTulip                       ItemID = 119
	ItemOxeyeDaisy                      ItemID = 120
	ItemCornflower                      ItemID = 121
	ItemLilyOfTheValley                 ItemID = 122
	ItemWitherRose                      ItemID = 123
	ItemBrownMushroom                   ItemID = 124
	ItemRedMushroom                     ItemID = 125
	ItemCrimsonFungus                   ItemID = 126
	ItemWarpedFungus                    ItemID = 127
	ItemCrimsonRoots                    ItemID = 128
	ItemWarpedRoots                     ItemID = 129
	ItemNetherSprouts                   ItemID = 130
	ItemWeepingVines                    ItemID = 131
	ItemTwistingVines                   ItemID = 132
	ItemSugarCane                       ItemID = 133
	ItemKelp                            ItemID = 134
	ItemBamboo                          ItemID = 135
	ItemGoldBlock                       ItemID = 136
	ItemIronBlock                       ItemID = 137
	ItemOakSlab                         ItemID = 138
	ItemSpruceSlab                      ItemID = 139
	ItemBirchSlab                       ItemID = 140
	ItemJungleSlab                      ItemID = 141
	ItemAcaciaSlab                      ItemID = 142
	ItemDarkOakSlab                     ItemID = 143
	ItemCrimsonSlab                     ItemID = 144
	ItemWarpedSlab                      ItemID = 145
	ItemStoneSlab                       ItemID = 146
	ItemSmoothStoneSlab                 ItemID = 147
	ItemSandstoneSlab                   ItemID = 148
	ItemCutSandstoneSlab                ItemID = 149
	ItemPetrifiedOakSlab                ItemID = 150
	ItemCobblestoneSlab                 ItemID = 151
	ItemBrickSlab                       ItemID = 152
	ItemStoneBrickSlab                  ItemID = 153
	ItemNetherBrickSlab                 ItemID = 154
	ItemQuartzSlab                      ItemID = 155
	ItemRedSandstoneSlab                ItemID = 156
	ItemCutRedSandstoneSlab             ItemID = 157
	ItemPurpurSlab                      ItemID = 158
	ItemPrismarineSlab                  ItemID = 159
	ItemPrismarineBrickSlab             ItemID = 160
	ItemDarkPrismarineSlab              ItemID = 161
	ItemSmoothQuartz                    ItemID = 162
	ItemSmoothRedSandstone              ItemID = 163
	ItemSmoothSandstone                 ItemID = 164
	ItemSmoothStone                     ItemID = 165
	ItemBricks                          ItemID = 166
	ItemTnt                             ItemID = 167
	ItemBookshelf                       ItemID = 168
	ItemMossyCobblestone                ItemID = 169
	ItemObsidian                        ItemID = 170
	ItemTorch                           ItemID = 171
	ItemEndRod                          ItemID = 172
	ItemChorusPlant                     ItemID = 173
	ItemChorusFlower                    ItemID = 174
	ItemPurpurBlock                     ItemID = 175
	ItemPurpurPillar                    ItemID = 176
	ItemPurpurStairs                    ItemID = 177
	ItemSpawner                         ItemID = 178
	ItemOakStairs                       ItemID = 179
	ItemChest                           ItemID = 180
	ItemDiamondOre                      ItemID = 181
	ItemDiamondBlock                    ItemID = 182
	ItemCraftingTable                   ItemID = 183
	ItemFarmland                        ItemID = 184
	ItemFurnace                         ItemID = 185
	ItemLadder                          ItemID = 186
	ItemRail                            ItemID = 187
	ItemCobblestoneStairs               ItemID = 188
	ItemLever                           ItemID = 189
	ItemStonePressurePlate              ItemID = 190
	ItemOakPressurePlate                ItemID = 191
	ItemSprucePressurePlate             ItemID = 192
	ItemBirchPressurePlate              ItemID = 193
	ItemJunglePressurePlate             ItemID = 194
	ItemAcaciaPressurePlate             ItemID = 195
	ItemDarkOakPressurePlate            ItemID = 196
	ItemCrimsonPressurePlate            ItemID = 197
	ItemWarpedPressurePlate             ItemID = 198
	ItemPolishedBlackstonePressurePlate ItemID = 199
	ItemRedstoneOre                     ItemID = 200
	ItemRedstoneTorch                   ItemID = 201
	ItemSnow                            ItemID = 202
	ItemIce                             ItemID = 203
	ItemSnowBlock                       ItemID = 204
	ItemCactus                          ItemID = 205
	ItemClay                            ItemID = 206
	ItemJukebox                         ItemID = 207
	ItemOakFence                        ItemID = 208
	ItemSpruceFence                     ItemID = 209
	ItemBirchFence                      ItemID = 210
	ItemJungleFence                     ItemID = 211
	ItemAcaciaFence                     ItemID = 212
	ItemDarkOakFence                    ItemID = 213
	ItemCrimsonFence                    ItemID = 214
	ItemWarpedFence                     ItemID = 215
	ItemPumpkin                         ItemID = 216
	ItemCarvedPumpkin                   ItemID = 217
	ItemNetherrack                      ItemID = 218
	ItemSoulSand                        ItemID = 219
	ItemSoulSoil                        ItemID = 220
	ItemBasalt                          ItemID = 221
	ItemPolishedBasalt                  ItemID = 222
	ItemSoulTorch                       ItemID = 223
	ItemGlowstone                       ItemID = 224
	ItemJackOLantern                    ItemID = 225
	ItemOakTrapdoor                     ItemID = 226
	ItemSpruceTrapdoor                  ItemID = 227
	ItemBirchTrapdoor                   ItemID = 228
	ItemJungleTrapdoor                  ItemID = 229
	ItemAcaciaTrapdoor                  ItemID = 230
	ItemDarkOakTrapdoor                 ItemID = 231
	ItemCrimsonTrapdoor                 ItemID = 232
	ItemWarpedTrapdoor                  ItemID = 233
	ItemInfestedStone                   ItemID = 234
	ItemInfestedCobblestone             ItemID = 235
	ItemInfestedStoneBricks             ItemID = 236
	ItemInfestedMossyStoneBricks        ItemID = 237
	ItemInfestedCrackedStoneBricks      ItemID = 238
	ItemInfestedChiseledStoneBricks     ItemID = 239
	ItemStoneBricks                     ItemID = 240
	ItemMossyStoneBricks                ItemID = 241
	ItemCrackedStoneBricks              ItemID = 242
	ItemChiseledStoneBricks             ItemID = 243
	ItemBrownMushroomBlock              ItemID = 244
	ItemRedMushroomBlock                ItemID = 245
	ItemMushroomStem                    ItemID = 246
	ItemIronBars                        ItemID = 247
	ItemChain                           ItemID = 248
	ItemGlassPane                       ItemID = 249
	ItemMelon                           ItemID = 250
	ItemVine                            ItemID = 251
	ItemOakFenceGate                    ItemID = 252
	ItemSpruceFenceGate                 ItemID = 253
	ItemBirchFenceGate                  ItemID = 254
	ItemJungleFenceGate                 ItemID = 255
	ItemAcaciaFenceGate                 ItemID = 256
	ItemDarkOakFenceGate                ItemID = 257
	ItemCrimsonFenceGate                ItemID = 258
	ItemWarpedFenceGate                 ItemID = 259
	ItemBrickStairs                     ItemID = 260
	ItemStoneBrickStairs                ItemID = 261
	ItemMycelium                        ItemID = 262
	ItemLilyPad                         ItemID = 263
	ItemNetherBricks                    ItemID = 264
	ItemCrackedNetherBricks             ItemID = 265
	ItemChiseledNetherBricks            ItemID = 266
	ItemNetherBrickFence                ItemID = 267
	ItemNetherBrickStairs               ItemID = 268
	ItemEnchantingTable                 ItemID = 269
	ItemEndPortalFrame                  ItemID = 270
	ItemEndStone                        ItemID = 271
	ItemEndStoneBricks                  ItemID = 272
	ItemDragonEgg                       ItemID = 273
	ItemRedstoneLamp                    ItemID = 274
	ItemSandstoneStairs                 ItemID = 275
	ItemEmeraldOre                      ItemID = 276
	ItemEnderChest                      ItemID = 277
	ItemTripwireHook                    ItemID = 278
	ItemEmeraldBlock                    ItemID = 279
	ItemSpruceStairs                    ItemID = 280
	ItemBirchStairs                     ItemID = 281
	ItemJungleStairs                    ItemID = 282
	ItemCrimsonStairs                   ItemID = 283
	ItemWarpedStairs                    ItemID = 284
	ItemCommandBlock                    ItemID = 285
	ItemBeacon                          ItemID = 286
	ItemCobblestoneWall                 ItemID = 287
	ItemMossyCobblestoneWall            ItemID = 288
	ItemBrickWall                       ItemID = 289
	ItemPrismarineWall                  ItemID = 290
	ItemRedSandstoneWall                ItemID = 291
	ItemMossyStoneBrickWall             ItemID = 292
	ItemGraniteWall                     ItemID = 293
	ItemStoneBrickWall                  ItemID = 294
	ItemNetherBrickWall                 ItemID = 295
	ItemAndesiteWall                    ItemID = 296
	ItemRedNetherBrickWall              ItemID = 297
	ItemSandstoneWall                   ItemID = 298
	ItemEndStoneBrickWall               ItemID = 299
	ItemDioriteWall                     ItemID = 300
	ItemBlackstoneWall                  ItemID = 301
	ItemPolishedBlackstoneWall          ItemID = 302
	ItemPolishedBlackstoneBrickWall     ItemID = 303
	ItemStoneButton                     ItemID = 304
	ItemOakButton                       ItemID = 305
	ItemSpruceButton                    ItemID = 306
	ItemBirchButton                     ItemID = 307
	ItemJungleButton                    ItemID = 308
	ItemAcaciaButton                    ItemID = 309
	ItemDarkOakButton                   ItemID = 310
	ItemCrimsonButton                   ItemID = 311
	ItemWarpedButton                    ItemID = 312
	ItemPolishedBlackstoneButton        ItemID = 313
	ItemAnvil                           ItemID = 314
	ItemChippedAnvil                    ItemID = 315
	ItemDamagedAnvil                    ItemID = 316
	ItemTrappedChest                    ItemID = 317
	ItemLightWeightedPressurePlate      ItemID = 318
	ItemHeavyWeightedPressurePlate      ItemID = 319
	ItemDaylightDetector                ItemID = 320
	ItemRedstoneBlock                   ItemID = 321
	ItemNetherQuartzOre                 ItemID = 322
	ItemHopper                          ItemID = 323
	ItemChiseledQuartzBlock             ItemID = 324
	ItemQuartzBlock                     ItemID = 325
	ItemQuartzBricks                    ItemID = 326
	ItemQuartzPillar                    ItemID = 327
	ItemQuartzStairs                    ItemID = 328
	ItemActivatorRail                   ItemID = 329
	ItemDropper                         ItemID = 330
	ItemWhiteTerracotta                 ItemID = 331
	ItemOrangeTerracotta                ItemID = 332
	ItemMagentaTerracotta               ItemID = 333
	ItemLightBlueTerracotta             ItemID = 334
	ItemYellowTerracotta                ItemID = 335
	ItemLimeTerracotta                  ItemID = 336
	ItemPinkTerracotta                  ItemID = 337
	ItemGrayTerracotta                  ItemID = 338
	ItemLightGrayTerracotta             ItemID = 339
	ItemCyanTerracotta                  ItemID = 340
	ItemPurpleTerracotta                ItemID = 341
	ItemBlueTerracotta                  ItemID = 342
	ItemBrownTerracotta                 ItemID = 343
	ItemGreenTerracotta                 ItemID = 344
	ItemRedTerracotta                   ItemID = 345
	ItemBlackTerracotta                 ItemID = 346
	ItemBarrier                         ItemID = 347
	ItemIronTrapdoor                    ItemID = 348
	ItemHayBlock                        ItemID = 349
	ItemWhiteCarpet                     ItemID = 350
	ItemOrangeCarpet                    ItemID = 351
	ItemMagentaCarpet                   ItemID = 352
	ItemLightBlueCarpet                 ItemID = 353
	ItemYellowCarpet                    ItemID = 354
	ItemLimeCarpet                      ItemID = 355
	ItemPinkCarpet                      ItemID = 356
	ItemGrayCarpet                      ItemID = 357
	ItemLightGrayCarpet                 ItemID = 358
	ItemCyanCarpet                      ItemID = 359
	ItemPurpleCarpet                    ItemID = 360
	ItemBlueCarpet                      ItemID = 361
	ItemBrownCarpet                     ItemID = 362
	ItemGreenCarpet                     ItemID = 363
	ItemRedCarpet                       ItemID = 364
	ItemBlackCarpet                     ItemID = 365
	ItemTerracotta                      ItemID = 366
	ItemCoalBlock                       ItemID = 367
	ItemPackedIce                       ItemID = 368
	ItemAcaciaStairs                    ItemID = 369
	ItemDarkOakStairs                   ItemID = 370
	ItemSlimeBlock                      ItemID = 371
	ItemGrassPath                       ItemID = 372
	ItemSunflower                       ItemID = 373
	ItemLilac                           ItemID = 374
	ItemRoseBush                        ItemID = 375
	ItemPeony                           ItemID = 376
	ItemTallGrass                       ItemID = 377
	ItemLargeFern                       ItemID = 378
	ItemWhiteStainedGlass               ItemID = 379
	ItemOrangeStainedGlass              ItemID = 380
	ItemMagentaStainedGlass             ItemID = 381
	ItemLightBlueStainedGlass           ItemID = 382
	ItemYellowStainedGlass              ItemID = 383
	ItemLimeStainedGlass                ItemID = 384
	ItemPinkStainedGlass                ItemID = 385
	ItemGrayStainedGlass                ItemID = 386
	ItemLightGrayStainedGlass           ItemID = 387
	ItemCyanStainedGlass                ItemID = 388
	ItemPurpleStainedGlass              ItemID = 389
	ItemBlueStainedGlass                ItemID = 390
	ItemBrownStainedGlass               ItemID = 391
	ItemGreenStainedGlass               ItemID = 392
	ItemRedStainedGlass                 ItemID = 393
	ItemBlackStainedGlass               ItemID = 394
	ItemWhiteStainedGlassPane           ItemID = 395
	ItemOrangeStainedGlassPane          ItemID = 396
	ItemMagentaStainedGlassPane         ItemID = 397
	ItemLightBlueStainedGlassPane       ItemID = 398
	ItemYellowStainedGlassPane          ItemID = 399
	ItemLimeStainedGlassPane            ItemID = 400
	ItemPinkStainedGlassPane            ItemID = 401
	ItemGrayStainedGlassPane            ItemID = 402
	ItemLightGrayStainedGlassPane       ItemID = 403
	ItemCyanStainedGlassPane            ItemID = 404
	ItemPurpleStainedGlassPane          ItemID = 405
	ItemBlueStainedGlassPane            ItemID = 406
	ItemBrownStainedGlassPane           ItemID = 407
	ItemGreenStainedGlassPane           ItemID = 408
	ItemRedStainedGlassPane             ItemID = 409
	ItemBlackStainedGlassPane           ItemID = 410
	ItemPrismarine                      ItemID = 411
	ItemPrismarineBricks                ItemID = 412
	ItemDarkPrismarine                  ItemID = 413
	ItemPrismarineStairs                ItemID = 414
	ItemPrismarineBrickStairs           ItemID = 415
	ItemDarkPrismarineStairs            ItemID = 416
	ItemSeaLantern                      ItemID = 417
	ItemRedSandstone                    ItemID = 418
	ItemChiseledRedSandstone            ItemID = 419
	ItemCutRedSandstone                 ItemID = 420
	ItemRedSandstoneStairs              ItemID = 421
	ItemRepeatingCommandBlock           ItemID = 422
	ItemChainCommandBlock               ItemID = 423
	ItemMagmaBlock                      ItemID = 424
	ItemNetherWartBlock                 ItemID = 425
	ItemWarpedWartBlock                 ItemID = 426
	ItemRedNetherBricks                 ItemID = 427
	ItemBoneBlock                       ItemID = 428
	ItemStructureVoid                   ItemID = 429
	ItemObserver                        ItemID = 430
	ItemShulkerBox                      ItemID = 431
	ItemWhiteShulkerBox                 ItemID = 432
	ItemOrangeShulkerBox                ItemID = 433
	ItemMagentaShulkerBox               ItemID = 434
	ItemLightBlueShulkerBox             ItemID = 435
	ItemYellowShulkerBox                ItemID = 436
	ItemLimeShulkerBox                  ItemID = 437
	ItemPinkShulkerBox                  ItemID = 438
	ItemGrayShulkerBox                  ItemID = 439
	ItemLightGrayShulkerBox             ItemID = 440
	ItemCyanShulkerBox                  ItemID = 441
	ItemPurpleShulkerBox                ItemID = 442
	ItemBlueShulkerBox                  ItemID = 443
	ItemBrownShulkerBox                 ItemID = 444
	ItemGreenShulkerBox                 ItemID = 445
	ItemRedShulkerBox                   ItemID = 446
	ItemBlackShulkerBox                 ItemID = 447
	ItemWhiteGlazedTerracotta           ItemID = 448
	ItemOrangeGlazedTerracotta          ItemID = 449
	ItemMagentaGlazedTerracotta         ItemID = 450
	ItemLightBlueGlazedTerracotta       ItemID = 451
	ItemYellowGlazedTerracotta          ItemID = 452
	ItemLimeGlazedTerracotta            ItemID = 453
	ItemPinkGlazedTerracotta            ItemID = 454
	ItemGrayGlazedTerracotta            ItemID = 455
	ItemLightGrayGlazedTerracotta       ItemID = 456
	ItemCyanGlazedTerracotta            ItemID = 457
	ItemPurpleGlazedTerracotta          ItemID = 458
	ItemBlueGlazedTerracotta            ItemID = 459
	ItemBrownGlazedTerracotta           ItemID = 460
	ItemGreenGlazedTerracotta           ItemID = 461
	ItemRedGlazedTerracotta             ItemID = 462
	ItemBlackGlazedTerracotta           ItemID = 463
	ItemWhiteConcrete                   ItemID = 464
	ItemOrangeConcrete                  ItemID = 465
	ItemMagentaConcrete                 ItemID = 466
	ItemLightBlueConcrete               ItemID = 467
	ItemYellowConcrete                  ItemID = 468
	ItemLimeConcrete                    ItemID = 469
	ItemPinkConcrete                    ItemID = 470
	ItemGrayConcrete                    ItemID = 471
	ItemLightGrayConcrete               ItemID = 472
	ItemCyanConcrete                    ItemID = 473
	ItemPurpleConcrete                  ItemID = 474
	ItemBlueConcrete                    ItemID = 475
	ItemBrownConcrete                   ItemID = 476
	ItemGreenConcrete                   ItemID = 477
	ItemRedConcrete                     ItemID = 478
	ItemBlackConcrete                   ItemID = 479
	ItemWhiteConcretePowder             ItemID = 480
	ItemOrangeConcretePowder            ItemID = 481
	ItemMagentaConcretePowder           ItemID = 482
	ItemLightBlueConcretePowder         ItemID = 483
	ItemYellowConcretePowder            ItemID = 484
	ItemLimeConcretePowder              ItemID = 485
	ItemPinkConcretePowder              ItemID = 486
	ItemGrayConcretePowder              ItemID = 487
	ItemLightGrayConcretePowder         ItemID = 488
	ItemCyanConcretePowder              ItemID = 489
	ItemPurpleConcretePowder            ItemID = 490
	ItemBlueConcretePowder              ItemID = 491
	ItemBrownConcretePowder             ItemID = 492
	ItemGreenConcretePowder             ItemID = 493
	ItemRedConcretePowder               ItemID = 494
	ItemBlackConcretePowder             ItemID = 495
	ItemTurtleEgg                       ItemID = 496
	ItemDeadTubeCoralBlock              ItemID = 497
	ItemDeadBrainCoralBlock             ItemID = 498
	ItemDeadBubbleCoralBlock            ItemID = 499
	ItemDeadFireCoralBlock              ItemID = 500
	ItemDeadHornCoralBlock              ItemID = 501
	ItemTubeCoralBlock                  ItemID = 502
	ItemBrainCoralBlock                 ItemID = 503
	ItemBubbleCoralBlock                ItemID = 504
	ItemFireCoralBlock                  ItemID = 505
	ItemHornCoralBlock                  ItemID = 506
	ItemTubeCoral                       ItemID = 507
	ItemBrainCoral                      ItemID = 508
	ItemBubbleCoral                     ItemID = 509
	ItemFireCoral                       ItemID = 510
	ItemHornCoral                       ItemID = 511
	ItemDeadBrainCoral                  ItemID = 512
	ItemDeadBubbleCoral                 ItemID = 513
	ItemDeadFireCoral                   ItemID = 514
	ItemDeadHornCoral                   ItemID = 515
	ItemDeadTubeCoral                   ItemID = 516
	ItemTubeCoralFan                    ItemID = 517
	ItemBrainCoralFan                   ItemID = 518
	ItemBubbleCoralFan                  ItemID = 519
	ItemFireCoralFan                    ItemID = 520
	ItemHornCoralFan                    ItemID = 521
	ItemDeadTubeCoralFan                ItemID = 522
	ItemDeadBrainCoralFan               ItemID = 523
	ItemDeadBubbleCoralFan              ItemID = 524
	ItemDeadFireCoralFan                ItemID = 525
	ItemDeadHornCoralFan                ItemID = 526
	ItemBlueIce                         ItemID = 527
	ItemConduit                         ItemID = 528
	ItemPolishedGraniteStairs           ItemID = 529
	ItemSmoothRedSandstoneStairs        ItemID = 530
	ItemMossyStoneBrickStairs           ItemID = 531
	ItemPolishedDioriteStairs           ItemID = 532
	ItemMossyCobblestoneStairs          ItemID = 533
	ItemEndStoneBrickStairs             ItemID = 534
	ItemStoneStairs                     ItemID = 535
	ItemSmoothSandstoneStairs           ItemID = 536
	ItemSmoothQuartzStairs              ItemID = 537
	ItemGraniteStairs                   ItemID = 538
	ItemAndesiteStairs                  ItemID = 539
	ItemRedNetherBrickStairs            ItemID = 540
	ItemPolishedAndesiteStairs          ItemID = 541
	ItemDioriteStairs                   ItemID = 542
	ItemPolishedGraniteSlab             ItemID = 543
	ItemSmoothRedSandstoneSlab          ItemID = 544
	ItemMossyStoneBrickSlab             ItemID = 545
	ItemPolishedDioriteSlab             ItemID = 546
	ItemMossyCobblestoneSlab            ItemID = 547
	ItemEndStoneBrickSlab               ItemID = 548
	ItemSmoothSandstoneSlab             ItemID = 549
	ItemSmoothQuartzSlab                ItemID = 550
	ItemGraniteSlab                     ItemID = 551
	ItemAndesiteSlab                    ItemID = 552
	ItemRedNetherBrickSlab              ItemID = 553
	ItemPolishedAndesiteSlab            ItemID = 554
	ItemDioriteSlab                     ItemID = 555
	ItemScaffolding                     ItemID = 556
	ItemIronDoor                        ItemID = 557
	ItemOakDoor                         ItemID = 558
	ItemSpruceDoor                      ItemID = 559
	ItemBirchDoor                       ItemID = 560
	ItemJungleDoor                      ItemID = 561
	ItemAcaciaDoor                      ItemID = 562
	ItemDarkOakDoor                     ItemID = 563
	ItemCrimsonDoor                     ItemID = 564
	ItemWarpedDoor                      ItemID = 565
	ItemRepeater                        ItemID = 566
	ItemComparator                      ItemID = 567
	ItemStructureBlock                  ItemID = 568
	ItemJigsaw                          ItemID = 569
	ItemTurtleHelmet                    ItemID = 570
	ItemScute                           ItemID = 571
	ItemFlintAndSteel                   ItemID = 572
	ItemApple                           ItemID = 573
	ItemBow                             ItemID = 574
	ItemArrow                           ItemID = 575
	ItemCoal                            ItemID = 576
	ItemCharcoal                        ItemID = 577
	ItemDiamond                         ItemID = 578
	ItemIronIngot                       ItemID = 579
	ItemGoldIngot                       ItemID = 580
	ItemNetheriteIngot                  ItemID = 581
	ItemNetheriteScrap                  ItemID = 582
	ItemWoodenSword                     ItemID = 583
	ItemWoodenShovel                    ItemID = 584
	ItemWoodenPickaxe                   ItemID = 585
	ItemWoodenAxe                       ItemID = 586
	ItemWoodenHoe                       ItemID = 587
	ItemStoneSword                      ItemID = 588
	ItemStoneShovel                     ItemID = 589
	ItemStonePickaxe                    ItemID = 590
	ItemStoneAxe                        ItemID = 591
	ItemStoneHoe                        ItemID = 592
	ItemGoldenSword                     ItemID = 593
	ItemGoldenShovel                    ItemID = 594
	ItemGoldenPickaxe                   ItemID = 595
	ItemGoldenAxe                       ItemID = 596
	ItemGoldenHoe                       ItemID = 597
	ItemIronSword                       ItemID = 598
	ItemIronShovel                      ItemID = 599
	ItemIronPickaxe                     ItemID = 600
	ItemIronAxe                         ItemID = 601
	ItemIronHoe                         ItemID = 602
	ItemDiamondSword                    ItemID = 603
	ItemDiamondShovel                   ItemID = 604
	ItemDiamondPickaxe                  ItemID = 605
	ItemDiamondAxe                      ItemID = 606
	ItemDiamondHoe                      ItemID = 607
	ItemNetheriteSword                  ItemID = 608
	ItemNetheriteShovel                 ItemID = 609
	ItemNetheritePickaxe                ItemID = 610
	ItemNetheriteAxe                    ItemID = 611
	ItemNetheriteHoe                    ItemID = 612
	ItemStick                           ItemID = 613
	ItemBowl                            ItemID = 614
	ItemMushroomStew                    ItemID = 615
	ItemString                          ItemID = 616
	ItemFeather                         ItemID = 617
	ItemGunpowder                       ItemID = 618
	ItemWheatSeeds                      ItemID = 619
	ItemWheat                           ItemID = 620
	ItemBread                           ItemID = 621
	ItemLeatherHelmet                   ItemID = 622
	ItemLeatherChestplate               ItemID = 623
	ItemLeatherLeggings                 ItemID = 624
	ItemLeatherBoots                    ItemID = 625
	ItemChainmailHelmet                 ItemID = 626
	ItemChainmailChestplate             ItemID = 627
	ItemChainmailLeggings               ItemID = 628
	ItemChainmailBoots                  ItemID = 629
	ItemIronHelmet                      ItemID = 630
	ItemIronChestplate                  ItemID = 631
	ItemIronLeggings                    ItemID = 632
	ItemIronBoots                       ItemID = 633
	ItemDiamondHelmet                   ItemID = 634
	ItemDiamondChestplate               ItemID = 635
	ItemDiamondLeggings                 ItemID = 636
	ItemDiamondBoots                    ItemID = 637
	ItemGoldenHelmet                    ItemID = 638
	ItemGoldenChestplate                ItemID = 639
	ItemGoldenLeggings                  ItemID = 640
	ItemGoldenBoots                     ItemID = 641
	ItemNetheriteHelmet                 ItemID = 642
	ItemNetheriteChestplate             ItemID = 643
	ItemNetheriteLeggings               ItemID = 644
	ItemNetheriteBoots                  ItemID = 645
	ItemFlint                           ItemID = 646
	ItemPorkchop                        ItemID = 647
	ItemCookedPorkchop                  ItemID = 648
	ItemPainting                        ItemID = 649
	ItemGoldenApple                     ItemID = 650
	ItemEnchantedGoldenApple            ItemID = 651
	ItemOakSign                         ItemID = 652
	ItemSpruceSign                      ItemID = 653
	ItemBirchSign                       ItemID = 654
	ItemJungleSign                      ItemID = 655
	ItemAcaciaSign                      ItemID = 656
	ItemDarkOakSign                     ItemID = 657
	ItemCrimsonSign                     ItemID = 658
	ItemWarpedSign                      ItemID = 659
	ItemBucket                          ItemID = 660
	ItemWaterBucket                     ItemID = 661
	ItemLavaBucket                      ItemID = 662
	ItemMinecart                        ItemID = 663
	ItemSaddle                          ItemID = 664
	ItemRedstone                        ItemID = 665
	ItemSnowball                        ItemID = 666
	ItemOakBoat                         ItemID = 667
	ItemLeather                         ItemID = 668
	ItemMilkBucket                      ItemID = 669
	ItemPufferfishBucket                ItemID = 670
	ItemSalmonBucket                    ItemID = 671
	ItemCodBucket                       ItemID = 672
	ItemTropicalFishBucket              ItemID = 673
	ItemBrick                           ItemID = 674
	ItemClayBall                        ItemID = 675
	ItemDriedKelpBlock                  ItemID = 676
	ItemPaper                           ItemID = 677
	ItemBook                            ItemID = 678
	ItemSlimeBall                       ItemID = 679
	ItemChestMinecart                   ItemID = 680
	ItemFurnaceMinecart                 ItemID = 681
	ItemEgg                             ItemID = 682
	ItemCompass                         ItemID = 683
	ItemFishingRod                      ItemID = 684
	ItemClock                           ItemID = 685
	ItemGlowstoneDust                   ItemID = 686
	ItemCod                             ItemID = 687
	ItemSalmon                          ItemID = 688
	ItemTropicalFish                    ItemID = 689
	ItemPufferfish                      ItemID = 690
	ItemCookedCod                       ItemID = 691
	ItemCookedSalmon                    ItemID = 692
	ItemInkSac                          ItemID = 693
	ItemCocoaBeans                      ItemID = 694
	ItemLapisLazuli                     ItemID = 695
	ItemWhiteDye                        ItemID = 696
	ItemOrangeDye                       ItemID = 697
	ItemMagentaDye                      ItemID = 698
	ItemLightBlueDye                    ItemID = 699
	ItemYellowDye                       ItemID = 700
	ItemLimeDye                         ItemID = 701
	ItemPinkDye                         ItemID = 702
	ItemGrayDye                         ItemID = 703
	ItemLightGrayDye                    ItemID = 704
	ItemCyanDye                         ItemID = 705
	ItemPurpleDye                       ItemID = 706
	ItemBlueDye                         ItemID = 707
	ItemBrownDye                        ItemID = 708
	ItemGreenDye                        ItemID = 709
	ItemRedDye                          ItemID = 710
	ItemBlackDye                        ItemID = 711
	ItemBoneMeal                        ItemID = 712
	ItemBone                            ItemID = 713
	ItemSugar                           ItemID = 714
	ItemCake                            ItemID = 715
	ItemWhiteBed                        ItemID = 716
	ItemOrangeBed                       ItemID = 717
	ItemMagentaBed                      ItemID = 718
	ItemLightBlueBed                    ItemID = 719
	ItemYellowBed                       ItemID = 720
	ItemLimeBed                         ItemID = 721
	ItemPinkBed                         ItemID = 722
	ItemGrayBed                         ItemID = 723
	ItemLightGrayBed                    ItemID = 724
	ItemCyanBed                         ItemID = 725
	ItemPurpleBed                       ItemID = 726
	ItemBlueBed                         ItemID = 727
	ItemBrownBed                        ItemID = 728
	ItemGreenBed                        ItemID = 729
	ItemRedBed                          ItemID = 730
	ItemBlackBed                        ItemID = 731
	ItemCookie                          ItemID = 732
	ItemFilledMap                       ItemID = 733
	ItemShears                          ItemID = 734
	ItemMelonSlice                      ItemID = 735
	ItemDriedKelp                       ItemID = 736
	ItemPumpkinSeeds                    ItemID = 737
	ItemMelonSeeds                      ItemID = 738
	ItemBeef                            ItemID = 739
	ItemCookedBeef                      ItemID = 740
	ItemChicken                         ItemID = 741
	ItemCookedChicken                   ItemID = 742
	ItemRottenFlesh                     ItemID = 743
	ItemEnderPearl                      ItemID = 744
	ItemBlazeRod                        ItemID = 745
	ItemGhastTear                       ItemID = 746
	ItemGoldNugget                      ItemID = 747
	ItemNetherWart                      ItemID = 748
	ItemPotion                          ItemID = 749
	ItemGlassBottle                     ItemID = 750
	ItemSpiderEye                       ItemID = 751
	ItemFermentedSpiderEye              ItemID = 752
	ItemBlazePowder                     ItemID = 753
	ItemMagmaCream                      ItemID = 754
	ItemBrewingStand                    ItemID = 755
	ItemCauldron                        ItemID = 756
	ItemEnderEye                        ItemID = 757
	ItemGlisteringMelonSlice            ItemID = 758
	ItemBatSpawnEgg                     ItemID = 759
	ItemBeeSpawnEgg                     ItemID = 760
	ItemBlazeSpawnEgg                   ItemID = 761
	ItemCatSpawnEgg                     ItemID = 762
	ItemCaveSpiderSpawnEgg              ItemID = 763
	ItemChickenSpawnEgg                 ItemID = 764
	ItemCodSpawnEgg                     ItemID = 765
	ItemCowSpawnEgg                     ItemID = 766
	ItemCreeperSpawnEgg                 ItemID = 767
	ItemDolphinSpawnEgg                 ItemID = 768
	ItemDonkeySpawnEgg                  ItemID = 769
	ItemDrownedSpawnEgg                 ItemID = 770
	ItemElderGuardianSpawnEgg           ItemID = 771
	ItemEndermanSpawnEgg                ItemID = 772
	ItemEndermiteSpawnEgg               ItemID = 773
	ItemEvokerSpawnEgg                  ItemID = 774
	ItemFoxSpawnEgg                     ItemID = 775
	ItemGhastSpawnEgg                   ItemID = 776
	ItemGuardianSpawnEgg                ItemID = 777
	ItemHoglinSpawnEgg                  ItemID = 778
	ItemHorseSpawnEgg                   ItemID = 779
	ItemHuskSpawnEgg                    ItemID = 780
	ItemLlamaSpawnEgg                   ItemID = 781
	ItemMagmaCubeSpawnEgg               ItemID = 782
	ItemMooshroomSpawnEgg               ItemID = 783
	ItemMuleSpawnEgg                    ItemID = 784
	ItemOcelotSpawnEgg                  ItemID = 785
	ItemPandaSpawnEgg                   ItemID = 786
	ItemParrotSpawnEgg                  ItemID = 787
	ItemPhantomSpawnEgg                 ItemID = 788
	ItemPigSpawnEgg                     ItemID = 789
	ItemPiglinSpawnEgg                  ItemID = 790
	ItemPiglinBruteSpawnEgg             ItemID = 791
	ItemPillagerSpawnEgg                ItemID = 792
	ItemPolarBearSpawnEgg               ItemID = 793
	ItemPufferfishSpawnEgg              ItemID = 794
	ItemRabbitSpawnEgg                  ItemID = 795
	ItemRavagerSpawnEgg                 ItemID = 796
	ItemSalmonSpawnEgg                  ItemID = 797
	ItemSheepSpawnEgg                   ItemID = 798
	ItemShulkerSpawnEgg                 ItemID = 799
	ItemSilverfishSpawnEgg              ItemID = 800
	ItemSkeletonSpawnEgg                ItemID = 801
	ItemSkeletonHorseSpawnEgg           ItemID = 802
	ItemSlimeSpawnEgg                   ItemID = 803
	ItemSpiderSpawnEgg                  ItemID = 804
	ItemSquidSpawnEgg                   ItemID = 805
	ItemStraySpawnEgg                   ItemID = 806
	ItemStriderSpawnEgg                 ItemID = 807
	ItemTraderLlamaSpawnEgg             ItemID = 808
	ItemTropicalFishSpawnEgg            ItemID = 809
	ItemTurtleSpawnEgg                  ItemID = 810
	ItemVexSpawnEgg                     ItemID = 811
	ItemVillagerSpawnEgg                ItemID = 812
	ItemVindicatorSpawnEgg              ItemID = 813
	ItemWanderingTraderSpawnEgg         ItemID = 814
	ItemWitchSpawnEgg                   ItemID = 815
	ItemWitherSkeletonSpawnEgg          ItemID = 816
	ItemWolfSpawnEgg                    ItemID = 817
	ItemZoglinSpawnEgg                  ItemID = 818
	ItemZombieSpawnEgg                  ItemID = 819
	ItemZombieHorseSpawnEgg             ItemID = 820
	ItemZombieVillagerSpawnEgg          ItemID = 821
	ItemZombifiedPiglinSpawnEgg         ItemID = 822
	ItemExperienceBottle                ItemID = 823
	ItemFireCharge                      ItemID = 824
	ItemWritableBook                    ItemID = 825
	ItemWrittenBook                     ItemID = 826
	ItemEmerald                         ItemID = 827
	ItemItemFrame                       ItemID = 828
	ItemFlowerPot                       ItemID = 829
	ItemCarrot                          ItemID = 830
	ItemPotato                          ItemID = 831
	ItemBakedPotato                     ItemID = 832
	ItemPoisonousPotato                 ItemID = 833
	ItemMap                             ItemID = 834
	ItemGoldenCarrot                    ItemID = 835
	ItemSkeletonSkull                   ItemID = 836
	ItemWitherSkeletonSkull             ItemID = 837
	ItemPlayerHead                      ItemID = 838
	ItemZombieHead                      ItemID = 839
	ItemCreeperHead                     ItemID = 840
	ItemDragonHead                      ItemID = 841
	ItemCarrotOnAStick                  ItemID = 842
	ItemWarpedFungusOnAStick            ItemID = 843
	ItemNetherStar                      ItemID = 844
	ItemPumpkinPie                      ItemID = 845
	ItemFireworkRocket                  ItemID = 846
	ItemFireworkStar                    ItemID = 847
	ItemEnchantedBook                   ItemID = 848
	ItemNetherBrick                     ItemID = 849
	ItemQuartz                          ItemID = 850
	ItemTntMinecart                     ItemID = 851
	ItemHopperMinecart                  ItemID = 852
	ItemPrismarineShard                 ItemID = 853
	ItemPrismarineCrystals              ItemID = 854
	ItemRabbit                          ItemID = 855
	ItemCookedRabbit                    ItemID = 856
	ItemRabbitStew                      ItemID = 857
	ItemRabbitFoot                      ItemID = 858
	ItemRabbitHide                      ItemID = 859
	ItemArmorStand                      ItemID = 860
	ItemIronHorseArmor                  ItemID = 861
	ItemGoldenHorseArmor                ItemID = 862
	ItemDiamondHorseArmor               ItemID = 863
	ItemLeatherHorseArmor               ItemID = 864
	ItemLead                            ItemID = 865
	ItemNameTag                         ItemID = 866
	ItemCommandBlockMinecart            ItemID = 867
	ItemMutton                          ItemID = 868
	ItemCookedMutton                    ItemID = 869
	ItemWhiteBanner                     ItemID = 870
	ItemOrangeBanner                    ItemID = 871
	ItemMagentaBanner                   ItemID = 872
	ItemLightBlueBanner                 ItemID = 873
	ItemYellowBanner                    ItemID = 874
	ItemLimeBanner                      ItemID = 875
	ItemPinkBanner                      ItemID = 876
	ItemGrayBanner                      ItemID = 877
	ItemLightGrayBanner                 ItemID = 878
	ItemCyanBanner                      ItemID = 879
	ItemPurpleBanner                    ItemID = 880
	ItemBlueBanner                      ItemID = 881
	ItemBrownBanner                     ItemID = 882
	ItemGreenBanner                     ItemID = 883
	ItemRedBanner                       ItemID = 884
	ItemBlackBanner                     ItemID = 885
	ItemEndCrystal                      ItemID = 886
	ItemChorusFruit                     ItemID = 887
	ItemPoppedChorusFruit               ItemID = 888
	ItemBeetroot                        ItemID = 889
	ItemBeetrootSeeds                   ItemID = 890
	ItemBeetrootSoup                    ItemID = 891
	ItemDragonBreath                    ItemID = 892
	ItemSplashPotion                    ItemID = 893
	ItemSpectralArrow                   ItemID = 894
	ItemTippedArrow                     ItemID = 895
	ItemLingeringPotion                 ItemID = 896
	ItemShield                          ItemID = 897
	ItemElytra                          ItemID = 898
	ItemSpruceBoat                      ItemID = 899
	ItemBirchBoat                       ItemID = 900
	ItemJungleBoat                      ItemID = 901
	ItemAcaciaBoat                      ItemID = 902
	ItemDarkOakBoat                     ItemID = 903
	ItemTotemOfUndying                  ItemID = 904
	ItemShulkerShell                    ItemID = 905
	ItemIronNugget                      ItemID = 906
	ItemKnowledgeBook                   ItemID = 907
	ItemDebugStick                      ItemID = 908
	MusicDisc13                         ItemID = 909
	ItemMusicDiscCat                    ItemID = 910
	ItemMusicDiscBlocks                 ItemID = 911
	ItemMusicDiscChirp                  ItemID = 912
	ItemMusicDiscFar                    ItemID = 913
	ItemMusicDiscMall                   ItemID = 914
	ItemMusicDiscMellohi                ItemID = 915
	ItemMusicDiscStal                   ItemID = 916
	ItemMusicDiscStrad                  ItemID = 917
	ItemMusicDiscWard                   ItemID = 918
	MusicDisc11                         ItemID = 919
	ItemMusicDiscWait                   ItemID = 920
	ItemMusicDiscPigstep                ItemID = 921
	ItemTrident                         ItemID = 922
	ItemPhantomMembrane                 ItemID = 923
	ItemNautilusShell                   ItemID = 924
	ItemHeartOfTheSea                   ItemID = 925
	ItemCrossbow                        ItemID = 926
	ItemSuspiciousStew                  ItemID = 927
	ItemLoom                            ItemID = 928
	ItemFlowerBannerPattern             ItemID = 929
	ItemCreeperBannerPattern            ItemID = 930
	ItemSkullBannerPattern              ItemID = 931
	ItemMojangBannerPattern             ItemID = 932
	ItemGlobeBannerPattern              ItemID = 933
	ItemPiglinBannerPattern             ItemID = 934
	ItemComposter                       ItemID = 935
	ItemBarrel                          ItemID = 936
	ItemSmoker                          ItemID = 937
	ItemBlastFurnace                    ItemID = 938
	ItemCartographyTable                ItemID = 939
	ItemFletchingTable                  ItemID = 940
	ItemGrindstone                      ItemID = 941
	ItemLectern                         ItemID = 942
	ItemSmithingTable                   ItemID = 943
	ItemStonecutter                     ItemID = 944
	ItemBell                            ItemID = 945
	ItemLantern                         ItemID = 946
	ItemSoulLantern                     ItemID = 947
	ItemSweetBerries                    ItemID = 948
	ItemCampfire                        ItemID = 949
	ItemSoulCampfire                    ItemID = 950
	ItemShroomlight                     ItemID = 951
	ItemHoneycomb                       ItemID = 952
	ItemBeeNest                         ItemID = 953
	ItemBeehive                         ItemID = 954
	ItemHoneyBottle                     ItemID = 955
	ItemHoneyBlock                      ItemID = 956
	ItemHoneycombBlock                  ItemID = 957
	ItemLodestone                       ItemID = 958
	ItemNetheriteBlock                  ItemID = 959
	ItemAncientDebris                   ItemID = 960
	ItemTarget                          ItemID = 961
	ItemCryingObsidian                  ItemID = 962
	ItemBlackstone                      ItemID = 963
	ItemBlackstoneSlab                  ItemID = 964
	ItemBlackstoneStairs                ItemID = 965
	ItemGildedBlackstone                ItemID = 966
	ItemPolishedBlackstone              ItemID = 967
	ItemPolishedBlackstoneSlab          ItemID = 968
	ItemPolishedBlackstoneStairs        ItemID = 969
	ItemChiseledPolishedBlackstone      ItemID = 970
	ItemPolishedBlackstoneBricks        ItemID = 971
	ItemPolishedBlackstoneBrickSlab     ItemID = 972
	ItemPolishedBlackstoneBrickStairs   ItemID = 973
	ItemCrackedPolishedBlackstoneBricks ItemID = 974
	ItemRespawnAnchor                   ItemID = 975
)

var itemNamesMap map[ItemID]string

func init() {
	itemNamesMap = make(map[ItemID]string)
	itemNamesMap[0] = "minecraft:air"
	itemNamesMap[1] = "minecraft:stone"
	itemNamesMap[2] = "minecraft:granite"
	itemNamesMap[3] = "minecraft:polished_granite"
	itemNamesMap[4] = "minecraft:diorite"
	itemNamesMap[5] = "minecraft:polished_diorite"
	itemNamesMap[6] = "minecraft:andesite"
	itemNamesMap[7] = "minecraft:polished_andesite"
	itemNamesMap[8] = "minecraft:grass_block"
	itemNamesMap[9] = "minecraft:dirt"
	itemNamesMap[10] = "minecraft:coarse_dirt"
	itemNamesMap[11] = "minecraft:podzol"
	itemNamesMap[12] = "minecraft:crimson_nylium"
	itemNamesMap[13] = "minecraft:warped_nylium"
	itemNamesMap[14] = "minecraft:cobblestone"
	itemNamesMap[15] = "minecraft:oak_planks"
	itemNamesMap[16] = "minecraft:spruce_planks"
	itemNamesMap[17] = "minecraft:birch_planks"
	itemNamesMap[18] = "minecraft:jungle_planks"
	itemNamesMap[19] = "minecraft:acacia_planks"
	itemNamesMap[20] = "minecraft:dark_oak_planks"
	itemNamesMap[21] = "minecraft:crimson_planks"
	itemNamesMap[22] = "minecraft:warped_planks"
	itemNamesMap[23] = "minecraft:oak_sapling"
	itemNamesMap[24] = "minecraft:spruce_sapling"
	itemNamesMap[25] = "minecraft:birch_sapling"
	itemNamesMap[26] = "minecraft:jungle_sapling"
	itemNamesMap[27] = "minecraft:acacia_sapling"
	itemNamesMap[28] = "minecraft:dark_oak_sapling"
	itemNamesMap[29] = "minecraft:bedrock"
	itemNamesMap[30] = "minecraft:sand"
	itemNamesMap[31] = "minecraft:red_sand"
	itemNamesMap[32] = "minecraft:gravel"
	itemNamesMap[33] = "minecraft:gold_ore"
	itemNamesMap[34] = "minecraft:iron_ore"
	itemNamesMap[35] = "minecraft:coal_ore"
	itemNamesMap[36] = "minecraft:nether_gold_ore"
	itemNamesMap[37] = "minecraft:oak_log"
	itemNamesMap[38] = "minecraft:spruce_log"
	itemNamesMap[39] = "minecraft:birch_log"
	itemNamesMap[40] = "minecraft:jungle_log"
	itemNamesMap[41] = "minecraft:acacia_log"
	itemNamesMap[42] = "minecraft:dark_oak_log"
	itemNamesMap[43] = "minecraft:crimson_stem"
	itemNamesMap[44] = "minecraft:warped_stem"
	itemNamesMap[45] = "minecraft:stripped_oak_log"
	itemNamesMap[46] = "minecraft:stripped_spruce_log"
	itemNamesMap[47] = "minecraft:stripped_birch_log"
	itemNamesMap[48] = "minecraft:stripped_jungle_log"
	itemNamesMap[49] = "minecraft:stripped_acacia_log"
	itemNamesMap[50] = "minecraft:stripped_dark_oak_log"
	itemNamesMap[51] = "minecraft:stripped_crimson_stem"
	itemNamesMap[52] = "minecraft:stripped_warped_stem"
	itemNamesMap[53] = "minecraft:stripped_oak_wood"
	itemNamesMap[54] = "minecraft:stripped_spruce_wood"
	itemNamesMap[55] = "minecraft:stripped_birch_wood"
	itemNamesMap[56] = "minecraft:stripped_jungle_wood"
	itemNamesMap[57] = "minecraft:stripped_acacia_wood"
	itemNamesMap[58] = "minecraft:stripped_dark_oak_wood"
	itemNamesMap[59] = "minecraft:stripped_crimson_hyphae"
	itemNamesMap[60] = "minecraft:stripped_warped_hyphae"
	itemNamesMap[61] = "minecraft:oak_wood"
	itemNamesMap[62] = "minecraft:spruce_wood"
	itemNamesMap[63] = "minecraft:birch_wood"
	itemNamesMap[64] = "minecraft:jungle_wood"
	itemNamesMap[65] = "minecraft:acacia_wood"
	itemNamesMap[66] = "minecraft:dark_oak_wood"
	itemNamesMap[67] = "minecraft:crimson_hyphae"
	itemNamesMap[68] = "minecraft:warped_hyphae"
	itemNamesMap[69] = "minecraft:oak_leaves"
	itemNamesMap[70] = "minecraft:spruce_leaves"
	itemNamesMap[71] = "minecraft:birch_leaves"
	itemNamesMap[72] = "minecraft:jungle_leaves"
	itemNamesMap[73] = "minecraft:acacia_leaves"
	itemNamesMap[74] = "minecraft:dark_oak_leaves"
	itemNamesMap[75] = "minecraft:sponge"
	itemNamesMap[76] = "minecraft:wet_sponge"
	itemNamesMap[77] = "minecraft:glass"
	itemNamesMap[78] = "minecraft:lapis_ore"
	itemNamesMap[79] = "minecraft:lapis_block"
	itemNamesMap[80] = "minecraft:dispenser"
	itemNamesMap[81] = "minecraft:sandstone"
	itemNamesMap[82] = "minecraft:chiseled_sandstone"
	itemNamesMap[83] = "minecraft:cut_sandstone"
	itemNamesMap[84] = "minecraft:note_block"
	itemNamesMap[85] = "minecraft:powered_rail"
	itemNamesMap[86] = "minecraft:detector_rail"
	itemNamesMap[87] = "minecraft:sticky_piston"
	itemNamesMap[88] = "minecraft:cobweb"
	itemNamesMap[89] = "minecraft:grass"
	itemNamesMap[90] = "minecraft:fern"
	itemNamesMap[91] = "minecraft:dead_bush"
	itemNamesMap[92] = "minecraft:seagrass"
	itemNamesMap[93] = "minecraft:sea_pickle"
	itemNamesMap[94] = "minecraft:piston"
	itemNamesMap[95] = "minecraft:white_wool"
	itemNamesMap[96] = "minecraft:orange_wool"
	itemNamesMap[97] = "minecraft:magenta_wool"
	itemNamesMap[98] = "minecraft:light_blue_wool"
	itemNamesMap[99] = "minecraft:yellow_wool"
	itemNamesMap[100] = "minecraft:lime_wool"
	itemNamesMap[101] = "minecraft:pink_wool"
	itemNamesMap[102] = "minecraft:gray_wool"
	itemNamesMap[103] = "minecraft:light_gray_wool"
	itemNamesMap[104] = "minecraft:cyan_wool"
	itemNamesMap[105] = "minecraft:purple_wool"
	itemNamesMap[106] = "minecraft:blue_wool"
	itemNamesMap[107] = "minecraft:brown_wool"
	itemNamesMap[108] = "minecraft:green_wool"
	itemNamesMap[109] = "minecraft:red_wool"
	itemNamesMap[110] = "minecraft:black_wool"
	itemNamesMap[111] = "minecraft:dandelion"
	itemNamesMap[112] = "minecraft:poppy"
	itemNamesMap[113] = "minecraft:blue_orchid"
	itemNamesMap[114] = "minecraft:allium"
	itemNamesMap[115] = "minecraft:azure_bluet"
	itemNamesMap[116] = "minecraft:red_tulip"
	itemNamesMap[117] = "minecraft:orange_tulip"
	itemNamesMap[118] = "minecraft:white_tulip"
	itemNamesMap[119] = "minecraft:pink_tulip"
	itemNamesMap[120] = "minecraft:oxeye_daisy"
	itemNamesMap[121] = "minecraft:cornflower"
	itemNamesMap[122] = "minecraft:lily_of_the_valley"
	itemNamesMap[123] = "minecraft:wither_rose"
	itemNamesMap[124] = "minecraft:brown_mushroom"
	itemNamesMap[125] = "minecraft:red_mushroom"
	itemNamesMap[126] = "minecraft:crimson_fungus"
	itemNamesMap[127] = "minecraft:warped_fungus"
	itemNamesMap[128] = "minecraft:crimson_roots"
	itemNamesMap[129] = "minecraft:warped_roots"
	itemNamesMap[130] = "minecraft:nether_sprouts"
	itemNamesMap[131] = "minecraft:weeping_vines"
	itemNamesMap[132] = "minecraft:twisting_vines"
	itemNamesMap[133] = "minecraft:sugar_cane"
	itemNamesMap[134] = "minecraft:kelp"
	itemNamesMap[135] = "minecraft:bamboo"
	itemNamesMap[136] = "minecraft:gold_block"
	itemNamesMap[137] = "minecraft:iron_block"
	itemNamesMap[138] = "minecraft:oak_slab"
	itemNamesMap[139] = "minecraft:spruce_slab"
	itemNamesMap[140] = "minecraft:birch_slab"
	itemNamesMap[141] = "minecraft:jungle_slab"
	itemNamesMap[142] = "minecraft:acacia_slab"
	itemNamesMap[143] = "minecraft:dark_oak_slab"
	itemNamesMap[144] = "minecraft:crimson_slab"
	itemNamesMap[145] = "minecraft:warped_slab"
	itemNamesMap[146] = "minecraft:stone_slab"
	itemNamesMap[147] = "minecraft:smooth_stone_slab"
	itemNamesMap[148] = "minecraft:sandstone_slab"
	itemNamesMap[149] = "minecraft:cut_sandstone_slab"
	itemNamesMap[150] = "minecraft:petrified_oak_slab"
	itemNamesMap[151] = "minecraft:cobblestone_slab"
	itemNamesMap[152] = "minecraft:brick_slab"
	itemNamesMap[153] = "minecraft:stone_brick_slab"
	itemNamesMap[154] = "minecraft:nether_brick_slab"
	itemNamesMap[155] = "minecraft:quartz_slab"
	itemNamesMap[156] = "minecraft:red_sandstone_slab"
	itemNamesMap[157] = "minecraft:cut_red_sandstone_slab"
	itemNamesMap[158] = "minecraft:purpur_slab"
	itemNamesMap[159] = "minecraft:prismarine_slab"
	itemNamesMap[160] = "minecraft:prismarine_brick_slab"
	itemNamesMap[161] = "minecraft:dark_prismarine_slab"
	itemNamesMap[162] = "minecraft:smooth_quartz"
	itemNamesMap[163] = "minecraft:smooth_red_sandstone"
	itemNamesMap[164] = "minecraft:smooth_sandstone"
	itemNamesMap[165] = "minecraft:smooth_stone"
	itemNamesMap[166] = "minecraft:bricks"
	itemNamesMap[167] = "minecraft:tnt"
	itemNamesMap[168] = "minecraft:bookshelf"
	itemNamesMap[169] = "minecraft:mossy_cobblestone"
	itemNamesMap[170] = "minecraft:obsidian"
	itemNamesMap[171] = "minecraft:torch"
	itemNamesMap[172] = "minecraft:end_rod"
	itemNamesMap[173] = "minecraft:chorus_plant"
	itemNamesMap[174] = "minecraft:chorus_flower"
	itemNamesMap[175] = "minecraft:purpur_block"
	itemNamesMap[176] = "minecraft:purpur_pillar"
	itemNamesMap[177] = "minecraft:purpur_stairs"
	itemNamesMap[178] = "minecraft:spawner"
	itemNamesMap[179] = "minecraft:oak_stairs"
	itemNamesMap[180] = "minecraft:chest"
	itemNamesMap[181] = "minecraft:diamond_ore"
	itemNamesMap[182] = "minecraft:diamond_block"
	itemNamesMap[183] = "minecraft:crafting_table"
	itemNamesMap[184] = "minecraft:farmland"
	itemNamesMap[185] = "minecraft:furnace"
	itemNamesMap[186] = "minecraft:ladder"
	itemNamesMap[187] = "minecraft:rail"
	itemNamesMap[188] = "minecraft:cobblestone_stairs"
	itemNamesMap[189] = "minecraft:lever"
	itemNamesMap[190] = "minecraft:stone_pressure_plate"
	itemNamesMap[191] = "minecraft:oak_pressure_plate"
	itemNamesMap[192] = "minecraft:spruce_pressure_plate"
	itemNamesMap[193] = "minecraft:birch_pressure_plate"
	itemNamesMap[194] = "minecraft:jungle_pressure_plate"
	itemNamesMap[195] = "minecraft:acacia_pressure_plate"
	itemNamesMap[196] = "minecraft:dark_oak_pressure_plate"
	itemNamesMap[197] = "minecraft:crimson_pressure_plate"
	itemNamesMap[198] = "minecraft:warped_pressure_plate"
	itemNamesMap[199] = "minecraft:polished_blackstone_pressure_plate"
	itemNamesMap[200] = "minecraft:redstone_ore"
	itemNamesMap[201] = "minecraft:redstone_torch"
	itemNamesMap[202] = "minecraft:snow"
	itemNamesMap[203] = "minecraft:ice"
	itemNamesMap[204] = "minecraft:snow_block"
	itemNamesMap[205] = "minecraft:cactus"
	itemNamesMap[206] = "minecraft:clay"
	itemNamesMap[207] = "minecraft:jukebox"
	itemNamesMap[208] = "minecraft:oak_fence"
	itemNamesMap[209] = "minecraft:spruce_fence"
	itemNamesMap[210] = "minecraft:birch_fence"
	itemNamesMap[211] = "minecraft:jungle_fence"
	itemNamesMap[212] = "minecraft:acacia_fence"
	itemNamesMap[213] = "minecraft:dark_oak_fence"
	itemNamesMap[214] = "minecraft:crimson_fence"
	itemNamesMap[215] = "minecraft:warped_fence"
	itemNamesMap[216] = "minecraft:pumpkin"
	itemNamesMap[217] = "minecraft:carved_pumpkin"
	itemNamesMap[218] = "minecraft:netherrack"
	itemNamesMap[219] = "minecraft:soul_sand"
	itemNamesMap[220] = "minecraft:soul_soil"
	itemNamesMap[221] = "minecraft:basalt"
	itemNamesMap[222] = "minecraft:polished_basalt"
	itemNamesMap[223] = "minecraft:soul_torch"
	itemNamesMap[224] = "minecraft:glowstone"
	itemNamesMap[225] = "minecraft:jack_o_lantern"
	itemNamesMap[226] = "minecraft:oak_trapdoor"
	itemNamesMap[227] = "minecraft:spruce_trapdoor"
	itemNamesMap[228] = "minecraft:birch_trapdoor"
	itemNamesMap[229] = "minecraft:jungle_trapdoor"
	itemNamesMap[230] = "minecraft:acacia_trapdoor"
	itemNamesMap[231] = "minecraft:dark_oak_trapdoor"
	itemNamesMap[232] = "minecraft:crimson_trapdoor"
	itemNamesMap[233] = "minecraft:warped_trapdoor"
	itemNamesMap[234] = "minecraft:infested_stone"
	itemNamesMap[235] = "minecraft:infested_cobblestone"
	itemNamesMap[236] = "minecraft:infested_stone_bricks"
	itemNamesMap[237] = "minecraft:infested_mossy_stone_bricks"
	itemNamesMap[238] = "minecraft:infested_cracked_stone_bricks"
	itemNamesMap[239] = "minecraft:infested_chiseled_stone_bricks"
	itemNamesMap[240] = "minecraft:stone_bricks"
	itemNamesMap[241] = "minecraft:mossy_stone_bricks"
	itemNamesMap[242] = "minecraft:cracked_stone_bricks"
	itemNamesMap[243] = "minecraft:chiseled_stone_bricks"
	itemNamesMap[244] = "minecraft:brown_mushroom_block"
	itemNamesMap[245] = "minecraft:red_mushroom_block"
	itemNamesMap[246] = "minecraft:mushroom_stem"
	itemNamesMap[247] = "minecraft:iron_bars"
	itemNamesMap[248] = "minecraft:chain"
	itemNamesMap[249] = "minecraft:glass_pane"
	itemNamesMap[250] = "minecraft:melon"
	itemNamesMap[251] = "minecraft:vine"
	itemNamesMap[252] = "minecraft:oak_fence_gate"
	itemNamesMap[253] = "minecraft:spruce_fence_gate"
	itemNamesMap[254] = "minecraft:birch_fence_gate"
	itemNamesMap[255] = "minecraft:jungle_fence_gate"
	itemNamesMap[256] = "minecraft:acacia_fence_gate"
	itemNamesMap[257] = "minecraft:dark_oak_fence_gate"
	itemNamesMap[258] = "minecraft:crimson_fence_gate"
	itemNamesMap[259] = "minecraft:warped_fence_gate"
	itemNamesMap[260] = "minecraft:brick_stairs"
	itemNamesMap[261] = "minecraft:stone_brick_stairs"
	itemNamesMap[262] = "minecraft:mycelium"
	itemNamesMap[263] = "minecraft:lily_pad"
	itemNamesMap[264] = "minecraft:nether_bricks"
	itemNamesMap[265] = "minecraft:cracked_nether_bricks"
	itemNamesMap[266] = "minecraft:chiseled_nether_bricks"
	itemNamesMap[267] = "minecraft:nether_brick_fence"
	itemNamesMap[268] = "minecraft:nether_brick_stairs"
	itemNamesMap[269] = "minecraft:enchanting_table"
	itemNamesMap[270] = "minecraft:end_portal_frame"
	itemNamesMap[271] = "minecraft:end_stone"
	itemNamesMap[272] = "minecraft:end_stone_bricks"
	itemNamesMap[273] = "minecraft:dragon_egg"
	itemNamesMap[274] = "minecraft:redstone_lamp"
	itemNamesMap[275] = "minecraft:sandstone_stairs"
	itemNamesMap[276] = "minecraft:emerald_ore"
	itemNamesMap[277] = "minecraft:ender_chest"
	itemNamesMap[278] = "minecraft:tripwire_hook"
	itemNamesMap[279] = "minecraft:emerald_block"
	itemNamesMap[280] = "minecraft:spruce_stairs"
	itemNamesMap[281] = "minecraft:birch_stairs"
	itemNamesMap[282] = "minecraft:jungle_stairs"
	itemNamesMap[283] = "minecraft:crimson_stairs"
	itemNamesMap[284] = "minecraft:warped_stairs"
	itemNamesMap[285] = "minecraft:command_block"
	itemNamesMap[286] = "minecraft:beacon"
	itemNamesMap[287] = "minecraft:cobblestone_wall"
	itemNamesMap[288] = "minecraft:mossy_cobblestone_wall"
	itemNamesMap[289] = "minecraft:brick_wall"
	itemNamesMap[290] = "minecraft:prismarine_wall"
	itemNamesMap[291] = "minecraft:red_sandstone_wall"
	itemNamesMap[292] = "minecraft:mossy_stone_brick_wall"
	itemNamesMap[293] = "minecraft:granite_wall"
	itemNamesMap[294] = "minecraft:stone_brick_wall"
	itemNamesMap[295] = "minecraft:nether_brick_wall"
	itemNamesMap[296] = "minecraft:andesite_wall"
	itemNamesMap[297] = "minecraft:red_nether_brick_wall"
	itemNamesMap[298] = "minecraft:sandstone_wall"
	itemNamesMap[299] = "minecraft:end_stone_brick_wall"
	itemNamesMap[300] = "minecraft:diorite_wall"
	itemNamesMap[301] = "minecraft:blackstone_wall"
	itemNamesMap[302] = "minecraft:polished_blackstone_wall"
	itemNamesMap[303] = "minecraft:polished_blackstone_brick_wall"
	itemNamesMap[304] = "minecraft:stone_button"
	itemNamesMap[305] = "minecraft:oak_button"
	itemNamesMap[306] = "minecraft:spruce_button"
	itemNamesMap[307] = "minecraft:birch_button"
	itemNamesMap[308] = "minecraft:jungle_button"
	itemNamesMap[309] = "minecraft:acacia_button"
	itemNamesMap[310] = "minecraft:dark_oak_button"
	itemNamesMap[311] = "minecraft:crimson_button"
	itemNamesMap[312] = "minecraft:warped_button"
	itemNamesMap[313] = "minecraft:polished_blackstone_button"
	itemNamesMap[314] = "minecraft:anvil"
	itemNamesMap[315] = "minecraft:chipped_anvil"
	itemNamesMap[316] = "minecraft:damaged_anvil"
	itemNamesMap[317] = "minecraft:trapped_chest"
	itemNamesMap[318] = "minecraft:light_weighted_pressure_plate"
	itemNamesMap[319] = "minecraft:heavy_weighted_pressure_plate"
	itemNamesMap[320] = "minecraft:daylight_detector"
	itemNamesMap[321] = "minecraft:redstone_block"
	itemNamesMap[322] = "minecraft:nether_quartz_ore"
	itemNamesMap[323] = "minecraft:hopper"
	itemNamesMap[324] = "minecraft:chiseled_quartz_block"
	itemNamesMap[325] = "minecraft:quartz_block"
	itemNamesMap[326] = "minecraft:quartz_bricks"
	itemNamesMap[327] = "minecraft:quartz_pillar"
	itemNamesMap[328] = "minecraft:quartz_stairs"
	itemNamesMap[329] = "minecraft:activator_rail"
	itemNamesMap[330] = "minecraft:dropper"
	itemNamesMap[331] = "minecraft:white_terracotta"
	itemNamesMap[332] = "minecraft:orange_terracotta"
	itemNamesMap[333] = "minecraft:magenta_terracotta"
	itemNamesMap[334] = "minecraft:light_blue_terracotta"
	itemNamesMap[335] = "minecraft:yellow_terracotta"
	itemNamesMap[336] = "minecraft:lime_terracotta"
	itemNamesMap[337] = "minecraft:pink_terracotta"
	itemNamesMap[338] = "minecraft:gray_terracotta"
	itemNamesMap[339] = "minecraft:light_gray_terracotta"
	itemNamesMap[340] = "minecraft:cyan_terracotta"
	itemNamesMap[341] = "minecraft:purple_terracotta"
	itemNamesMap[342] = "minecraft:blue_terracotta"
	itemNamesMap[343] = "minecraft:brown_terracotta"
	itemNamesMap[344] = "minecraft:green_terracotta"
	itemNamesMap[345] = "minecraft:red_terracotta"
	itemNamesMap[346] = "minecraft:black_terracotta"
	itemNamesMap[347] = "minecraft:barrier"
	itemNamesMap[348] = "minecraft:iron_trapdoor"
	itemNamesMap[349] = "minecraft:hay_block"
	itemNamesMap[350] = "minecraft:white_carpet"
	itemNamesMap[351] = "minecraft:orange_carpet"
	itemNamesMap[352] = "minecraft:magenta_carpet"
	itemNamesMap[353] = "minecraft:light_blue_carpet"
	itemNamesMap[354] = "minecraft:yellow_carpet"
	itemNamesMap[355] = "minecraft:lime_carpet"
	itemNamesMap[356] = "minecraft:pink_carpet"
	itemNamesMap[357] = "minecraft:gray_carpet"
	itemNamesMap[358] = "minecraft:light_gray_carpet"
	itemNamesMap[359] = "minecraft:cyan_carpet"
	itemNamesMap[360] = "minecraft:purple_carpet"
	itemNamesMap[361] = "minecraft:blue_carpet"
	itemNamesMap[362] = "minecraft:brown_carpet"
	itemNamesMap[363] = "minecraft:green_carpet"
	itemNamesMap[364] = "minecraft:red_carpet"
	itemNamesMap[365] = "minecraft:black_carpet"
	itemNamesMap[366] = "minecraft:terracotta"
	itemNamesMap[367] = "minecraft:coal_block"
	itemNamesMap[368] = "minecraft:packed_ice"
	itemNamesMap[369] = "minecraft:acacia_stairs"
	itemNamesMap[370] = "minecraft:dark_oak_stairs"
	itemNamesMap[371] = "minecraft:slime_block"
	itemNamesMap[372] = "minecraft:grass_path"
	itemNamesMap[373] = "minecraft:sunflower"
	itemNamesMap[374] = "minecraft:lilac"
	itemNamesMap[375] = "minecraft:rose_bush"
	itemNamesMap[376] = "minecraft:peony"
	itemNamesMap[377] = "minecraft:tall_grass"
	itemNamesMap[378] = "minecraft:large_fern"
	itemNamesMap[379] = "minecraft:white_stained_glass"
	itemNamesMap[380] = "minecraft:orange_stained_glass"
	itemNamesMap[381] = "minecraft:magenta_stained_glass"
	itemNamesMap[382] = "minecraft:light_blue_stained_glass"
	itemNamesMap[383] = "minecraft:yellow_stained_glass"
	itemNamesMap[384] = "minecraft:lime_stained_glass"
	itemNamesMap[385] = "minecraft:pink_stained_glass"
	itemNamesMap[386] = "minecraft:gray_stained_glass"
	itemNamesMap[387] = "minecraft:light_gray_stained_glass"
	itemNamesMap[388] = "minecraft:cyan_stained_glass"
	itemNamesMap[389] = "minecraft:purple_stained_glass"
	itemNamesMap[390] = "minecraft:blue_stained_glass"
	itemNamesMap[391] = "minecraft:brown_stained_glass"
	itemNamesMap[392] = "minecraft:green_stained_glass"
	itemNamesMap[393] = "minecraft:red_stained_glass"
	itemNamesMap[394] = "minecraft:black_stained_glass"
	itemNamesMap[395] = "minecraft:white_stained_glass_pane"
	itemNamesMap[396] = "minecraft:orange_stained_glass_pane"
	itemNamesMap[397] = "minecraft:magenta_stained_glass_pane"
	itemNamesMap[398] = "minecraft:light_blue_stained_glass_pane"
	itemNamesMap[399] = "minecraft:yellow_stained_glass_pane"
	itemNamesMap[400] = "minecraft:lime_stained_glass_pane"
	itemNamesMap[401] = "minecraft:pink_stained_glass_pane"
	itemNamesMap[402] = "minecraft:gray_stained_glass_pane"
	itemNamesMap[403] = "minecraft:light_gray_stained_glass_pane"
	itemNamesMap[404] = "minecraft:cyan_stained_glass_pane"
	itemNamesMap[405] = "minecraft:purple_stained_glass_pane"
	itemNamesMap[406] = "minecraft:blue_stained_glass_pane"
	itemNamesMap[407] = "minecraft:brown_stained_glass_pane"
	itemNamesMap[408] = "minecraft:green_stained_glass_pane"
	itemNamesMap[409] = "minecraft:red_stained_glass_pane"
	itemNamesMap[410] = "minecraft:black_stained_glass_pane"
	itemNamesMap[411] = "minecraft:prismarine"
	itemNamesMap[412] = "minecraft:prismarine_bricks"
	itemNamesMap[413] = "minecraft:dark_prismarine"
	itemNamesMap[414] = "minecraft:prismarine_stairs"
	itemNamesMap[415] = "minecraft:prismarine_brick_stairs"
	itemNamesMap[416] = "minecraft:dark_prismarine_stairs"
	itemNamesMap[417] = "minecraft:sea_lantern"
	itemNamesMap[418] = "minecraft:red_sandstone"
	itemNamesMap[419] = "minecraft:chiseled_red_sandstone"
	itemNamesMap[420] = "minecraft:cut_red_sandstone"
	itemNamesMap[421] = "minecraft:red_sandstone_stairs"
	itemNamesMap[422] = "minecraft:repeating_command_block"
	itemNamesMap[423] = "minecraft:chain_command_block"
	itemNamesMap[424] = "minecraft:magma_block"
	itemNamesMap[425] = "minecraft:nether_wart_block"
	itemNamesMap[426] = "minecraft:warped_wart_block"
	itemNamesMap[427] = "minecraft:red_nether_bricks"
	itemNamesMap[428] = "minecraft:bone_block"
	itemNamesMap[429] = "minecraft:structure_void"
	itemNamesMap[430] = "minecraft:observer"
	itemNamesMap[431] = "minecraft:shulker_box"
	itemNamesMap[432] = "minecraft:white_shulker_box"
	itemNamesMap[433] = "minecraft:orange_shulker_box"
	itemNamesMap[434] = "minecraft:magenta_shulker_box"
	itemNamesMap[435] = "minecraft:light_blue_shulker_box"
	itemNamesMap[436] = "minecraft:yellow_shulker_box"
	itemNamesMap[437] = "minecraft:lime_shulker_box"
	itemNamesMap[438] = "minecraft:pink_shulker_box"
	itemNamesMap[439] = "minecraft:gray_shulker_box"
	itemNamesMap[440] = "minecraft:light_gray_shulker_box"
	itemNamesMap[441] = "minecraft:cyan_shulker_box"
	itemNamesMap[442] = "minecraft:purple_shulker_box"
	itemNamesMap[443] = "minecraft:blue_shulker_box"
	itemNamesMap[444] = "minecraft:brown_shulker_box"
	itemNamesMap[445] = "minecraft:green_shulker_box"
	itemNamesMap[446] = "minecraft:red_shulker_box"
	itemNamesMap[447] = "minecraft:black_shulker_box"
	itemNamesMap[448] = "minecraft:white_glazed_terracotta"
	itemNamesMap[449] = "minecraft:orange_glazed_terracotta"
	itemNamesMap[450] = "minecraft:magenta_glazed_terracotta"
	itemNamesMap[451] = "minecraft:light_blue_glazed_terracotta"
	itemNamesMap[452] = "minecraft:yellow_glazed_terracotta"
	itemNamesMap[453] = "minecraft:lime_glazed_terracotta"
	itemNamesMap[454] = "minecraft:pink_glazed_terracotta"
	itemNamesMap[455] = "minecraft:gray_glazed_terracotta"
	itemNamesMap[456] = "minecraft:light_gray_glazed_terracotta"
	itemNamesMap[457] = "minecraft:cyan_glazed_terracotta"
	itemNamesMap[458] = "minecraft:purple_glazed_terracotta"
	itemNamesMap[459] = "minecraft:blue_glazed_terracotta"
	itemNamesMap[460] = "minecraft:brown_glazed_terracotta"
	itemNamesMap[461] = "minecraft:green_glazed_terracotta"
	itemNamesMap[462] = "minecraft:red_glazed_terracotta"
	itemNamesMap[463] = "minecraft:black_glazed_terracotta"
	itemNamesMap[464] = "minecraft:white_concrete"
	itemNamesMap[465] = "minecraft:orange_concrete"
	itemNamesMap[466] = "minecraft:magenta_concrete"
	itemNamesMap[467] = "minecraft:light_blue_concrete"
	itemNamesMap[468] = "minecraft:yellow_concrete"
	itemNamesMap[469] = "minecraft:lime_concrete"
	itemNamesMap[470] = "minecraft:pink_concrete"
	itemNamesMap[471] = "minecraft:gray_concrete"
	itemNamesMap[472] = "minecraft:light_gray_concrete"
	itemNamesMap[473] = "minecraft:cyan_concrete"
	itemNamesMap[474] = "minecraft:purple_concrete"
	itemNamesMap[475] = "minecraft:blue_concrete"
	itemNamesMap[476] = "minecraft:brown_concrete"
	itemNamesMap[477] = "minecraft:green_concrete"
	itemNamesMap[478] = "minecraft:red_concrete"
	itemNamesMap[479] = "minecraft:black_concrete"
	itemNamesMap[480] = "minecraft:white_concrete_powder"
	itemNamesMap[481] = "minecraft:orange_concrete_powder"
	itemNamesMap[482] = "minecraft:magenta_concrete_powder"
	itemNamesMap[483] = "minecraft:light_blue_concrete_powder"
	itemNamesMap[484] = "minecraft:yellow_concrete_powder"
	itemNamesMap[485] = "minecraft:lime_concrete_powder"
	itemNamesMap[486] = "minecraft:pink_concrete_powder"
	itemNamesMap[487] = "minecraft:gray_concrete_powder"
	itemNamesMap[488] = "minecraft:light_gray_concrete_powder"
	itemNamesMap[489] = "minecraft:cyan_concrete_powder"
	itemNamesMap[490] = "minecraft:purple_concrete_powder"
	itemNamesMap[491] = "minecraft:blue_concrete_powder"
	itemNamesMap[492] = "minecraft:brown_concrete_powder"
	itemNamesMap[493] = "minecraft:green_concrete_powder"
	itemNamesMap[494] = "minecraft:red_concrete_powder"
	itemNamesMap[495] = "minecraft:black_concrete_powder"
	itemNamesMap[496] = "minecraft:turtle_egg"
	itemNamesMap[497] = "minecraft:dead_tube_coral_block"
	itemNamesMap[498] = "minecraft:dead_brain_coral_block"
	itemNamesMap[499] = "minecraft:dead_bubble_coral_block"
	itemNamesMap[500] = "minecraft:dead_fire_coral_block"
	itemNamesMap[501] = "minecraft:dead_horn_coral_block"
	itemNamesMap[502] = "minecraft:tube_coral_block"
	itemNamesMap[503] = "minecraft:brain_coral_block"
	itemNamesMap[504] = "minecraft:bubble_coral_block"
	itemNamesMap[505] = "minecraft:fire_coral_block"
	itemNamesMap[506] = "minecraft:horn_coral_block"
	itemNamesMap[507] = "minecraft:tube_coral"
	itemNamesMap[508] = "minecraft:brain_coral"
	itemNamesMap[509] = "minecraft:bubble_coral"
	itemNamesMap[510] = "minecraft:fire_coral"
	itemNamesMap[511] = "minecraft:horn_coral"
	itemNamesMap[512] = "minecraft:dead_brain_coral"
	itemNamesMap[513] = "minecraft:dead_bubble_coral"
	itemNamesMap[514] = "minecraft:dead_fire_coral"
	itemNamesMap[515] = "minecraft:dead_horn_coral"
	itemNamesMap[516] = "minecraft:dead_tube_coral"
	itemNamesMap[517] = "minecraft:tube_coral_fan"
	itemNamesMap[518] = "minecraft:brain_coral_fan"
	itemNamesMap[519] = "minecraft:bubble_coral_fan"
	itemNamesMap[520] = "minecraft:fire_coral_fan"
	itemNamesMap[521] = "minecraft:horn_coral_fan"
	itemNamesMap[522] = "minecraft:dead_tube_coral_fan"
	itemNamesMap[523] = "minecraft:dead_brain_coral_fan"
	itemNamesMap[524] = "minecraft:dead_bubble_coral_fan"
	itemNamesMap[525] = "minecraft:dead_fire_coral_fan"
	itemNamesMap[526] = "minecraft:dead_horn_coral_fan"
	itemNamesMap[527] = "minecraft:blue_ice"
	itemNamesMap[528] = "minecraft:conduit"
	itemNamesMap[529] = "minecraft:polished_granite_stairs"
	itemNamesMap[530] = "minecraft:smooth_red_sandstone_stairs"
	itemNamesMap[531] = "minecraft:mossy_stone_brick_stairs"
	itemNamesMap[532] = "minecraft:polished_diorite_stairs"
	itemNamesMap[533] = "minecraft:mossy_cobblestone_stairs"
	itemNamesMap[534] = "minecraft:end_stone_brick_stairs"
	itemNamesMap[535] = "minecraft:stone_stairs"
	itemNamesMap[536] = "minecraft:smooth_sandstone_stairs"
	itemNamesMap[537] = "minecraft:smooth_quartz_stairs"
	itemNamesMap[538] = "minecraft:granite_stairs"
	itemNamesMap[539] = "minecraft:andesite_stairs"
	itemNamesMap[540] = "minecraft:red_nether_brick_stairs"
	itemNamesMap[541] = "minecraft:polished_andesite_stairs"
	itemNamesMap[542] = "minecraft:diorite_stairs"
	itemNamesMap[543] = "minecraft:polished_granite_slab"
	itemNamesMap[544] = "minecraft:smooth_red_sandstone_slab"
	itemNamesMap[545] = "minecraft:mossy_stone_brick_slab"
	itemNamesMap[546] = "minecraft:polished_diorite_slab"
	itemNamesMap[547] = "minecraft:mossy_cobblestone_slab"
	itemNamesMap[548] = "minecraft:end_stone_brick_slab"
	itemNamesMap[549] = "minecraft:smooth_sandstone_slab"
	itemNamesMap[550] = "minecraft:smooth_quartz_slab"
	itemNamesMap[551] = "minecraft:granite_slab"
	itemNamesMap[552] = "minecraft:andesite_slab"
	itemNamesMap[553] = "minecraft:red_nether_brick_slab"
	itemNamesMap[554] = "minecraft:polished_andesite_slab"
	itemNamesMap[555] = "minecraft:diorite_slab"
	itemNamesMap[556] = "minecraft:scaffolding"
	itemNamesMap[557] = "minecraft:iron_door"
	itemNamesMap[558] = "minecraft:oak_door"
	itemNamesMap[559] = "minecraft:spruce_door"
	itemNamesMap[560] = "minecraft:birch_door"
	itemNamesMap[561] = "minecraft:jungle_door"
	itemNamesMap[562] = "minecraft:acacia_door"
	itemNamesMap[563] = "minecraft:dark_oak_door"
	itemNamesMap[564] = "minecraft:crimson_door"
	itemNamesMap[565] = "minecraft:warped_door"
	itemNamesMap[566] = "minecraft:repeater"
	itemNamesMap[567] = "minecraft:comparator"
	itemNamesMap[568] = "minecraft:structure_block"
	itemNamesMap[569] = "minecraft:jigsaw"
	itemNamesMap[570] = "minecraft:turtle_helmet"
	itemNamesMap[571] = "minecraft:scute"
	itemNamesMap[572] = "minecraft:flint_and_steel"
	itemNamesMap[573] = "minecraft:apple"
	itemNamesMap[574] = "minecraft:bow"
	itemNamesMap[575] = "minecraft:arrow"
	itemNamesMap[576] = "minecraft:coal"
	itemNamesMap[577] = "minecraft:charcoal"
	itemNamesMap[578] = "minecraft:diamond"
	itemNamesMap[579] = "minecraft:iron_ingot"
	itemNamesMap[580] = "minecraft:gold_ingot"
	itemNamesMap[581] = "minecraft:netherite_ingot"
	itemNamesMap[582] = "minecraft:netherite_scrap"
	itemNamesMap[583] = "minecraft:wooden_sword"
	itemNamesMap[584] = "minecraft:wooden_shovel"
	itemNamesMap[585] = "minecraft:wooden_pickaxe"
	itemNamesMap[586] = "minecraft:wooden_axe"
	itemNamesMap[587] = "minecraft:wooden_hoe"
	itemNamesMap[588] = "minecraft:stone_sword"
	itemNamesMap[589] = "minecraft:stone_shovel"
	itemNamesMap[590] = "minecraft:stone_pickaxe"
	itemNamesMap[591] = "minecraft:stone_axe"
	itemNamesMap[592] = "minecraft:stone_hoe"
	itemNamesMap[593] = "minecraft:golden_sword"
	itemNamesMap[594] = "minecraft:golden_shovel"
	itemNamesMap[595] = "minecraft:golden_pickaxe"
	itemNamesMap[596] = "minecraft:golden_axe"
	itemNamesMap[597] = "minecraft:golden_hoe"
	itemNamesMap[598] = "minecraft:iron_sword"
	itemNamesMap[599] = "minecraft:iron_shovel"
	itemNamesMap[600] = "minecraft:iron_pickaxe"
	itemNamesMap[601] = "minecraft:iron_axe"
	itemNamesMap[602] = "minecraft:iron_hoe"
	itemNamesMap[603] = "minecraft:diamond_sword"
	itemNamesMap[604] = "minecraft:diamond_shovel"
	itemNamesMap[605] = "minecraft:diamond_pickaxe"
	itemNamesMap[606] = "minecraft:diamond_axe"
	itemNamesMap[607] = "minecraft:diamond_hoe"
	itemNamesMap[608] = "minecraft:netherite_sword"
	itemNamesMap[609] = "minecraft:netherite_shovel"
	itemNamesMap[610] = "minecraft:netherite_pickaxe"
	itemNamesMap[611] = "minecraft:netherite_axe"
	itemNamesMap[612] = "minecraft:netherite_hoe"
	itemNamesMap[613] = "minecraft:stick"
	itemNamesMap[614] = "minecraft:bowl"
	itemNamesMap[615] = "minecraft:mushroom_stew"
	itemNamesMap[616] = "minecraft:string"
	itemNamesMap[617] = "minecraft:feather"
	itemNamesMap[618] = "minecraft:gunpowder"
	itemNamesMap[619] = "minecraft:wheat_seeds"
	itemNamesMap[620] = "minecraft:wheat"
	itemNamesMap[621] = "minecraft:bread"
	itemNamesMap[622] = "minecraft:leather_helmet"
	itemNamesMap[623] = "minecraft:leather_chestplate"
	itemNamesMap[624] = "minecraft:leather_leggings"
	itemNamesMap[625] = "minecraft:leather_boots"
	itemNamesMap[626] = "minecraft:chainmail_helmet"
	itemNamesMap[627] = "minecraft:chainmail_chestplate"
	itemNamesMap[628] = "minecraft:chainmail_leggings"
	itemNamesMap[629] = "minecraft:chainmail_boots"
	itemNamesMap[630] = "minecraft:iron_helmet"
	itemNamesMap[631] = "minecraft:iron_chestplate"
	itemNamesMap[632] = "minecraft:iron_leggings"
	itemNamesMap[633] = "minecraft:iron_boots"
	itemNamesMap[634] = "minecraft:diamond_helmet"
	itemNamesMap[635] = "minecraft:diamond_chestplate"
	itemNamesMap[636] = "minecraft:diamond_leggings"
	itemNamesMap[637] = "minecraft:diamond_boots"
	itemNamesMap[638] = "minecraft:golden_helmet"
	itemNamesMap[639] = "minecraft:golden_chestplate"
	itemNamesMap[640] = "minecraft:golden_leggings"
	itemNamesMap[641] = "minecraft:golden_boots"
	itemNamesMap[642] = "minecraft:netherite_helmet"
	itemNamesMap[643] = "minecraft:netherite_chestplate"
	itemNamesMap[644] = "minecraft:netherite_leggings"
	itemNamesMap[645] = "minecraft:netherite_boots"
	itemNamesMap[646] = "minecraft:flint"
	itemNamesMap[647] = "minecraft:porkchop"
	itemNamesMap[648] = "minecraft:cooked_porkchop"
	itemNamesMap[649] = "minecraft:painting"
	itemNamesMap[650] = "minecraft:golden_apple"
	itemNamesMap[651] = "minecraft:enchanted_golden_apple"
	itemNamesMap[652] = "minecraft:oak_sign"
	itemNamesMap[653] = "minecraft:spruce_sign"
	itemNamesMap[654] = "minecraft:birch_sign"
	itemNamesMap[655] = "minecraft:jungle_sign"
	itemNamesMap[656] = "minecraft:acacia_sign"
	itemNamesMap[657] = "minecraft:dark_oak_sign"
	itemNamesMap[658] = "minecraft:crimson_sign"
	itemNamesMap[659] = "minecraft:warped_sign"
	itemNamesMap[660] = "minecraft:bucket"
	itemNamesMap[661] = "minecraft:water_bucket"
	itemNamesMap[662] = "minecraft:lava_bucket"
	itemNamesMap[663] = "minecraft:minecart"
	itemNamesMap[664] = "minecraft:saddle"
	itemNamesMap[665] = "minecraft:redstone"
	itemNamesMap[666] = "minecraft:snowball"
	itemNamesMap[667] = "minecraft:oak_boat"
	itemNamesMap[668] = "minecraft:leather"
	itemNamesMap[669] = "minecraft:milk_bucket"
	itemNamesMap[670] = "minecraft:pufferfish_bucket"
	itemNamesMap[671] = "minecraft:salmon_bucket"
	itemNamesMap[672] = "minecraft:cod_bucket"
	itemNamesMap[673] = "minecraft:tropical_fish_bucket"
	itemNamesMap[674] = "minecraft:brick"
	itemNamesMap[675] = "minecraft:clay_ball"
	itemNamesMap[676] = "minecraft:dried_kelp_block"
	itemNamesMap[677] = "minecraft:paper"
	itemNamesMap[678] = "minecraft:book"
	itemNamesMap[679] = "minecraft:slime_ball"
	itemNamesMap[680] = "minecraft:chest_minecart"
	itemNamesMap[681] = "minecraft:furnace_minecart"
	itemNamesMap[682] = "minecraft:egg"
	itemNamesMap[683] = "minecraft:compass"
	itemNamesMap[684] = "minecraft:fishing_rod"
	itemNamesMap[685] = "minecraft:clock"
	itemNamesMap[686] = "minecraft:glowstone_dust"
	itemNamesMap[687] = "minecraft:cod"
	itemNamesMap[688] = "minecraft:salmon"
	itemNamesMap[689] = "minecraft:tropical_fish"
	itemNamesMap[690] = "minecraft:pufferfish"
	itemNamesMap[691] = "minecraft:cooked_cod"
	itemNamesMap[692] = "minecraft:cooked_salmon"
	itemNamesMap[693] = "minecraft:ink_sac"
	itemNamesMap[694] = "minecraft:cocoa_beans"
	itemNamesMap[695] = "minecraft:lapis_lazuli"
	itemNamesMap[696] = "minecraft:white_dye"
	itemNamesMap[697] = "minecraft:orange_dye"
	itemNamesMap[698] = "minecraft:magenta_dye"
	itemNamesMap[699] = "minecraft:light_blue_dye"
	itemNamesMap[700] = "minecraft:yellow_dye"
	itemNamesMap[701] = "minecraft:lime_dye"
	itemNamesMap[702] = "minecraft:pink_dye"
	itemNamesMap[703] = "minecraft:gray_dye"
	itemNamesMap[704] = "minecraft:light_gray_dye"
	itemNamesMap[705] = "minecraft:cyan_dye"
	itemNamesMap[706] = "minecraft:purple_dye"
	itemNamesMap[707] = "minecraft:blue_dye"
	itemNamesMap[708] = "minecraft:brown_dye"
	itemNamesMap[709] = "minecraft:green_dye"
	itemNamesMap[710] = "minecraft:red_dye"
	itemNamesMap[711] = "minecraft:black_dye"
	itemNamesMap[712] = "minecraft:bone_meal"
	itemNamesMap[713] = "minecraft:bone"
	itemNamesMap[714] = "minecraft:sugar"
	itemNamesMap[715] = "minecraft:cake"
	itemNamesMap[716] = "minecraft:white_bed"
	itemNamesMap[717] = "minecraft:orange_bed"
	itemNamesMap[718] = "minecraft:magenta_bed"
	itemNamesMap[719] = "minecraft:light_blue_bed"
	itemNamesMap[720] = "minecraft:yellow_bed"
	itemNamesMap[721] = "minecraft:lime_bed"
	itemNamesMap[722] = "minecraft:pink_bed"
	itemNamesMap[723] = "minecraft:gray_bed"
	itemNamesMap[724] = "minecraft:light_gray_bed"
	itemNamesMap[725] = "minecraft:cyan_bed"
	itemNamesMap[726] = "minecraft:purple_bed"
	itemNamesMap[727] = "minecraft:blue_bed"
	itemNamesMap[728] = "minecraft:brown_bed"
	itemNamesMap[729] = "minecraft:green_bed"
	itemNamesMap[730] = "minecraft:red_bed"
	itemNamesMap[731] = "minecraft:black_bed"
	itemNamesMap[732] = "minecraft:cookie"
	itemNamesMap[733] = "minecraft:filled_map"
	itemNamesMap[734] = "minecraft:shears"
	itemNamesMap[735] = "minecraft:melon_slice"
	itemNamesMap[736] = "minecraft:dried_kelp"
	itemNamesMap[737] = "minecraft:pumpkin_seeds"
	itemNamesMap[738] = "minecraft:melon_seeds"
	itemNamesMap[739] = "minecraft:beef"
	itemNamesMap[740] = "minecraft:cooked_beef"
	itemNamesMap[741] = "minecraft:chicken"
	itemNamesMap[742] = "minecraft:cooked_chicken"
	itemNamesMap[743] = "minecraft:rotten_flesh"
	itemNamesMap[744] = "minecraft:ender_pearl"
	itemNamesMap[745] = "minecraft:blaze_rod"
	itemNamesMap[746] = "minecraft:ghast_tear"
	itemNamesMap[747] = "minecraft:gold_nugget"
	itemNamesMap[748] = "minecraft:nether_wart"
	itemNamesMap[749] = "minecraft:potion"
	itemNamesMap[750] = "minecraft:glass_bottle"
	itemNamesMap[751] = "minecraft:spider_eye"
	itemNamesMap[752] = "minecraft:fermented_spider_eye"
	itemNamesMap[753] = "minecraft:blaze_powder"
	itemNamesMap[754] = "minecraft:magma_cream"
	itemNamesMap[755] = "minecraft:brewing_stand"
	itemNamesMap[756] = "minecraft:cauldron"
	itemNamesMap[757] = "minecraft:ender_eye"
	itemNamesMap[758] = "minecraft:glistering_melon_slice"
	itemNamesMap[759] = "minecraft:bat_spawn_egg"
	itemNamesMap[760] = "minecraft:bee_spawn_egg"
	itemNamesMap[761] = "minecraft:blaze_spawn_egg"
	itemNamesMap[762] = "minecraft:cat_spawn_egg"
	itemNamesMap[763] = "minecraft:cave_spider_spawn_egg"
	itemNamesMap[764] = "minecraft:chicken_spawn_egg"
	itemNamesMap[765] = "minecraft:cod_spawn_egg"
	itemNamesMap[766] = "minecraft:cow_spawn_egg"
	itemNamesMap[767] = "minecraft:creeper_spawn_egg"
	itemNamesMap[768] = "minecraft:dolphin_spawn_egg"
	itemNamesMap[769] = "minecraft:donkey_spawn_egg"
	itemNamesMap[770] = "minecraft:drowned_spawn_egg"
	itemNamesMap[771] = "minecraft:elder_guardian_spawn_egg"
	itemNamesMap[772] = "minecraft:enderman_spawn_egg"
	itemNamesMap[773] = "minecraft:endermite_spawn_egg"
	itemNamesMap[774] = "minecraft:evoker_spawn_egg"
	itemNamesMap[775] = "minecraft:fox_spawn_egg"
	itemNamesMap[776] = "minecraft:ghast_spawn_egg"
	itemNamesMap[777] = "minecraft:guardian_spawn_egg"
	itemNamesMap[778] = "minecraft:hoglin_spawn_egg"
	itemNamesMap[779] = "minecraft:horse_spawn_egg"
	itemNamesMap[780] = "minecraft:husk_spawn_egg"
	itemNamesMap[781] = "minecraft:llama_spawn_egg"
	itemNamesMap[782] = "minecraft:magma_cube_spawn_egg"
	itemNamesMap[783] = "minecraft:mooshroom_spawn_egg"
	itemNamesMap[784] = "minecraft:mule_spawn_egg"
	itemNamesMap[785] = "minecraft:ocelot_spawn_egg"
	itemNamesMap[786] = "minecraft:panda_spawn_egg"
	itemNamesMap[787] = "minecraft:parrot_spawn_egg"
	itemNamesMap[788] = "minecraft:phantom_spawn_egg"
	itemNamesMap[789] = "minecraft:pig_spawn_egg"
	itemNamesMap[790] = "minecraft:piglin_spawn_egg"
	itemNamesMap[791] = "minecraft:piglin_brute_spawn_egg"
	itemNamesMap[792] = "minecraft:pillager_spawn_egg"
	itemNamesMap[793] = "minecraft:polar_bear_spawn_egg"
	itemNamesMap[794] = "minecraft:pufferfish_spawn_egg"
	itemNamesMap[795] = "minecraft:rabbit_spawn_egg"
	itemNamesMap[796] = "minecraft:ravager_spawn_egg"
	itemNamesMap[797] = "minecraft:salmon_spawn_egg"
	itemNamesMap[798] = "minecraft:sheep_spawn_egg"
	itemNamesMap[799] = "minecraft:shulker_spawn_egg"
	itemNamesMap[800] = "minecraft:silverfish_spawn_egg"
	itemNamesMap[801] = "minecraft:skeleton_spawn_egg"
	itemNamesMap[802] = "minecraft:skeleton_horse_spawn_egg"
	itemNamesMap[803] = "minecraft:slime_spawn_egg"
	itemNamesMap[804] = "minecraft:spider_spawn_egg"
	itemNamesMap[805] = "minecraft:squid_spawn_egg"
	itemNamesMap[806] = "minecraft:stray_spawn_egg"
	itemNamesMap[807] = "minecraft:strider_spawn_egg"
	itemNamesMap[808] = "minecraft:trader_llama_spawn_egg"
	itemNamesMap[809] = "minecraft:tropical_fish_spawn_egg"
	itemNamesMap[810] = "minecraft:turtle_spawn_egg"
	itemNamesMap[811] = "minecraft:vex_spawn_egg"
	itemNamesMap[812] = "minecraft:villager_spawn_egg"
	itemNamesMap[813] = "minecraft:vindicator_spawn_egg"
	itemNamesMap[814] = "minecraft:wandering_trader_spawn_egg"
	itemNamesMap[815] = "minecraft:witch_spawn_egg"
	itemNamesMap[816] = "minecraft:wither_skeleton_spawn_egg"
	itemNamesMap[817] = "minecraft:wolf_spawn_egg"
	itemNamesMap[818] = "minecraft:zoglin_spawn_egg"
	itemNamesMap[819] = "minecraft:zombie_spawn_egg"
	itemNamesMap[820] = "minecraft:zombie_horse_spawn_egg"
	itemNamesMap[821] = "minecraft:zombie_villager_spawn_egg"
	itemNamesMap[822] = "minecraft:zombified_piglin_spawn_egg"
	itemNamesMap[823] = "minecraft:experience_bottle"
	itemNamesMap[824] = "minecraft:fire_charge"
	itemNamesMap[825] = "minecraft:writable_book"
	itemNamesMap[826] = "minecraft:written_book"
	itemNamesMap[827] = "minecraft:emerald"
	itemNamesMap[828] = "minecraft:item_frame"
	itemNamesMap[829] = "minecraft:flower_pot"
	itemNamesMap[830] = "minecraft:carrot"
	itemNamesMap[831] = "minecraft:potato"
	itemNamesMap[832] = "minecraft:baked_potato"
	itemNamesMap[833] = "minecraft:poisonous_potato"
	itemNamesMap[834] = "minecraft:map"
	itemNamesMap[835] = "minecraft:golden_carrot"
	itemNamesMap[836] = "minecraft:skeleton_skull"
	itemNamesMap[837] = "minecraft:wither_skeleton_skull"
	itemNamesMap[838] = "minecraft:player_head"
	itemNamesMap[839] = "minecraft:zombie_head"
	itemNamesMap[840] = "minecraft:creeper_head"
	itemNamesMap[841] = "minecraft:dragon_head"
	itemNamesMap[842] = "minecraft:carrot_on_a_stick"
	itemNamesMap[843] = "minecraft:warped_fungus_on_a_stick"
	itemNamesMap[844] = "minecraft:nether_star"
	itemNamesMap[845] = "minecraft:pumpkin_pie"
	itemNamesMap[846] = "minecraft:firework_rocket"
	itemNamesMap[847] = "minecraft:firework_star"
	itemNamesMap[848] = "minecraft:enchanted_book"
	itemNamesMap[849] = "minecraft:nether_brick"
	itemNamesMap[850] = "minecraft:quartz"
	itemNamesMap[851] = "minecraft:tnt_minecart"
	itemNamesMap[852] = "minecraft:hopper_minecart"
	itemNamesMap[853] = "minecraft:prismarine_shard"
	itemNamesMap[854] = "minecraft:prismarine_crystals"
	itemNamesMap[855] = "minecraft:rabbit"
	itemNamesMap[856] = "minecraft:cooked_rabbit"
	itemNamesMap[857] = "minecraft:rabbit_stew"
	itemNamesMap[858] = "minecraft:rabbit_foot"
	itemNamesMap[859] = "minecraft:rabbit_hide"
	itemNamesMap[860] = "minecraft:armor_stand"
	itemNamesMap[861] = "minecraft:iron_horse_armor"
	itemNamesMap[862] = "minecraft:golden_horse_armor"
	itemNamesMap[863] = "minecraft:diamond_horse_armor"
	itemNamesMap[864] = "minecraft:leather_horse_armor"
	itemNamesMap[865] = "minecraft:lead"
	itemNamesMap[866] = "minecraft:name_tag"
	itemNamesMap[867] = "minecraft:command_block_minecart"
	itemNamesMap[868] = "minecraft:mutton"
	itemNamesMap[869] = "minecraft:cooked_mutton"
	itemNamesMap[870] = "minecraft:white_banner"
	itemNamesMap[871] = "minecraft:orange_banner"
	itemNamesMap[872] = "minecraft:magenta_banner"
	itemNamesMap[873] = "minecraft:light_blue_banner"
	itemNamesMap[874] = "minecraft:yellow_banner"
	itemNamesMap[875] = "minecraft:lime_banner"
	itemNamesMap[876] = "minecraft:pink_banner"
	itemNamesMap[877] = "minecraft:gray_banner"
	itemNamesMap[878] = "minecraft:light_gray_banner"
	itemNamesMap[879] = "minecraft:cyan_banner"
	itemNamesMap[880] = "minecraft:purple_banner"
	itemNamesMap[881] = "minecraft:blue_banner"
	itemNamesMap[882] = "minecraft:brown_banner"
	itemNamesMap[883] = "minecraft:green_banner"
	itemNamesMap[884] = "minecraft:red_banner"
	itemNamesMap[885] = "minecraft:black_banner"
	itemNamesMap[886] = "minecraft:end_crystal"
	itemNamesMap[887] = "minecraft:chorus_fruit"
	itemNamesMap[888] = "minecraft:popped_chorus_fruit"
	itemNamesMap[889] = "minecraft:beetroot"
	itemNamesMap[890] = "minecraft:beetroot_seeds"
	itemNamesMap[891] = "minecraft:beetroot_soup"
	itemNamesMap[892] = "minecraft:dragon_breath"
	itemNamesMap[893] = "minecraft:splash_potion"
	itemNamesMap[894] = "minecraft:spectral_arrow"
	itemNamesMap[895] = "minecraft:tipped_arrow"
	itemNamesMap[896] = "minecraft:lingering_potion"
	itemNamesMap[897] = "minecraft:shield"
	itemNamesMap[898] = "minecraft:elytra"
	itemNamesMap[899] = "minecraft:spruce_boat"
	itemNamesMap[900] = "minecraft:birch_boat"
	itemNamesMap[901] = "minecraft:jungle_boat"
	itemNamesMap[902] = "minecraft:acacia_boat"
	itemNamesMap[903] = "minecraft:dark_oak_boat"
	itemNamesMap[904] = "minecraft:totem_of_undying"
	itemNamesMap[905] = "minecraft:shulker_shell"
	itemNamesMap[906] = "minecraft:iron_nugget"
	itemNamesMap[907] = "minecraft:knowledge_book"
	itemNamesMap[908] = "minecraft:debug_stick"
	itemNamesMap[909] = "minecraft:music_disc_13"
	itemNamesMap[910] = "minecraft:music_disc_cat"
	itemNamesMap[911] = "minecraft:music_disc_blocks"
	itemNamesMap[912] = "minecraft:music_disc_chirp"
	itemNamesMap[913] = "minecraft:music_disc_far"
	itemNamesMap[914] = "minecraft:music_disc_mall"
	itemNamesMap[915] = "minecraft:music_disc_mellohi"
	itemNamesMap[916] = "minecraft:music_disc_stal"
	itemNamesMap[917] = "minecraft:music_disc_strad"
	itemNamesMap[918] = "minecraft:music_disc_ward"
	itemNamesMap[919] = "minecraft:music_disc_11"
	itemNamesMap[920] = "minecraft:music_disc_wait"
	itemNamesMap[921] = "minecraft:music_disc_pigstep"
	itemNamesMap[922] = "minecraft:trident"
	itemNamesMap[923] = "minecraft:phantom_membrane"
	itemNamesMap[924] = "minecraft:nautilus_shell"
	itemNamesMap[925] = "minecraft:heart_of_the_sea"
	itemNamesMap[926] = "minecraft:crossbow"
	itemNamesMap[927] = "minecraft:suspicious_stew"
	itemNamesMap[928] = "minecraft:loom"
	itemNamesMap[929] = "minecraft:flower_banner_pattern"
	itemNamesMap[930] = "minecraft:creeper_banner_pattern"
	itemNamesMap[931] = "minecraft:skull_banner_pattern"
	itemNamesMap[932] = "minecraft:mojang_banner_pattern"
	itemNamesMap[933] = "minecraft:globe_banner_pattern"
	itemNamesMap[934] = "minecraft:piglin_banner_pattern"
	itemNamesMap[935] = "minecraft:composter"
	itemNamesMap[936] = "minecraft:barrel"
	itemNamesMap[937] = "minecraft:smoker"
	itemNamesMap[938] = "minecraft:blast_furnace"
	itemNamesMap[939] = "minecraft:cartography_table"
	itemNamesMap[940] = "minecraft:fletching_table"
	itemNamesMap[941] = "minecraft:grindstone"
	itemNamesMap[942] = "minecraft:lectern"
	itemNamesMap[943] = "minecraft:smithing_table"
	itemNamesMap[944] = "minecraft:stonecutter"
	itemNamesMap[945] = "minecraft:bell"
	itemNamesMap[946] = "minecraft:lantern"
	itemNamesMap[947] = "minecraft:soul_lantern"
	itemNamesMap[948] = "minecraft:sweet_berries"
	itemNamesMap[949] = "minecraft:campfire"
	itemNamesMap[950] = "minecraft:soul_campfire"
	itemNamesMap[951] = "minecraft:shroomlight"
	itemNamesMap[952] = "minecraft:honeycomb"
	itemNamesMap[953] = "minecraft:bee_nest"
	itemNamesMap[954] = "minecraft:beehive"
	itemNamesMap[955] = "minecraft:honey_bottle"
	itemNamesMap[956] = "minecraft:honey_block"
	itemNamesMap[957] = "minecraft:honeycomb_block"
	itemNamesMap[958] = "minecraft:lodestone"
	itemNamesMap[959] = "minecraft:netherite_block"
	itemNamesMap[960] = "minecraft:ancient_debris"
	itemNamesMap[961] = "minecraft:target"
	itemNamesMap[962] = "minecraft:crying_obsidian"
	itemNamesMap[963] = "minecraft:blackstone"
	itemNamesMap[964] = "minecraft:blackstone_slab"
	itemNamesMap[965] = "minecraft:blackstone_stairs"
	itemNamesMap[966] = "minecraft:gilded_blackstone"
	itemNamesMap[967] = "minecraft:polished_blackstone"
	itemNamesMap[968] = "minecraft:polished_blackstone_slab"
	itemNamesMap[969] = "minecraft:polished_blackstone_stairs"
	itemNamesMap[970] = "minecraft:chiseled_polished_blackstone"
	itemNamesMap[971] = "minecraft:polished_blackstone_bricks"
	itemNamesMap[972] = "minecraft:polished_blackstone_brick_slab"
	itemNamesMap[973] = "minecraft:polished_blackstone_brick_stairs"
	itemNamesMap[974] = "minecraft:cracked_polished_blackstone_bricks"
	itemNamesMap[975] = "minecraft:respawn_anchor"

}
