// Code generated by "stringer -type=PacketType packets.go"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnspecified - -1]
	_ = x[SHandshake-4096]
	_ = x[SRequest-4352]
	_ = x[SPing-4353]
	_ = x[SLoginStart-4608]
	_ = x[SEncryptionResponse-4609]
	_ = x[SLoginPluginResponse-4610]
	_ = x[STeleportConfirm-4864]
	_ = x[SQueryBlockNBT-4865]
	_ = x[SSetDifficulty-4866]
	_ = x[SChatMessage-4867]
	_ = x[SClientStatus-4868]
	_ = x[SClientSettings-4869]
	_ = x[SPluginMessage-4875]
	_ = x[SKeepAlive-4879]
	_ = x[SPlayerPosition-4881]
	_ = x[SPlayerLocation-4882]
	_ = x[SPlayerRotation-4883]
	_ = x[SPlayerAbilities-4889]
	_ = x[CResponse-61696]
	_ = x[CPong-61697]
	_ = x[CDisconnect-61952]
	_ = x[CEncryptionRequest-61953]
	_ = x[CLoginSuccess-61954]
	_ = x[CSetCompression-61955]
	_ = x[CLoginPluginRequest-61956]
	_ = x[CChatMessage-62223]
	_ = x[CJoinGame-62246]
	_ = x[CPluginMessage-62233]
	_ = x[CPlayerLocation-62262]
	_ = x[CKeepAlive-62241]
	_ = x[CServerDifficulty-62222]
	_ = x[CPlayerAbilities-62258]
	_ = x[CHeldItemChange-62272]
	_ = x[CDeclareRecipes-62299]
	_ = x[CChunkData-62242]
	_ = x[CPlayerInfo-62260]
	_ = x[CEntityMetadata-62276]
}

const _PacketType_name = "TypeUnspecifiedSHandshakeSRequestSPingSLoginStartSEncryptionResponseSLoginPluginResponseSTeleportConfirmSQueryBlockNBTSSetDifficultySChatMessageSClientStatusSClientSettingsSPluginMessageSKeepAliveSPlayerPositionSPlayerLocationSPlayerRotationSPlayerAbilitiesCResponseCPongCDisconnectCEncryptionRequestCLoginSuccessCSetCompressionCLoginPluginRequestCServerDifficultyCChatMessageCPluginMessageCKeepAliveCChunkDataCJoinGameCPlayerAbilitiesCPlayerInfoCPlayerLocationCHeldItemChangeCEntityMetadataCDeclareRecipes"

var _PacketType_map = map[PacketType]string{
	-1:    _PacketType_name[0:15],
	4096:  _PacketType_name[15:25],
	4352:  _PacketType_name[25:33],
	4353:  _PacketType_name[33:38],
	4608:  _PacketType_name[38:49],
	4609:  _PacketType_name[49:68],
	4610:  _PacketType_name[68:88],
	4864:  _PacketType_name[88:104],
	4865:  _PacketType_name[104:118],
	4866:  _PacketType_name[118:132],
	4867:  _PacketType_name[132:144],
	4868:  _PacketType_name[144:157],
	4869:  _PacketType_name[157:172],
	4875:  _PacketType_name[172:186],
	4879:  _PacketType_name[186:196],
	4881:  _PacketType_name[196:211],
	4882:  _PacketType_name[211:226],
	4883:  _PacketType_name[226:241],
	4889:  _PacketType_name[241:257],
	61696: _PacketType_name[257:266],
	61697: _PacketType_name[266:271],
	61952: _PacketType_name[271:282],
	61953: _PacketType_name[282:300],
	61954: _PacketType_name[300:313],
	61955: _PacketType_name[313:328],
	61956: _PacketType_name[328:347],
	62222: _PacketType_name[347:364],
	62223: _PacketType_name[364:376],
	62233: _PacketType_name[376:390],
	62241: _PacketType_name[390:400],
	62242: _PacketType_name[400:410],
	62246: _PacketType_name[410:419],
	62258: _PacketType_name[419:435],
	62260: _PacketType_name[435:446],
	62262: _PacketType_name[446:461],
	62272: _PacketType_name[461:476],
	62276: _PacketType_name[476:491],
	62299: _PacketType_name[491:506],
}

func (i PacketType) String() string {
	if str, ok := _PacketType_map[i]; ok {
		return str
	}
	return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
}
