// Code generated by "stringer -type=PacketType packets.go"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SHandshake-4096]
	_ = x[SRequest-4352]
	_ = x[SPing-4353]
	_ = x[SLoginStart-4608]
	_ = x[SEncryptionResponse-4609]
	_ = x[SLoginPluginResponse-4610]
	_ = x[STeleportConfirm-4864]
	_ = x[SQueryBlockNBT-4865]
	_ = x[SSetDifficulty-4866]
	_ = x[SChatMessage-4867]
	_ = x[SClientStatus-4868]
	_ = x[SClientSettings-4869]
	_ = x[SPluginMessage-4875]
	_ = x[SKeepAlive-4879]
	_ = x[SPlayerPosition-4881]
	_ = x[SPlayerLocation-4882]
	_ = x[SPlayerRotation-4883]
	_ = x[SPlayerAbilities-4889]
	_ = x[CResponse-61696]
	_ = x[CPong-61697]
	_ = x[CDisconnect-61952]
	_ = x[CEncryptionRequest-61953]
	_ = x[CLoginSuccess-61954]
	_ = x[CSetCompression-61955]
	_ = x[CLoginPluginRequest-61956]
	_ = x[CChatMessage-62223]
	_ = x[CJoinGame-62246]
	_ = x[CPluginMessage-62233]
	_ = x[CPlayerLocation-62262]
	_ = x[CKeepAlive-62241]
	_ = x[CServerDifficulty-62222]
	_ = x[CPlayerAbilities-62258]
	_ = x[CHeldItemChange-62272]
	_ = x[CDeclareRecipes-62299]
	_ = x[CChunkData-62242]
	_ = x[CPlayerInfo-62260]
	_ = x[CEntityMetadata-62276]
}

const _PacketType_name = "SHandshakeSRequestSPingSLoginStartSEncryptionResponseSLoginPluginResponseSTeleportConfirmSQueryBlockNBTSSetDifficultySChatMessageSClientStatusSClientSettingsSPluginMessageSKeepAliveSPlayerPositionSPlayerLocationSPlayerRotationSPlayerAbilitiesCResponseCPongCDisconnectCEncryptionRequestCLoginSuccessCSetCompressionCLoginPluginRequestCServerDifficultyCChatMessageCPluginMessageCKeepAliveCChunkDataCJoinGameCPlayerAbilitiesCPlayerInfoCPlayerLocationCHeldItemChangeCEntityMetadataCDeclareRecipes"

var _PacketType_map = map[PacketType]string{
	4096:  _PacketType_name[0:10],
	4352:  _PacketType_name[10:18],
	4353:  _PacketType_name[18:23],
	4608:  _PacketType_name[23:34],
	4609:  _PacketType_name[34:53],
	4610:  _PacketType_name[53:73],
	4864:  _PacketType_name[73:89],
	4865:  _PacketType_name[89:103],
	4866:  _PacketType_name[103:117],
	4867:  _PacketType_name[117:129],
	4868:  _PacketType_name[129:142],
	4869:  _PacketType_name[142:157],
	4875:  _PacketType_name[157:171],
	4879:  _PacketType_name[171:181],
	4881:  _PacketType_name[181:196],
	4882:  _PacketType_name[196:211],
	4883:  _PacketType_name[211:226],
	4889:  _PacketType_name[226:242],
	61696: _PacketType_name[242:251],
	61697: _PacketType_name[251:256],
	61952: _PacketType_name[256:267],
	61953: _PacketType_name[267:285],
	61954: _PacketType_name[285:298],
	61955: _PacketType_name[298:313],
	61956: _PacketType_name[313:332],
	62222: _PacketType_name[332:349],
	62223: _PacketType_name[349:361],
	62233: _PacketType_name[361:375],
	62241: _PacketType_name[375:385],
	62242: _PacketType_name[385:395],
	62246: _PacketType_name[395:404],
	62258: _PacketType_name[404:420],
	62260: _PacketType_name[420:431],
	62262: _PacketType_name[431:446],
	62272: _PacketType_name[446:461],
	62276: _PacketType_name[461:476],
	62299: _PacketType_name[476:491],
}

func (i PacketType) String() string {
	if str, ok := _PacketType_map[i]; ok {
		return str
	}
	return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
}
