// Code generated by protoc-gen-oneofmapper. DO NOT EDIT.
// source: envelope.proto

package pb

type OneOfMessage string

const (
	Message_Cpacket         OneOfMessage = "Cpacket"
	Message_Spacket         OneOfMessage = "Spacket"
	Message_CloseConn       OneOfMessage = "CloseConn"
	Message_PlayerLoading   OneOfMessage = "PlayerLoading"
	Message_NewPlayer       OneOfMessage = "NewPlayer"
	Message_PlayerJoined    OneOfMessage = "PlayerJoined"
	Message_PlayerLeft      OneOfMessage = "PlayerLeft"
	Message_PlayerSpatial   OneOfMessage = "PlayerSpatial"
	Message_PlayerInventory OneOfMessage = "PlayerInventory"
)
