// Code generated by "stringer -type=Difficulty settings.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Peaceful-0]
	_ = x[Easy-1]
	_ = x[Normal-2]
	_ = x[Hard-3]
}

const _Difficulty_name = "PeacefulEasyNormalHard"

var _Difficulty_index = [...]uint8{0, 8, 12, 18, 22}

func (i Difficulty) String() string {
	if i >= Difficulty(len(_Difficulty_index)-1) {
		return "Difficulty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Difficulty_name[_Difficulty_index[i]:_Difficulty_index[i+1]]
}
