package items

type ItemID uint32

func (b ItemID) String() string { return namesMap[b] }
func (b ItemID) ID() uint32     { return uint32(b) }

const (
	Air                             ItemID = 0
	Stone                           ItemID = 1
	Granite                         ItemID = 2
	PolishedGranite                 ItemID = 3
	Diorite                         ItemID = 4
	PolishedDiorite                 ItemID = 5
	Andesite                        ItemID = 6
	PolishedAndesite                ItemID = 7
	GrassBlock                      ItemID = 8
	Dirt                            ItemID = 9
	CoarseDirt                      ItemID = 10
	Podzol                          ItemID = 11
	CrimsonNylium                   ItemID = 12
	WarpedNylium                    ItemID = 13
	Cobblestone                     ItemID = 14
	OakPlanks                       ItemID = 15
	SprucePlanks                    ItemID = 16
	BirchPlanks                     ItemID = 17
	JunglePlanks                    ItemID = 18
	AcaciaPlanks                    ItemID = 19
	DarkOakPlanks                   ItemID = 20
	CrimsonPlanks                   ItemID = 21
	WarpedPlanks                    ItemID = 22
	OakSapling                      ItemID = 23
	SpruceSapling                   ItemID = 24
	BirchSapling                    ItemID = 25
	JungleSapling                   ItemID = 26
	AcaciaSapling                   ItemID = 27
	DarkOakSapling                  ItemID = 28
	Bedrock                         ItemID = 29
	Sand                            ItemID = 30
	RedSand                         ItemID = 31
	Gravel                          ItemID = 32
	GoldOre                         ItemID = 33
	IronOre                         ItemID = 34
	CoalOre                         ItemID = 35
	NetherGoldOre                   ItemID = 36
	OakLog                          ItemID = 37
	SpruceLog                       ItemID = 38
	BirchLog                        ItemID = 39
	JungleLog                       ItemID = 40
	AcaciaLog                       ItemID = 41
	DarkOakLog                      ItemID = 42
	CrimsonStem                     ItemID = 43
	WarpedStem                      ItemID = 44
	StrippedOakLog                  ItemID = 45
	StrippedSpruceLog               ItemID = 46
	StrippedBirchLog                ItemID = 47
	StrippedJungleLog               ItemID = 48
	StrippedAcaciaLog               ItemID = 49
	StrippedDarkOakLog              ItemID = 50
	StrippedCrimsonStem             ItemID = 51
	StrippedWarpedStem              ItemID = 52
	StrippedOakWood                 ItemID = 53
	StrippedSpruceWood              ItemID = 54
	StrippedBirchWood               ItemID = 55
	StrippedJungleWood              ItemID = 56
	StrippedAcaciaWood              ItemID = 57
	StrippedDarkOakWood             ItemID = 58
	StrippedCrimsonHyphae           ItemID = 59
	StrippedWarpedHyphae            ItemID = 60
	OakWood                         ItemID = 61
	SpruceWood                      ItemID = 62
	BirchWood                       ItemID = 63
	JungleWood                      ItemID = 64
	AcaciaWood                      ItemID = 65
	DarkOakWood                     ItemID = 66
	CrimsonHyphae                   ItemID = 67
	WarpedHyphae                    ItemID = 68
	OakLeaves                       ItemID = 69
	SpruceLeaves                    ItemID = 70
	BirchLeaves                     ItemID = 71
	JungleLeaves                    ItemID = 72
	AcaciaLeaves                    ItemID = 73
	DarkOakLeaves                   ItemID = 74
	Sponge                          ItemID = 75
	WetSponge                       ItemID = 76
	Glass                           ItemID = 77
	LapisOre                        ItemID = 78
	LapisBlock                      ItemID = 79
	Dispenser                       ItemID = 80
	Sandstone                       ItemID = 81
	ChiseledSandstone               ItemID = 82
	CutSandstone                    ItemID = 83
	NoteBlock                       ItemID = 84
	PoweredRail                     ItemID = 85
	DetectorRail                    ItemID = 86
	StickyPiston                    ItemID = 87
	Cobweb                          ItemID = 88
	Grass                           ItemID = 89
	Fern                            ItemID = 90
	DeadBush                        ItemID = 91
	Seagrass                        ItemID = 92
	SeaPickle                       ItemID = 93
	Piston                          ItemID = 94
	WhiteWool                       ItemID = 95
	OrangeWool                      ItemID = 96
	MagentaWool                     ItemID = 97
	LightBlueWool                   ItemID = 98
	YellowWool                      ItemID = 99
	LimeWool                        ItemID = 100
	PinkWool                        ItemID = 101
	GrayWool                        ItemID = 102
	LightGrayWool                   ItemID = 103
	CyanWool                        ItemID = 104
	PurpleWool                      ItemID = 105
	BlueWool                        ItemID = 106
	BrownWool                       ItemID = 107
	GreenWool                       ItemID = 108
	RedWool                         ItemID = 109
	BlackWool                       ItemID = 110
	Dandelion                       ItemID = 111
	Poppy                           ItemID = 112
	BlueOrchid                      ItemID = 113
	Allium                          ItemID = 114
	AzureBluet                      ItemID = 115
	RedTulip                        ItemID = 116
	OrangeTulip                     ItemID = 117
	WhiteTulip                      ItemID = 118
	PinkTulip                       ItemID = 119
	OxeyeDaisy                      ItemID = 120
	Cornflower                      ItemID = 121
	LilyOfTheValley                 ItemID = 122
	WitherRose                      ItemID = 123
	BrownMushroom                   ItemID = 124
	RedMushroom                     ItemID = 125
	CrimsonFungus                   ItemID = 126
	WarpedFungus                    ItemID = 127
	CrimsonRoots                    ItemID = 128
	WarpedRoots                     ItemID = 129
	NetherSprouts                   ItemID = 130
	WeepingVines                    ItemID = 131
	TwistingVines                   ItemID = 132
	SugarCane                       ItemID = 133
	Kelp                            ItemID = 134
	Bamboo                          ItemID = 135
	GoldBlock                       ItemID = 136
	IronBlock                       ItemID = 137
	OakSlab                         ItemID = 138
	SpruceSlab                      ItemID = 139
	BirchSlab                       ItemID = 140
	JungleSlab                      ItemID = 141
	AcaciaSlab                      ItemID = 142
	DarkOakSlab                     ItemID = 143
	CrimsonSlab                     ItemID = 144
	WarpedSlab                      ItemID = 145
	StoneSlab                       ItemID = 146
	SmoothStoneSlab                 ItemID = 147
	SandstoneSlab                   ItemID = 148
	CutSandstoneSlab                ItemID = 149
	PetrifiedOakSlab                ItemID = 150
	CobblestoneSlab                 ItemID = 151
	BrickSlab                       ItemID = 152
	StoneBrickSlab                  ItemID = 153
	NetherBrickSlab                 ItemID = 154
	QuartzSlab                      ItemID = 155
	RedSandstoneSlab                ItemID = 156
	CutRedSandstoneSlab             ItemID = 157
	PurpurSlab                      ItemID = 158
	PrismarineSlab                  ItemID = 159
	PrismarineBrickSlab             ItemID = 160
	DarkPrismarineSlab              ItemID = 161
	SmoothQuartz                    ItemID = 162
	SmoothRedSandstone              ItemID = 163
	SmoothSandstone                 ItemID = 164
	SmoothStone                     ItemID = 165
	Bricks                          ItemID = 166
	Tnt                             ItemID = 167
	Bookshelf                       ItemID = 168
	MossyCobblestone                ItemID = 169
	Obsidian                        ItemID = 170
	Torch                           ItemID = 171
	EndRod                          ItemID = 172
	ChorusPlant                     ItemID = 173
	ChorusFlower                    ItemID = 174
	PurpurBlock                     ItemID = 175
	PurpurPillar                    ItemID = 176
	PurpurStairs                    ItemID = 177
	Spawner                         ItemID = 178
	OakStairs                       ItemID = 179
	Chest                           ItemID = 180
	DiamondOre                      ItemID = 181
	DiamondBlock                    ItemID = 182
	CraftingTable                   ItemID = 183
	Farmland                        ItemID = 184
	Furnace                         ItemID = 185
	Ladder                          ItemID = 186
	Rail                            ItemID = 187
	CobblestoneStairs               ItemID = 188
	Lever                           ItemID = 189
	StonePressurePlate              ItemID = 190
	OakPressurePlate                ItemID = 191
	SprucePressurePlate             ItemID = 192
	BirchPressurePlate              ItemID = 193
	JunglePressurePlate             ItemID = 194
	AcaciaPressurePlate             ItemID = 195
	DarkOakPressurePlate            ItemID = 196
	CrimsonPressurePlate            ItemID = 197
	WarpedPressurePlate             ItemID = 198
	PolishedBlackstonePressurePlate ItemID = 199
	RedstoneOre                     ItemID = 200
	RedstoneTorch                   ItemID = 201
	Snow                            ItemID = 202
	Ice                             ItemID = 203
	SnowBlock                       ItemID = 204
	Cactus                          ItemID = 205
	Clay                            ItemID = 206
	Jukebox                         ItemID = 207
	OakFence                        ItemID = 208
	SpruceFence                     ItemID = 209
	BirchFence                      ItemID = 210
	JungleFence                     ItemID = 211
	AcaciaFence                     ItemID = 212
	DarkOakFence                    ItemID = 213
	CrimsonFence                    ItemID = 214
	WarpedFence                     ItemID = 215
	Pumpkin                         ItemID = 216
	CarvedPumpkin                   ItemID = 217
	Netherrack                      ItemID = 218
	SoulSand                        ItemID = 219
	SoulSoil                        ItemID = 220
	Basalt                          ItemID = 221
	PolishedBasalt                  ItemID = 222
	SoulTorch                       ItemID = 223
	Glowstone                       ItemID = 224
	JackOLantern                    ItemID = 225
	OakTrapdoor                     ItemID = 226
	SpruceTrapdoor                  ItemID = 227
	BirchTrapdoor                   ItemID = 228
	JungleTrapdoor                  ItemID = 229
	AcaciaTrapdoor                  ItemID = 230
	DarkOakTrapdoor                 ItemID = 231
	CrimsonTrapdoor                 ItemID = 232
	WarpedTrapdoor                  ItemID = 233
	InfestedStone                   ItemID = 234
	InfestedCobblestone             ItemID = 235
	InfestedStoneBricks             ItemID = 236
	InfestedMossyStoneBricks        ItemID = 237
	InfestedCrackedStoneBricks      ItemID = 238
	InfestedChiseledStoneBricks     ItemID = 239
	StoneBricks                     ItemID = 240
	MossyStoneBricks                ItemID = 241
	CrackedStoneBricks              ItemID = 242
	ChiseledStoneBricks             ItemID = 243
	BrownMushroomBlock              ItemID = 244
	RedMushroomBlock                ItemID = 245
	MushroomStem                    ItemID = 246
	IronBars                        ItemID = 247
	Chain                           ItemID = 248
	GlassPane                       ItemID = 249
	Melon                           ItemID = 250
	Vine                            ItemID = 251
	OakFenceGate                    ItemID = 252
	SpruceFenceGate                 ItemID = 253
	BirchFenceGate                  ItemID = 254
	JungleFenceGate                 ItemID = 255
	AcaciaFenceGate                 ItemID = 256
	DarkOakFenceGate                ItemID = 257
	CrimsonFenceGate                ItemID = 258
	WarpedFenceGate                 ItemID = 259
	BrickStairs                     ItemID = 260
	StoneBrickStairs                ItemID = 261
	Mycelium                        ItemID = 262
	LilyPad                         ItemID = 263
	NetherBricks                    ItemID = 264
	CrackedNetherBricks             ItemID = 265
	ChiseledNetherBricks            ItemID = 266
	NetherBrickFence                ItemID = 267
	NetherBrickStairs               ItemID = 268
	EnchantingTable                 ItemID = 269
	EndPortalFrame                  ItemID = 270
	EndStone                        ItemID = 271
	EndStoneBricks                  ItemID = 272
	DragonEgg                       ItemID = 273
	RedstoneLamp                    ItemID = 274
	SandstoneStairs                 ItemID = 275
	EmeraldOre                      ItemID = 276
	EnderChest                      ItemID = 277
	TripwireHook                    ItemID = 278
	EmeraldBlock                    ItemID = 279
	SpruceStairs                    ItemID = 280
	BirchStairs                     ItemID = 281
	JungleStairs                    ItemID = 282
	CrimsonStairs                   ItemID = 283
	WarpedStairs                    ItemID = 284
	CommandBlock                    ItemID = 285
	Beacon                          ItemID = 286
	CobblestoneWall                 ItemID = 287
	MossyCobblestoneWall            ItemID = 288
	BrickWall                       ItemID = 289
	PrismarineWall                  ItemID = 290
	RedSandstoneWall                ItemID = 291
	MossyStoneBrickWall             ItemID = 292
	GraniteWall                     ItemID = 293
	StoneBrickWall                  ItemID = 294
	NetherBrickWall                 ItemID = 295
	AndesiteWall                    ItemID = 296
	RedNetherBrickWall              ItemID = 297
	SandstoneWall                   ItemID = 298
	EndStoneBrickWall               ItemID = 299
	DioriteWall                     ItemID = 300
	BlackstoneWall                  ItemID = 301
	PolishedBlackstoneWall          ItemID = 302
	PolishedBlackstoneBrickWall     ItemID = 303
	StoneButton                     ItemID = 304
	OakButton                       ItemID = 305
	SpruceButton                    ItemID = 306
	BirchButton                     ItemID = 307
	JungleButton                    ItemID = 308
	AcaciaButton                    ItemID = 309
	DarkOakButton                   ItemID = 310
	CrimsonButton                   ItemID = 311
	WarpedButton                    ItemID = 312
	PolishedBlackstoneButton        ItemID = 313
	Anvil                           ItemID = 314
	ChippedAnvil                    ItemID = 315
	DamagedAnvil                    ItemID = 316
	TrappedChest                    ItemID = 317
	LightWeightedPressurePlate      ItemID = 318
	HeavyWeightedPressurePlate      ItemID = 319
	DaylightDetector                ItemID = 320
	RedstoneBlock                   ItemID = 321
	NetherQuartzOre                 ItemID = 322
	Hopper                          ItemID = 323
	ChiseledQuartzBlock             ItemID = 324
	QuartzBlock                     ItemID = 325
	QuartzBricks                    ItemID = 326
	QuartzPillar                    ItemID = 327
	QuartzStairs                    ItemID = 328
	ActivatorRail                   ItemID = 329
	Dropper                         ItemID = 330
	WhiteTerracotta                 ItemID = 331
	OrangeTerracotta                ItemID = 332
	MagentaTerracotta               ItemID = 333
	LightBlueTerracotta             ItemID = 334
	YellowTerracotta                ItemID = 335
	LimeTerracotta                  ItemID = 336
	PinkTerracotta                  ItemID = 337
	GrayTerracotta                  ItemID = 338
	LightGrayTerracotta             ItemID = 339
	CyanTerracotta                  ItemID = 340
	PurpleTerracotta                ItemID = 341
	BlueTerracotta                  ItemID = 342
	BrownTerracotta                 ItemID = 343
	GreenTerracotta                 ItemID = 344
	RedTerracotta                   ItemID = 345
	BlackTerracotta                 ItemID = 346
	Barrier                         ItemID = 347
	IronTrapdoor                    ItemID = 348
	HayBlock                        ItemID = 349
	WhiteCarpet                     ItemID = 350
	OrangeCarpet                    ItemID = 351
	MagentaCarpet                   ItemID = 352
	LightBlueCarpet                 ItemID = 353
	YellowCarpet                    ItemID = 354
	LimeCarpet                      ItemID = 355
	PinkCarpet                      ItemID = 356
	GrayCarpet                      ItemID = 357
	LightGrayCarpet                 ItemID = 358
	CyanCarpet                      ItemID = 359
	PurpleCarpet                    ItemID = 360
	BlueCarpet                      ItemID = 361
	BrownCarpet                     ItemID = 362
	GreenCarpet                     ItemID = 363
	RedCarpet                       ItemID = 364
	BlackCarpet                     ItemID = 365
	Terracotta                      ItemID = 366
	CoalBlock                       ItemID = 367
	PackedIce                       ItemID = 368
	AcaciaStairs                    ItemID = 369
	DarkOakStairs                   ItemID = 370
	SlimeBlock                      ItemID = 371
	GrassPath                       ItemID = 372
	Sunflower                       ItemID = 373
	Lilac                           ItemID = 374
	RoseBush                        ItemID = 375
	Peony                           ItemID = 376
	TallGrass                       ItemID = 377
	LargeFern                       ItemID = 378
	WhiteStainedGlass               ItemID = 379
	OrangeStainedGlass              ItemID = 380
	MagentaStainedGlass             ItemID = 381
	LightBlueStainedGlass           ItemID = 382
	YellowStainedGlass              ItemID = 383
	LimeStainedGlass                ItemID = 384
	PinkStainedGlass                ItemID = 385
	GrayStainedGlass                ItemID = 386
	LightGrayStainedGlass           ItemID = 387
	CyanStainedGlass                ItemID = 388
	PurpleStainedGlass              ItemID = 389
	BlueStainedGlass                ItemID = 390
	BrownStainedGlass               ItemID = 391
	GreenStainedGlass               ItemID = 392
	RedStainedGlass                 ItemID = 393
	BlackStainedGlass               ItemID = 394
	WhiteStainedGlassPane           ItemID = 395
	OrangeStainedGlassPane          ItemID = 396
	MagentaStainedGlassPane         ItemID = 397
	LightBlueStainedGlassPane       ItemID = 398
	YellowStainedGlassPane          ItemID = 399
	LimeStainedGlassPane            ItemID = 400
	PinkStainedGlassPane            ItemID = 401
	GrayStainedGlassPane            ItemID = 402
	LightGrayStainedGlassPane       ItemID = 403
	CyanStainedGlassPane            ItemID = 404
	PurpleStainedGlassPane          ItemID = 405
	BlueStainedGlassPane            ItemID = 406
	BrownStainedGlassPane           ItemID = 407
	GreenStainedGlassPane           ItemID = 408
	RedStainedGlassPane             ItemID = 409
	BlackStainedGlassPane           ItemID = 410
	Prismarine                      ItemID = 411
	PrismarineBricks                ItemID = 412
	DarkPrismarine                  ItemID = 413
	PrismarineStairs                ItemID = 414
	PrismarineBrickStairs           ItemID = 415
	DarkPrismarineStairs            ItemID = 416
	SeaLantern                      ItemID = 417
	RedSandstone                    ItemID = 418
	ChiseledRedSandstone            ItemID = 419
	CutRedSandstone                 ItemID = 420
	RedSandstoneStairs              ItemID = 421
	RepeatingCommandBlock           ItemID = 422
	ChainCommandBlock               ItemID = 423
	MagmaBlock                      ItemID = 424
	NetherWartBlock                 ItemID = 425
	WarpedWartBlock                 ItemID = 426
	RedNetherBricks                 ItemID = 427
	BoneBlock                       ItemID = 428
	StructureVoid                   ItemID = 429
	Observer                        ItemID = 430
	ShulkerBox                      ItemID = 431
	WhiteShulkerBox                 ItemID = 432
	OrangeShulkerBox                ItemID = 433
	MagentaShulkerBox               ItemID = 434
	LightBlueShulkerBox             ItemID = 435
	YellowShulkerBox                ItemID = 436
	LimeShulkerBox                  ItemID = 437
	PinkShulkerBox                  ItemID = 438
	GrayShulkerBox                  ItemID = 439
	LightGrayShulkerBox             ItemID = 440
	CyanShulkerBox                  ItemID = 441
	PurpleShulkerBox                ItemID = 442
	BlueShulkerBox                  ItemID = 443
	BrownShulkerBox                 ItemID = 444
	GreenShulkerBox                 ItemID = 445
	RedShulkerBox                   ItemID = 446
	BlackShulkerBox                 ItemID = 447
	WhiteGlazedTerracotta           ItemID = 448
	OrangeGlazedTerracotta          ItemID = 449
	MagentaGlazedTerracotta         ItemID = 450
	LightBlueGlazedTerracotta       ItemID = 451
	YellowGlazedTerracotta          ItemID = 452
	LimeGlazedTerracotta            ItemID = 453
	PinkGlazedTerracotta            ItemID = 454
	GrayGlazedTerracotta            ItemID = 455
	LightGrayGlazedTerracotta       ItemID = 456
	CyanGlazedTerracotta            ItemID = 457
	PurpleGlazedTerracotta          ItemID = 458
	BlueGlazedTerracotta            ItemID = 459
	BrownGlazedTerracotta           ItemID = 460
	GreenGlazedTerracotta           ItemID = 461
	RedGlazedTerracotta             ItemID = 462
	BlackGlazedTerracotta           ItemID = 463
	WhiteConcrete                   ItemID = 464
	OrangeConcrete                  ItemID = 465
	MagentaConcrete                 ItemID = 466
	LightBlueConcrete               ItemID = 467
	YellowConcrete                  ItemID = 468
	LimeConcrete                    ItemID = 469
	PinkConcrete                    ItemID = 470
	GrayConcrete                    ItemID = 471
	LightGrayConcrete               ItemID = 472
	CyanConcrete                    ItemID = 473
	PurpleConcrete                  ItemID = 474
	BlueConcrete                    ItemID = 475
	BrownConcrete                   ItemID = 476
	GreenConcrete                   ItemID = 477
	RedConcrete                     ItemID = 478
	BlackConcrete                   ItemID = 479
	WhiteConcretePowder             ItemID = 480
	OrangeConcretePowder            ItemID = 481
	MagentaConcretePowder           ItemID = 482
	LightBlueConcretePowder         ItemID = 483
	YellowConcretePowder            ItemID = 484
	LimeConcretePowder              ItemID = 485
	PinkConcretePowder              ItemID = 486
	GrayConcretePowder              ItemID = 487
	LightGrayConcretePowder         ItemID = 488
	CyanConcretePowder              ItemID = 489
	PurpleConcretePowder            ItemID = 490
	BlueConcretePowder              ItemID = 491
	BrownConcretePowder             ItemID = 492
	GreenConcretePowder             ItemID = 493
	RedConcretePowder               ItemID = 494
	BlackConcretePowder             ItemID = 495
	TurtleEgg                       ItemID = 496
	DeadTubeCoralBlock              ItemID = 497
	DeadBrainCoralBlock             ItemID = 498
	DeadBubbleCoralBlock            ItemID = 499
	DeadFireCoralBlock              ItemID = 500
	DeadHornCoralBlock              ItemID = 501
	TubeCoralBlock                  ItemID = 502
	BrainCoralBlock                 ItemID = 503
	BubbleCoralBlock                ItemID = 504
	FireCoralBlock                  ItemID = 505
	HornCoralBlock                  ItemID = 506
	TubeCoral                       ItemID = 507
	BrainCoral                      ItemID = 508
	BubbleCoral                     ItemID = 509
	FireCoral                       ItemID = 510
	HornCoral                       ItemID = 511
	DeadBrainCoral                  ItemID = 512
	DeadBubbleCoral                 ItemID = 513
	DeadFireCoral                   ItemID = 514
	DeadHornCoral                   ItemID = 515
	DeadTubeCoral                   ItemID = 516
	TubeCoralFan                    ItemID = 517
	BrainCoralFan                   ItemID = 518
	BubbleCoralFan                  ItemID = 519
	FireCoralFan                    ItemID = 520
	HornCoralFan                    ItemID = 521
	DeadTubeCoralFan                ItemID = 522
	DeadBrainCoralFan               ItemID = 523
	DeadBubbleCoralFan              ItemID = 524
	DeadFireCoralFan                ItemID = 525
	DeadHornCoralFan                ItemID = 526
	BlueIce                         ItemID = 527
	Conduit                         ItemID = 528
	PolishedGraniteStairs           ItemID = 529
	SmoothRedSandstoneStairs        ItemID = 530
	MossyStoneBrickStairs           ItemID = 531
	PolishedDioriteStairs           ItemID = 532
	MossyCobblestoneStairs          ItemID = 533
	EndStoneBrickStairs             ItemID = 534
	StoneStairs                     ItemID = 535
	SmoothSandstoneStairs           ItemID = 536
	SmoothQuartzStairs              ItemID = 537
	GraniteStairs                   ItemID = 538
	AndesiteStairs                  ItemID = 539
	RedNetherBrickStairs            ItemID = 540
	PolishedAndesiteStairs          ItemID = 541
	DioriteStairs                   ItemID = 542
	PolishedGraniteSlab             ItemID = 543
	SmoothRedSandstoneSlab          ItemID = 544
	MossyStoneBrickSlab             ItemID = 545
	PolishedDioriteSlab             ItemID = 546
	MossyCobblestoneSlab            ItemID = 547
	EndStoneBrickSlab               ItemID = 548
	SmoothSandstoneSlab             ItemID = 549
	SmoothQuartzSlab                ItemID = 550
	GraniteSlab                     ItemID = 551
	AndesiteSlab                    ItemID = 552
	RedNetherBrickSlab              ItemID = 553
	PolishedAndesiteSlab            ItemID = 554
	DioriteSlab                     ItemID = 555
	Scaffolding                     ItemID = 556
	IronDoor                        ItemID = 557
	OakDoor                         ItemID = 558
	SpruceDoor                      ItemID = 559
	BirchDoor                       ItemID = 560
	JungleDoor                      ItemID = 561
	AcaciaDoor                      ItemID = 562
	DarkOakDoor                     ItemID = 563
	CrimsonDoor                     ItemID = 564
	WarpedDoor                      ItemID = 565
	Repeater                        ItemID = 566
	Comparator                      ItemID = 567
	StructureBlock                  ItemID = 568
	Jigsaw                          ItemID = 569
	TurtleHelmet                    ItemID = 570
	Scute                           ItemID = 571
	FlintAndSteel                   ItemID = 572
	Apple                           ItemID = 573
	Bow                             ItemID = 574
	Arrow                           ItemID = 575
	Coal                            ItemID = 576
	Charcoal                        ItemID = 577
	Diamond                         ItemID = 578
	IronIngot                       ItemID = 579
	GoldIngot                       ItemID = 580
	NetheriteIngot                  ItemID = 581
	NetheriteScrap                  ItemID = 582
	WoodenSword                     ItemID = 583
	WoodenShovel                    ItemID = 584
	WoodenPickaxe                   ItemID = 585
	WoodenAxe                       ItemID = 586
	WoodenHoe                       ItemID = 587
	StoneSword                      ItemID = 588
	StoneShovel                     ItemID = 589
	StonePickaxe                    ItemID = 590
	StoneAxe                        ItemID = 591
	StoneHoe                        ItemID = 592
	GoldenSword                     ItemID = 593
	GoldenShovel                    ItemID = 594
	GoldenPickaxe                   ItemID = 595
	GoldenAxe                       ItemID = 596
	GoldenHoe                       ItemID = 597
	IronSword                       ItemID = 598
	IronShovel                      ItemID = 599
	IronPickaxe                     ItemID = 600
	IronAxe                         ItemID = 601
	IronHoe                         ItemID = 602
	DiamondSword                    ItemID = 603
	DiamondShovel                   ItemID = 604
	DiamondPickaxe                  ItemID = 605
	DiamondAxe                      ItemID = 606
	DiamondHoe                      ItemID = 607
	NetheriteSword                  ItemID = 608
	NetheriteShovel                 ItemID = 609
	NetheritePickaxe                ItemID = 610
	NetheriteAxe                    ItemID = 611
	NetheriteHoe                    ItemID = 612
	Stick                           ItemID = 613
	Bowl                            ItemID = 614
	MushroomStew                    ItemID = 615
	String                          ItemID = 616
	Feather                         ItemID = 617
	Gunpowder                       ItemID = 618
	WheatSeeds                      ItemID = 619
	Wheat                           ItemID = 620
	Bread                           ItemID = 621
	LeatherHelmet                   ItemID = 622
	LeatherChestplate               ItemID = 623
	LeatherLeggings                 ItemID = 624
	LeatherBoots                    ItemID = 625
	ChainmailHelmet                 ItemID = 626
	ChainmailChestplate             ItemID = 627
	ChainmailLeggings               ItemID = 628
	ChainmailBoots                  ItemID = 629
	IronHelmet                      ItemID = 630
	IronChestplate                  ItemID = 631
	IronLeggings                    ItemID = 632
	IronBoots                       ItemID = 633
	DiamondHelmet                   ItemID = 634
	DiamondChestplate               ItemID = 635
	DiamondLeggings                 ItemID = 636
	DiamondBoots                    ItemID = 637
	GoldenHelmet                    ItemID = 638
	GoldenChestplate                ItemID = 639
	GoldenLeggings                  ItemID = 640
	GoldenBoots                     ItemID = 641
	NetheriteHelmet                 ItemID = 642
	NetheriteChestplate             ItemID = 643
	NetheriteLeggings               ItemID = 644
	NetheriteBoots                  ItemID = 645
	Flint                           ItemID = 646
	Porkchop                        ItemID = 647
	CookedPorkchop                  ItemID = 648
	Painting                        ItemID = 649
	GoldenApple                     ItemID = 650
	EnchantedGoldenApple            ItemID = 651
	OakSign                         ItemID = 652
	SpruceSign                      ItemID = 653
	BirchSign                       ItemID = 654
	JungleSign                      ItemID = 655
	AcaciaSign                      ItemID = 656
	DarkOakSign                     ItemID = 657
	CrimsonSign                     ItemID = 658
	WarpedSign                      ItemID = 659
	Bucket                          ItemID = 660
	WaterBucket                     ItemID = 661
	LavaBucket                      ItemID = 662
	Minecart                        ItemID = 663
	Saddle                          ItemID = 664
	Redstone                        ItemID = 665
	Snowball                        ItemID = 666
	OakBoat                         ItemID = 667
	Leather                         ItemID = 668
	MilkBucket                      ItemID = 669
	PufferfishBucket                ItemID = 670
	SalmonBucket                    ItemID = 671
	CodBucket                       ItemID = 672
	TropicalFishBucket              ItemID = 673
	Brick                           ItemID = 674
	ClayBall                        ItemID = 675
	DriedKelpBlock                  ItemID = 676
	Paper                           ItemID = 677
	Book                            ItemID = 678
	SlimeBall                       ItemID = 679
	ChestMinecart                   ItemID = 680
	FurnaceMinecart                 ItemID = 681
	Egg                             ItemID = 682
	Compass                         ItemID = 683
	FishingRod                      ItemID = 684
	Clock                           ItemID = 685
	GlowstoneDust                   ItemID = 686
	Cod                             ItemID = 687
	Salmon                          ItemID = 688
	TropicalFish                    ItemID = 689
	Pufferfish                      ItemID = 690
	CookedCod                       ItemID = 691
	CookedSalmon                    ItemID = 692
	InkSac                          ItemID = 693
	CocoaBeans                      ItemID = 694
	LapisLazuli                     ItemID = 695
	WhiteDye                        ItemID = 696
	OrangeDye                       ItemID = 697
	MagentaDye                      ItemID = 698
	LightBlueDye                    ItemID = 699
	YellowDye                       ItemID = 700
	LimeDye                         ItemID = 701
	PinkDye                         ItemID = 702
	GrayDye                         ItemID = 703
	LightGrayDye                    ItemID = 704
	CyanDye                         ItemID = 705
	PurpleDye                       ItemID = 706
	BlueDye                         ItemID = 707
	BrownDye                        ItemID = 708
	GreenDye                        ItemID = 709
	RedDye                          ItemID = 710
	BlackDye                        ItemID = 711
	BoneMeal                        ItemID = 712
	Bone                            ItemID = 713
	Sugar                           ItemID = 714
	Cake                            ItemID = 715
	WhiteBed                        ItemID = 716
	OrangeBed                       ItemID = 717
	MagentaBed                      ItemID = 718
	LightBlueBed                    ItemID = 719
	YellowBed                       ItemID = 720
	LimeBed                         ItemID = 721
	PinkBed                         ItemID = 722
	GrayBed                         ItemID = 723
	LightGrayBed                    ItemID = 724
	CyanBed                         ItemID = 725
	PurpleBed                       ItemID = 726
	BlueBed                         ItemID = 727
	BrownBed                        ItemID = 728
	GreenBed                        ItemID = 729
	RedBed                          ItemID = 730
	BlackBed                        ItemID = 731
	Cookie                          ItemID = 732
	FilledMap                       ItemID = 733
	Shears                          ItemID = 734
	MelonSlice                      ItemID = 735
	DriedKelp                       ItemID = 736
	PumpkinSeeds                    ItemID = 737
	MelonSeeds                      ItemID = 738
	Beef                            ItemID = 739
	CookedBeef                      ItemID = 740
	Chicken                         ItemID = 741
	CookedChicken                   ItemID = 742
	RottenFlesh                     ItemID = 743
	EnderPearl                      ItemID = 744
	BlazeRod                        ItemID = 745
	GhastTear                       ItemID = 746
	GoldNugget                      ItemID = 747
	NetherWart                      ItemID = 748
	Potion                          ItemID = 749
	GlassBottle                     ItemID = 750
	SpiderEye                       ItemID = 751
	FermentedSpiderEye              ItemID = 752
	BlazePowder                     ItemID = 753
	MagmaCream                      ItemID = 754
	BrewingStand                    ItemID = 755
	Cauldron                        ItemID = 756
	EnderEye                        ItemID = 757
	GlisteringMelonSlice            ItemID = 758
	BatSpawnEgg                     ItemID = 759
	BeeSpawnEgg                     ItemID = 760
	BlazeSpawnEgg                   ItemID = 761
	CatSpawnEgg                     ItemID = 762
	CaveSpiderSpawnEgg              ItemID = 763
	ChickenSpawnEgg                 ItemID = 764
	CodSpawnEgg                     ItemID = 765
	CowSpawnEgg                     ItemID = 766
	CreeperSpawnEgg                 ItemID = 767
	DolphinSpawnEgg                 ItemID = 768
	DonkeySpawnEgg                  ItemID = 769
	DrownedSpawnEgg                 ItemID = 770
	ElderGuardianSpawnEgg           ItemID = 771
	EndermanSpawnEgg                ItemID = 772
	EndermiteSpawnEgg               ItemID = 773
	EvokerSpawnEgg                  ItemID = 774
	FoxSpawnEgg                     ItemID = 775
	GhastSpawnEgg                   ItemID = 776
	GuardianSpawnEgg                ItemID = 777
	HoglinSpawnEgg                  ItemID = 778
	HorseSpawnEgg                   ItemID = 779
	HuskSpawnEgg                    ItemID = 780
	LlamaSpawnEgg                   ItemID = 781
	MagmaCubeSpawnEgg               ItemID = 782
	MooshroomSpawnEgg               ItemID = 783
	MuleSpawnEgg                    ItemID = 784
	OcelotSpawnEgg                  ItemID = 785
	PandaSpawnEgg                   ItemID = 786
	ParrotSpawnEgg                  ItemID = 787
	PhantomSpawnEgg                 ItemID = 788
	PigSpawnEgg                     ItemID = 789
	PiglinSpawnEgg                  ItemID = 790
	PiglinBruteSpawnEgg             ItemID = 791
	PillagerSpawnEgg                ItemID = 792
	PolarBearSpawnEgg               ItemID = 793
	PufferfishSpawnEgg              ItemID = 794
	RabbitSpawnEgg                  ItemID = 795
	RavagerSpawnEgg                 ItemID = 796
	SalmonSpawnEgg                  ItemID = 797
	SheepSpawnEgg                   ItemID = 798
	ShulkerSpawnEgg                 ItemID = 799
	SilverfishSpawnEgg              ItemID = 800
	SkeletonSpawnEgg                ItemID = 801
	SkeletonHorseSpawnEgg           ItemID = 802
	SlimeSpawnEgg                   ItemID = 803
	SpiderSpawnEgg                  ItemID = 804
	SquidSpawnEgg                   ItemID = 805
	StraySpawnEgg                   ItemID = 806
	StriderSpawnEgg                 ItemID = 807
	TraderLlamaSpawnEgg             ItemID = 808
	TropicalFishSpawnEgg            ItemID = 809
	TurtleSpawnEgg                  ItemID = 810
	VexSpawnEgg                     ItemID = 811
	VillagerSpawnEgg                ItemID = 812
	VindicatorSpawnEgg              ItemID = 813
	WanderingTraderSpawnEgg         ItemID = 814
	WitchSpawnEgg                   ItemID = 815
	WitherSkeletonSpawnEgg          ItemID = 816
	WolfSpawnEgg                    ItemID = 817
	ZoglinSpawnEgg                  ItemID = 818
	ZombieSpawnEgg                  ItemID = 819
	ZombieHorseSpawnEgg             ItemID = 820
	ZombieVillagerSpawnEgg          ItemID = 821
	ZombifiedPiglinSpawnEgg         ItemID = 822
	ExperienceBottle                ItemID = 823
	FireCharge                      ItemID = 824
	WritableBook                    ItemID = 825
	WrittenBook                     ItemID = 826
	Emerald                         ItemID = 827
	ItemFrame                       ItemID = 828
	FlowerPot                       ItemID = 829
	Carrot                          ItemID = 830
	Potato                          ItemID = 831
	BakedPotato                     ItemID = 832
	PoisonousPotato                 ItemID = 833
	Map                             ItemID = 834
	GoldenCarrot                    ItemID = 835
	SkeletonSkull                   ItemID = 836
	WitherSkeletonSkull             ItemID = 837
	PlayerHead                      ItemID = 838
	ZombieHead                      ItemID = 839
	CreeperHead                     ItemID = 840
	DragonHead                      ItemID = 841
	CarrotOnAStick                  ItemID = 842
	WarpedFungusOnAStick            ItemID = 843
	NetherStar                      ItemID = 844
	PumpkinPie                      ItemID = 845
	FireworkRocket                  ItemID = 846
	FireworkStar                    ItemID = 847
	EnchantedBook                   ItemID = 848
	NetherBrick                     ItemID = 849
	Quartz                          ItemID = 850
	TntMinecart                     ItemID = 851
	HopperMinecart                  ItemID = 852
	PrismarineShard                 ItemID = 853
	PrismarineCrystals              ItemID = 854
	Rabbit                          ItemID = 855
	CookedRabbit                    ItemID = 856
	RabbitStew                      ItemID = 857
	RabbitFoot                      ItemID = 858
	RabbitHide                      ItemID = 859
	ArmorStand                      ItemID = 860
	IronHorseArmor                  ItemID = 861
	GoldenHorseArmor                ItemID = 862
	DiamondHorseArmor               ItemID = 863
	LeatherHorseArmor               ItemID = 864
	Lead                            ItemID = 865
	NameTag                         ItemID = 866
	CommandBlockMinecart            ItemID = 867
	Mutton                          ItemID = 868
	CookedMutton                    ItemID = 869
	WhiteBanner                     ItemID = 870
	OrangeBanner                    ItemID = 871
	MagentaBanner                   ItemID = 872
	LightBlueBanner                 ItemID = 873
	YellowBanner                    ItemID = 874
	LimeBanner                      ItemID = 875
	PinkBanner                      ItemID = 876
	GrayBanner                      ItemID = 877
	LightGrayBanner                 ItemID = 878
	CyanBanner                      ItemID = 879
	PurpleBanner                    ItemID = 880
	BlueBanner                      ItemID = 881
	BrownBanner                     ItemID = 882
	GreenBanner                     ItemID = 883
	RedBanner                       ItemID = 884
	BlackBanner                     ItemID = 885
	EndCrystal                      ItemID = 886
	ChorusFruit                     ItemID = 887
	PoppedChorusFruit               ItemID = 888
	Beetroot                        ItemID = 889
	BeetrootSeeds                   ItemID = 890
	BeetrootSoup                    ItemID = 891
	DragonBreath                    ItemID = 892
	SplashPotion                    ItemID = 893
	SpectralArrow                   ItemID = 894
	TippedArrow                     ItemID = 895
	LingeringPotion                 ItemID = 896
	Shield                          ItemID = 897
	Elytra                          ItemID = 898
	SpruceBoat                      ItemID = 899
	BirchBoat                       ItemID = 900
	JungleBoat                      ItemID = 901
	AcaciaBoat                      ItemID = 902
	DarkOakBoat                     ItemID = 903
	TotemOfUndying                  ItemID = 904
	ShulkerShell                    ItemID = 905
	IronNugget                      ItemID = 906
	KnowledgeBook                   ItemID = 907
	DebugStick                      ItemID = 908
	MusicDisc13                     ItemID = 909
	MusicDiscCat                    ItemID = 910
	MusicDiscBlocks                 ItemID = 911
	MusicDiscChirp                  ItemID = 912
	MusicDiscFar                    ItemID = 913
	MusicDiscMall                   ItemID = 914
	MusicDiscMellohi                ItemID = 915
	MusicDiscStal                   ItemID = 916
	MusicDiscStrad                  ItemID = 917
	MusicDiscWard                   ItemID = 918
	MusicDisc11                     ItemID = 919
	MusicDiscWait                   ItemID = 920
	MusicDiscPigstep                ItemID = 921
	Trident                         ItemID = 922
	PhantomMembrane                 ItemID = 923
	NautilusShell                   ItemID = 924
	HeartOfTheSea                   ItemID = 925
	Crossbow                        ItemID = 926
	SuspiciousStew                  ItemID = 927
	Loom                            ItemID = 928
	FlowerBannerPattern             ItemID = 929
	CreeperBannerPattern            ItemID = 930
	SkullBannerPattern              ItemID = 931
	MojangBannerPattern             ItemID = 932
	GlobeBannerPattern              ItemID = 933
	PiglinBannerPattern             ItemID = 934
	Composter                       ItemID = 935
	Barrel                          ItemID = 936
	Smoker                          ItemID = 937
	BlastFurnace                    ItemID = 938
	CartographyTable                ItemID = 939
	FletchingTable                  ItemID = 940
	Grindstone                      ItemID = 941
	Lectern                         ItemID = 942
	SmithingTable                   ItemID = 943
	Stonecutter                     ItemID = 944
	Bell                            ItemID = 945
	Lantern                         ItemID = 946
	SoulLantern                     ItemID = 947
	SweetBerries                    ItemID = 948
	Campfire                        ItemID = 949
	SoulCampfire                    ItemID = 950
	Shroomlight                     ItemID = 951
	Honeycomb                       ItemID = 952
	BeeNest                         ItemID = 953
	Beehive                         ItemID = 954
	HoneyBottle                     ItemID = 955
	HoneyBlock                      ItemID = 956
	HoneycombBlock                  ItemID = 957
	Lodestone                       ItemID = 958
	NetheriteBlock                  ItemID = 959
	AncientDebris                   ItemID = 960
	Target                          ItemID = 961
	CryingObsidian                  ItemID = 962
	Blackstone                      ItemID = 963
	BlackstoneSlab                  ItemID = 964
	BlackstoneStairs                ItemID = 965
	GildedBlackstone                ItemID = 966
	PolishedBlackstone              ItemID = 967
	PolishedBlackstoneSlab          ItemID = 968
	PolishedBlackstoneStairs        ItemID = 969
	ChiseledPolishedBlackstone      ItemID = 970
	PolishedBlackstoneBricks        ItemID = 971
	PolishedBlackstoneBrickSlab     ItemID = 972
	PolishedBlackstoneBrickStairs   ItemID = 973
	CrackedPolishedBlackstoneBricks ItemID = 974
	RespawnAnchor                   ItemID = 975
)

var namesMap map[ItemID]string

func init() {
	namesMap = make(map[ItemID]string)
	namesMap[0] = "minecraft:air"
	namesMap[1] = "minecraft:stone"
	namesMap[2] = "minecraft:granite"
	namesMap[3] = "minecraft:polished_granite"
	namesMap[4] = "minecraft:diorite"
	namesMap[5] = "minecraft:polished_diorite"
	namesMap[6] = "minecraft:andesite"
	namesMap[7] = "minecraft:polished_andesite"
	namesMap[8] = "minecraft:grass_block"
	namesMap[9] = "minecraft:dirt"
	namesMap[10] = "minecraft:coarse_dirt"
	namesMap[11] = "minecraft:podzol"
	namesMap[12] = "minecraft:crimson_nylium"
	namesMap[13] = "minecraft:warped_nylium"
	namesMap[14] = "minecraft:cobblestone"
	namesMap[15] = "minecraft:oak_planks"
	namesMap[16] = "minecraft:spruce_planks"
	namesMap[17] = "minecraft:birch_planks"
	namesMap[18] = "minecraft:jungle_planks"
	namesMap[19] = "minecraft:acacia_planks"
	namesMap[20] = "minecraft:dark_oak_planks"
	namesMap[21] = "minecraft:crimson_planks"
	namesMap[22] = "minecraft:warped_planks"
	namesMap[23] = "minecraft:oak_sapling"
	namesMap[24] = "minecraft:spruce_sapling"
	namesMap[25] = "minecraft:birch_sapling"
	namesMap[26] = "minecraft:jungle_sapling"
	namesMap[27] = "minecraft:acacia_sapling"
	namesMap[28] = "minecraft:dark_oak_sapling"
	namesMap[29] = "minecraft:bedrock"
	namesMap[30] = "minecraft:sand"
	namesMap[31] = "minecraft:red_sand"
	namesMap[32] = "minecraft:gravel"
	namesMap[33] = "minecraft:gold_ore"
	namesMap[34] = "minecraft:iron_ore"
	namesMap[35] = "minecraft:coal_ore"
	namesMap[36] = "minecraft:nether_gold_ore"
	namesMap[37] = "minecraft:oak_log"
	namesMap[38] = "minecraft:spruce_log"
	namesMap[39] = "minecraft:birch_log"
	namesMap[40] = "minecraft:jungle_log"
	namesMap[41] = "minecraft:acacia_log"
	namesMap[42] = "minecraft:dark_oak_log"
	namesMap[43] = "minecraft:crimson_stem"
	namesMap[44] = "minecraft:warped_stem"
	namesMap[45] = "minecraft:stripped_oak_log"
	namesMap[46] = "minecraft:stripped_spruce_log"
	namesMap[47] = "minecraft:stripped_birch_log"
	namesMap[48] = "minecraft:stripped_jungle_log"
	namesMap[49] = "minecraft:stripped_acacia_log"
	namesMap[50] = "minecraft:stripped_dark_oak_log"
	namesMap[51] = "minecraft:stripped_crimson_stem"
	namesMap[52] = "minecraft:stripped_warped_stem"
	namesMap[53] = "minecraft:stripped_oak_wood"
	namesMap[54] = "minecraft:stripped_spruce_wood"
	namesMap[55] = "minecraft:stripped_birch_wood"
	namesMap[56] = "minecraft:stripped_jungle_wood"
	namesMap[57] = "minecraft:stripped_acacia_wood"
	namesMap[58] = "minecraft:stripped_dark_oak_wood"
	namesMap[59] = "minecraft:stripped_crimson_hyphae"
	namesMap[60] = "minecraft:stripped_warped_hyphae"
	namesMap[61] = "minecraft:oak_wood"
	namesMap[62] = "minecraft:spruce_wood"
	namesMap[63] = "minecraft:birch_wood"
	namesMap[64] = "minecraft:jungle_wood"
	namesMap[65] = "minecraft:acacia_wood"
	namesMap[66] = "minecraft:dark_oak_wood"
	namesMap[67] = "minecraft:crimson_hyphae"
	namesMap[68] = "minecraft:warped_hyphae"
	namesMap[69] = "minecraft:oak_leaves"
	namesMap[70] = "minecraft:spruce_leaves"
	namesMap[71] = "minecraft:birch_leaves"
	namesMap[72] = "minecraft:jungle_leaves"
	namesMap[73] = "minecraft:acacia_leaves"
	namesMap[74] = "minecraft:dark_oak_leaves"
	namesMap[75] = "minecraft:sponge"
	namesMap[76] = "minecraft:wet_sponge"
	namesMap[77] = "minecraft:glass"
	namesMap[78] = "minecraft:lapis_ore"
	namesMap[79] = "minecraft:lapis_block"
	namesMap[80] = "minecraft:dispenser"
	namesMap[81] = "minecraft:sandstone"
	namesMap[82] = "minecraft:chiseled_sandstone"
	namesMap[83] = "minecraft:cut_sandstone"
	namesMap[84] = "minecraft:note_block"
	namesMap[85] = "minecraft:powered_rail"
	namesMap[86] = "minecraft:detector_rail"
	namesMap[87] = "minecraft:sticky_piston"
	namesMap[88] = "minecraft:cobweb"
	namesMap[89] = "minecraft:grass"
	namesMap[90] = "minecraft:fern"
	namesMap[91] = "minecraft:dead_bush"
	namesMap[92] = "minecraft:seagrass"
	namesMap[93] = "minecraft:sea_pickle"
	namesMap[94] = "minecraft:piston"
	namesMap[95] = "minecraft:white_wool"
	namesMap[96] = "minecraft:orange_wool"
	namesMap[97] = "minecraft:magenta_wool"
	namesMap[98] = "minecraft:light_blue_wool"
	namesMap[99] = "minecraft:yellow_wool"
	namesMap[100] = "minecraft:lime_wool"
	namesMap[101] = "minecraft:pink_wool"
	namesMap[102] = "minecraft:gray_wool"
	namesMap[103] = "minecraft:light_gray_wool"
	namesMap[104] = "minecraft:cyan_wool"
	namesMap[105] = "minecraft:purple_wool"
	namesMap[106] = "minecraft:blue_wool"
	namesMap[107] = "minecraft:brown_wool"
	namesMap[108] = "minecraft:green_wool"
	namesMap[109] = "minecraft:red_wool"
	namesMap[110] = "minecraft:black_wool"
	namesMap[111] = "minecraft:dandelion"
	namesMap[112] = "minecraft:poppy"
	namesMap[113] = "minecraft:blue_orchid"
	namesMap[114] = "minecraft:allium"
	namesMap[115] = "minecraft:azure_bluet"
	namesMap[116] = "minecraft:red_tulip"
	namesMap[117] = "minecraft:orange_tulip"
	namesMap[118] = "minecraft:white_tulip"
	namesMap[119] = "minecraft:pink_tulip"
	namesMap[120] = "minecraft:oxeye_daisy"
	namesMap[121] = "minecraft:cornflower"
	namesMap[122] = "minecraft:lily_of_the_valley"
	namesMap[123] = "minecraft:wither_rose"
	namesMap[124] = "minecraft:brown_mushroom"
	namesMap[125] = "minecraft:red_mushroom"
	namesMap[126] = "minecraft:crimson_fungus"
	namesMap[127] = "minecraft:warped_fungus"
	namesMap[128] = "minecraft:crimson_roots"
	namesMap[129] = "minecraft:warped_roots"
	namesMap[130] = "minecraft:nether_sprouts"
	namesMap[131] = "minecraft:weeping_vines"
	namesMap[132] = "minecraft:twisting_vines"
	namesMap[133] = "minecraft:sugar_cane"
	namesMap[134] = "minecraft:kelp"
	namesMap[135] = "minecraft:bamboo"
	namesMap[136] = "minecraft:gold_block"
	namesMap[137] = "minecraft:iron_block"
	namesMap[138] = "minecraft:oak_slab"
	namesMap[139] = "minecraft:spruce_slab"
	namesMap[140] = "minecraft:birch_slab"
	namesMap[141] = "minecraft:jungle_slab"
	namesMap[142] = "minecraft:acacia_slab"
	namesMap[143] = "minecraft:dark_oak_slab"
	namesMap[144] = "minecraft:crimson_slab"
	namesMap[145] = "minecraft:warped_slab"
	namesMap[146] = "minecraft:stone_slab"
	namesMap[147] = "minecraft:smooth_stone_slab"
	namesMap[148] = "minecraft:sandstone_slab"
	namesMap[149] = "minecraft:cut_sandstone_slab"
	namesMap[150] = "minecraft:petrified_oak_slab"
	namesMap[151] = "minecraft:cobblestone_slab"
	namesMap[152] = "minecraft:brick_slab"
	namesMap[153] = "minecraft:stone_brick_slab"
	namesMap[154] = "minecraft:nether_brick_slab"
	namesMap[155] = "minecraft:quartz_slab"
	namesMap[156] = "minecraft:red_sandstone_slab"
	namesMap[157] = "minecraft:cut_red_sandstone_slab"
	namesMap[158] = "minecraft:purpur_slab"
	namesMap[159] = "minecraft:prismarine_slab"
	namesMap[160] = "minecraft:prismarine_brick_slab"
	namesMap[161] = "minecraft:dark_prismarine_slab"
	namesMap[162] = "minecraft:smooth_quartz"
	namesMap[163] = "minecraft:smooth_red_sandstone"
	namesMap[164] = "minecraft:smooth_sandstone"
	namesMap[165] = "minecraft:smooth_stone"
	namesMap[166] = "minecraft:bricks"
	namesMap[167] = "minecraft:tnt"
	namesMap[168] = "minecraft:bookshelf"
	namesMap[169] = "minecraft:mossy_cobblestone"
	namesMap[170] = "minecraft:obsidian"
	namesMap[171] = "minecraft:torch"
	namesMap[172] = "minecraft:end_rod"
	namesMap[173] = "minecraft:chorus_plant"
	namesMap[174] = "minecraft:chorus_flower"
	namesMap[175] = "minecraft:purpur_block"
	namesMap[176] = "minecraft:purpur_pillar"
	namesMap[177] = "minecraft:purpur_stairs"
	namesMap[178] = "minecraft:spawner"
	namesMap[179] = "minecraft:oak_stairs"
	namesMap[180] = "minecraft:chest"
	namesMap[181] = "minecraft:diamond_ore"
	namesMap[182] = "minecraft:diamond_block"
	namesMap[183] = "minecraft:crafting_table"
	namesMap[184] = "minecraft:farmland"
	namesMap[185] = "minecraft:furnace"
	namesMap[186] = "minecraft:ladder"
	namesMap[187] = "minecraft:rail"
	namesMap[188] = "minecraft:cobblestone_stairs"
	namesMap[189] = "minecraft:lever"
	namesMap[190] = "minecraft:stone_pressure_plate"
	namesMap[191] = "minecraft:oak_pressure_plate"
	namesMap[192] = "minecraft:spruce_pressure_plate"
	namesMap[193] = "minecraft:birch_pressure_plate"
	namesMap[194] = "minecraft:jungle_pressure_plate"
	namesMap[195] = "minecraft:acacia_pressure_plate"
	namesMap[196] = "minecraft:dark_oak_pressure_plate"
	namesMap[197] = "minecraft:crimson_pressure_plate"
	namesMap[198] = "minecraft:warped_pressure_plate"
	namesMap[199] = "minecraft:polished_blackstone_pressure_plate"
	namesMap[200] = "minecraft:redstone_ore"
	namesMap[201] = "minecraft:redstone_torch"
	namesMap[202] = "minecraft:snow"
	namesMap[203] = "minecraft:ice"
	namesMap[204] = "minecraft:snow_block"
	namesMap[205] = "minecraft:cactus"
	namesMap[206] = "minecraft:clay"
	namesMap[207] = "minecraft:jukebox"
	namesMap[208] = "minecraft:oak_fence"
	namesMap[209] = "minecraft:spruce_fence"
	namesMap[210] = "minecraft:birch_fence"
	namesMap[211] = "minecraft:jungle_fence"
	namesMap[212] = "minecraft:acacia_fence"
	namesMap[213] = "minecraft:dark_oak_fence"
	namesMap[214] = "minecraft:crimson_fence"
	namesMap[215] = "minecraft:warped_fence"
	namesMap[216] = "minecraft:pumpkin"
	namesMap[217] = "minecraft:carved_pumpkin"
	namesMap[218] = "minecraft:netherrack"
	namesMap[219] = "minecraft:soul_sand"
	namesMap[220] = "minecraft:soul_soil"
	namesMap[221] = "minecraft:basalt"
	namesMap[222] = "minecraft:polished_basalt"
	namesMap[223] = "minecraft:soul_torch"
	namesMap[224] = "minecraft:glowstone"
	namesMap[225] = "minecraft:jack_o_lantern"
	namesMap[226] = "minecraft:oak_trapdoor"
	namesMap[227] = "minecraft:spruce_trapdoor"
	namesMap[228] = "minecraft:birch_trapdoor"
	namesMap[229] = "minecraft:jungle_trapdoor"
	namesMap[230] = "minecraft:acacia_trapdoor"
	namesMap[231] = "minecraft:dark_oak_trapdoor"
	namesMap[232] = "minecraft:crimson_trapdoor"
	namesMap[233] = "minecraft:warped_trapdoor"
	namesMap[234] = "minecraft:infested_stone"
	namesMap[235] = "minecraft:infested_cobblestone"
	namesMap[236] = "minecraft:infested_stone_bricks"
	namesMap[237] = "minecraft:infested_mossy_stone_bricks"
	namesMap[238] = "minecraft:infested_cracked_stone_bricks"
	namesMap[239] = "minecraft:infested_chiseled_stone_bricks"
	namesMap[240] = "minecraft:stone_bricks"
	namesMap[241] = "minecraft:mossy_stone_bricks"
	namesMap[242] = "minecraft:cracked_stone_bricks"
	namesMap[243] = "minecraft:chiseled_stone_bricks"
	namesMap[244] = "minecraft:brown_mushroom_block"
	namesMap[245] = "minecraft:red_mushroom_block"
	namesMap[246] = "minecraft:mushroom_stem"
	namesMap[247] = "minecraft:iron_bars"
	namesMap[248] = "minecraft:chain"
	namesMap[249] = "minecraft:glass_pane"
	namesMap[250] = "minecraft:melon"
	namesMap[251] = "minecraft:vine"
	namesMap[252] = "minecraft:oak_fence_gate"
	namesMap[253] = "minecraft:spruce_fence_gate"
	namesMap[254] = "minecraft:birch_fence_gate"
	namesMap[255] = "minecraft:jungle_fence_gate"
	namesMap[256] = "minecraft:acacia_fence_gate"
	namesMap[257] = "minecraft:dark_oak_fence_gate"
	namesMap[258] = "minecraft:crimson_fence_gate"
	namesMap[259] = "minecraft:warped_fence_gate"
	namesMap[260] = "minecraft:brick_stairs"
	namesMap[261] = "minecraft:stone_brick_stairs"
	namesMap[262] = "minecraft:mycelium"
	namesMap[263] = "minecraft:lily_pad"
	namesMap[264] = "minecraft:nether_bricks"
	namesMap[265] = "minecraft:cracked_nether_bricks"
	namesMap[266] = "minecraft:chiseled_nether_bricks"
	namesMap[267] = "minecraft:nether_brick_fence"
	namesMap[268] = "minecraft:nether_brick_stairs"
	namesMap[269] = "minecraft:enchanting_table"
	namesMap[270] = "minecraft:end_portal_frame"
	namesMap[271] = "minecraft:end_stone"
	namesMap[272] = "minecraft:end_stone_bricks"
	namesMap[273] = "minecraft:dragon_egg"
	namesMap[274] = "minecraft:redstone_lamp"
	namesMap[275] = "minecraft:sandstone_stairs"
	namesMap[276] = "minecraft:emerald_ore"
	namesMap[277] = "minecraft:ender_chest"
	namesMap[278] = "minecraft:tripwire_hook"
	namesMap[279] = "minecraft:emerald_block"
	namesMap[280] = "minecraft:spruce_stairs"
	namesMap[281] = "minecraft:birch_stairs"
	namesMap[282] = "minecraft:jungle_stairs"
	namesMap[283] = "minecraft:crimson_stairs"
	namesMap[284] = "minecraft:warped_stairs"
	namesMap[285] = "minecraft:command_block"
	namesMap[286] = "minecraft:beacon"
	namesMap[287] = "minecraft:cobblestone_wall"
	namesMap[288] = "minecraft:mossy_cobblestone_wall"
	namesMap[289] = "minecraft:brick_wall"
	namesMap[290] = "minecraft:prismarine_wall"
	namesMap[291] = "minecraft:red_sandstone_wall"
	namesMap[292] = "minecraft:mossy_stone_brick_wall"
	namesMap[293] = "minecraft:granite_wall"
	namesMap[294] = "minecraft:stone_brick_wall"
	namesMap[295] = "minecraft:nether_brick_wall"
	namesMap[296] = "minecraft:andesite_wall"
	namesMap[297] = "minecraft:red_nether_brick_wall"
	namesMap[298] = "minecraft:sandstone_wall"
	namesMap[299] = "minecraft:end_stone_brick_wall"
	namesMap[300] = "minecraft:diorite_wall"
	namesMap[301] = "minecraft:blackstone_wall"
	namesMap[302] = "minecraft:polished_blackstone_wall"
	namesMap[303] = "minecraft:polished_blackstone_brick_wall"
	namesMap[304] = "minecraft:stone_button"
	namesMap[305] = "minecraft:oak_button"
	namesMap[306] = "minecraft:spruce_button"
	namesMap[307] = "minecraft:birch_button"
	namesMap[308] = "minecraft:jungle_button"
	namesMap[309] = "minecraft:acacia_button"
	namesMap[310] = "minecraft:dark_oak_button"
	namesMap[311] = "minecraft:crimson_button"
	namesMap[312] = "minecraft:warped_button"
	namesMap[313] = "minecraft:polished_blackstone_button"
	namesMap[314] = "minecraft:anvil"
	namesMap[315] = "minecraft:chipped_anvil"
	namesMap[316] = "minecraft:damaged_anvil"
	namesMap[317] = "minecraft:trapped_chest"
	namesMap[318] = "minecraft:light_weighted_pressure_plate"
	namesMap[319] = "minecraft:heavy_weighted_pressure_plate"
	namesMap[320] = "minecraft:daylight_detector"
	namesMap[321] = "minecraft:redstone_block"
	namesMap[322] = "minecraft:nether_quartz_ore"
	namesMap[323] = "minecraft:hopper"
	namesMap[324] = "minecraft:chiseled_quartz_block"
	namesMap[325] = "minecraft:quartz_block"
	namesMap[326] = "minecraft:quartz_bricks"
	namesMap[327] = "minecraft:quartz_pillar"
	namesMap[328] = "minecraft:quartz_stairs"
	namesMap[329] = "minecraft:activator_rail"
	namesMap[330] = "minecraft:dropper"
	namesMap[331] = "minecraft:white_terracotta"
	namesMap[332] = "minecraft:orange_terracotta"
	namesMap[333] = "minecraft:magenta_terracotta"
	namesMap[334] = "minecraft:light_blue_terracotta"
	namesMap[335] = "minecraft:yellow_terracotta"
	namesMap[336] = "minecraft:lime_terracotta"
	namesMap[337] = "minecraft:pink_terracotta"
	namesMap[338] = "minecraft:gray_terracotta"
	namesMap[339] = "minecraft:light_gray_terracotta"
	namesMap[340] = "minecraft:cyan_terracotta"
	namesMap[341] = "minecraft:purple_terracotta"
	namesMap[342] = "minecraft:blue_terracotta"
	namesMap[343] = "minecraft:brown_terracotta"
	namesMap[344] = "minecraft:green_terracotta"
	namesMap[345] = "minecraft:red_terracotta"
	namesMap[346] = "minecraft:black_terracotta"
	namesMap[347] = "minecraft:barrier"
	namesMap[348] = "minecraft:iron_trapdoor"
	namesMap[349] = "minecraft:hay_block"
	namesMap[350] = "minecraft:white_carpet"
	namesMap[351] = "minecraft:orange_carpet"
	namesMap[352] = "minecraft:magenta_carpet"
	namesMap[353] = "minecraft:light_blue_carpet"
	namesMap[354] = "minecraft:yellow_carpet"
	namesMap[355] = "minecraft:lime_carpet"
	namesMap[356] = "minecraft:pink_carpet"
	namesMap[357] = "minecraft:gray_carpet"
	namesMap[358] = "minecraft:light_gray_carpet"
	namesMap[359] = "minecraft:cyan_carpet"
	namesMap[360] = "minecraft:purple_carpet"
	namesMap[361] = "minecraft:blue_carpet"
	namesMap[362] = "minecraft:brown_carpet"
	namesMap[363] = "minecraft:green_carpet"
	namesMap[364] = "minecraft:red_carpet"
	namesMap[365] = "minecraft:black_carpet"
	namesMap[366] = "minecraft:terracotta"
	namesMap[367] = "minecraft:coal_block"
	namesMap[368] = "minecraft:packed_ice"
	namesMap[369] = "minecraft:acacia_stairs"
	namesMap[370] = "minecraft:dark_oak_stairs"
	namesMap[371] = "minecraft:slime_block"
	namesMap[372] = "minecraft:grass_path"
	namesMap[373] = "minecraft:sunflower"
	namesMap[374] = "minecraft:lilac"
	namesMap[375] = "minecraft:rose_bush"
	namesMap[376] = "minecraft:peony"
	namesMap[377] = "minecraft:tall_grass"
	namesMap[378] = "minecraft:large_fern"
	namesMap[379] = "minecraft:white_stained_glass"
	namesMap[380] = "minecraft:orange_stained_glass"
	namesMap[381] = "minecraft:magenta_stained_glass"
	namesMap[382] = "minecraft:light_blue_stained_glass"
	namesMap[383] = "minecraft:yellow_stained_glass"
	namesMap[384] = "minecraft:lime_stained_glass"
	namesMap[385] = "minecraft:pink_stained_glass"
	namesMap[386] = "minecraft:gray_stained_glass"
	namesMap[387] = "minecraft:light_gray_stained_glass"
	namesMap[388] = "minecraft:cyan_stained_glass"
	namesMap[389] = "minecraft:purple_stained_glass"
	namesMap[390] = "minecraft:blue_stained_glass"
	namesMap[391] = "minecraft:brown_stained_glass"
	namesMap[392] = "minecraft:green_stained_glass"
	namesMap[393] = "minecraft:red_stained_glass"
	namesMap[394] = "minecraft:black_stained_glass"
	namesMap[395] = "minecraft:white_stained_glass_pane"
	namesMap[396] = "minecraft:orange_stained_glass_pane"
	namesMap[397] = "minecraft:magenta_stained_glass_pane"
	namesMap[398] = "minecraft:light_blue_stained_glass_pane"
	namesMap[399] = "minecraft:yellow_stained_glass_pane"
	namesMap[400] = "minecraft:lime_stained_glass_pane"
	namesMap[401] = "minecraft:pink_stained_glass_pane"
	namesMap[402] = "minecraft:gray_stained_glass_pane"
	namesMap[403] = "minecraft:light_gray_stained_glass_pane"
	namesMap[404] = "minecraft:cyan_stained_glass_pane"
	namesMap[405] = "minecraft:purple_stained_glass_pane"
	namesMap[406] = "minecraft:blue_stained_glass_pane"
	namesMap[407] = "minecraft:brown_stained_glass_pane"
	namesMap[408] = "minecraft:green_stained_glass_pane"
	namesMap[409] = "minecraft:red_stained_glass_pane"
	namesMap[410] = "minecraft:black_stained_glass_pane"
	namesMap[411] = "minecraft:prismarine"
	namesMap[412] = "minecraft:prismarine_bricks"
	namesMap[413] = "minecraft:dark_prismarine"
	namesMap[414] = "minecraft:prismarine_stairs"
	namesMap[415] = "minecraft:prismarine_brick_stairs"
	namesMap[416] = "minecraft:dark_prismarine_stairs"
	namesMap[417] = "minecraft:sea_lantern"
	namesMap[418] = "minecraft:red_sandstone"
	namesMap[419] = "minecraft:chiseled_red_sandstone"
	namesMap[420] = "minecraft:cut_red_sandstone"
	namesMap[421] = "minecraft:red_sandstone_stairs"
	namesMap[422] = "minecraft:repeating_command_block"
	namesMap[423] = "minecraft:chain_command_block"
	namesMap[424] = "minecraft:magma_block"
	namesMap[425] = "minecraft:nether_wart_block"
	namesMap[426] = "minecraft:warped_wart_block"
	namesMap[427] = "minecraft:red_nether_bricks"
	namesMap[428] = "minecraft:bone_block"
	namesMap[429] = "minecraft:structure_void"
	namesMap[430] = "minecraft:observer"
	namesMap[431] = "minecraft:shulker_box"
	namesMap[432] = "minecraft:white_shulker_box"
	namesMap[433] = "minecraft:orange_shulker_box"
	namesMap[434] = "minecraft:magenta_shulker_box"
	namesMap[435] = "minecraft:light_blue_shulker_box"
	namesMap[436] = "minecraft:yellow_shulker_box"
	namesMap[437] = "minecraft:lime_shulker_box"
	namesMap[438] = "minecraft:pink_shulker_box"
	namesMap[439] = "minecraft:gray_shulker_box"
	namesMap[440] = "minecraft:light_gray_shulker_box"
	namesMap[441] = "minecraft:cyan_shulker_box"
	namesMap[442] = "minecraft:purple_shulker_box"
	namesMap[443] = "minecraft:blue_shulker_box"
	namesMap[444] = "minecraft:brown_shulker_box"
	namesMap[445] = "minecraft:green_shulker_box"
	namesMap[446] = "minecraft:red_shulker_box"
	namesMap[447] = "minecraft:black_shulker_box"
	namesMap[448] = "minecraft:white_glazed_terracotta"
	namesMap[449] = "minecraft:orange_glazed_terracotta"
	namesMap[450] = "minecraft:magenta_glazed_terracotta"
	namesMap[451] = "minecraft:light_blue_glazed_terracotta"
	namesMap[452] = "minecraft:yellow_glazed_terracotta"
	namesMap[453] = "minecraft:lime_glazed_terracotta"
	namesMap[454] = "minecraft:pink_glazed_terracotta"
	namesMap[455] = "minecraft:gray_glazed_terracotta"
	namesMap[456] = "minecraft:light_gray_glazed_terracotta"
	namesMap[457] = "minecraft:cyan_glazed_terracotta"
	namesMap[458] = "minecraft:purple_glazed_terracotta"
	namesMap[459] = "minecraft:blue_glazed_terracotta"
	namesMap[460] = "minecraft:brown_glazed_terracotta"
	namesMap[461] = "minecraft:green_glazed_terracotta"
	namesMap[462] = "minecraft:red_glazed_terracotta"
	namesMap[463] = "minecraft:black_glazed_terracotta"
	namesMap[464] = "minecraft:white_concrete"
	namesMap[465] = "minecraft:orange_concrete"
	namesMap[466] = "minecraft:magenta_concrete"
	namesMap[467] = "minecraft:light_blue_concrete"
	namesMap[468] = "minecraft:yellow_concrete"
	namesMap[469] = "minecraft:lime_concrete"
	namesMap[470] = "minecraft:pink_concrete"
	namesMap[471] = "minecraft:gray_concrete"
	namesMap[472] = "minecraft:light_gray_concrete"
	namesMap[473] = "minecraft:cyan_concrete"
	namesMap[474] = "minecraft:purple_concrete"
	namesMap[475] = "minecraft:blue_concrete"
	namesMap[476] = "minecraft:brown_concrete"
	namesMap[477] = "minecraft:green_concrete"
	namesMap[478] = "minecraft:red_concrete"
	namesMap[479] = "minecraft:black_concrete"
	namesMap[480] = "minecraft:white_concrete_powder"
	namesMap[481] = "minecraft:orange_concrete_powder"
	namesMap[482] = "minecraft:magenta_concrete_powder"
	namesMap[483] = "minecraft:light_blue_concrete_powder"
	namesMap[484] = "minecraft:yellow_concrete_powder"
	namesMap[485] = "minecraft:lime_concrete_powder"
	namesMap[486] = "minecraft:pink_concrete_powder"
	namesMap[487] = "minecraft:gray_concrete_powder"
	namesMap[488] = "minecraft:light_gray_concrete_powder"
	namesMap[489] = "minecraft:cyan_concrete_powder"
	namesMap[490] = "minecraft:purple_concrete_powder"
	namesMap[491] = "minecraft:blue_concrete_powder"
	namesMap[492] = "minecraft:brown_concrete_powder"
	namesMap[493] = "minecraft:green_concrete_powder"
	namesMap[494] = "minecraft:red_concrete_powder"
	namesMap[495] = "minecraft:black_concrete_powder"
	namesMap[496] = "minecraft:turtle_egg"
	namesMap[497] = "minecraft:dead_tube_coral_block"
	namesMap[498] = "minecraft:dead_brain_coral_block"
	namesMap[499] = "minecraft:dead_bubble_coral_block"
	namesMap[500] = "minecraft:dead_fire_coral_block"
	namesMap[501] = "minecraft:dead_horn_coral_block"
	namesMap[502] = "minecraft:tube_coral_block"
	namesMap[503] = "minecraft:brain_coral_block"
	namesMap[504] = "minecraft:bubble_coral_block"
	namesMap[505] = "minecraft:fire_coral_block"
	namesMap[506] = "minecraft:horn_coral_block"
	namesMap[507] = "minecraft:tube_coral"
	namesMap[508] = "minecraft:brain_coral"
	namesMap[509] = "minecraft:bubble_coral"
	namesMap[510] = "minecraft:fire_coral"
	namesMap[511] = "minecraft:horn_coral"
	namesMap[512] = "minecraft:dead_brain_coral"
	namesMap[513] = "minecraft:dead_bubble_coral"
	namesMap[514] = "minecraft:dead_fire_coral"
	namesMap[515] = "minecraft:dead_horn_coral"
	namesMap[516] = "minecraft:dead_tube_coral"
	namesMap[517] = "minecraft:tube_coral_fan"
	namesMap[518] = "minecraft:brain_coral_fan"
	namesMap[519] = "minecraft:bubble_coral_fan"
	namesMap[520] = "minecraft:fire_coral_fan"
	namesMap[521] = "minecraft:horn_coral_fan"
	namesMap[522] = "minecraft:dead_tube_coral_fan"
	namesMap[523] = "minecraft:dead_brain_coral_fan"
	namesMap[524] = "minecraft:dead_bubble_coral_fan"
	namesMap[525] = "minecraft:dead_fire_coral_fan"
	namesMap[526] = "minecraft:dead_horn_coral_fan"
	namesMap[527] = "minecraft:blue_ice"
	namesMap[528] = "minecraft:conduit"
	namesMap[529] = "minecraft:polished_granite_stairs"
	namesMap[530] = "minecraft:smooth_red_sandstone_stairs"
	namesMap[531] = "minecraft:mossy_stone_brick_stairs"
	namesMap[532] = "minecraft:polished_diorite_stairs"
	namesMap[533] = "minecraft:mossy_cobblestone_stairs"
	namesMap[534] = "minecraft:end_stone_brick_stairs"
	namesMap[535] = "minecraft:stone_stairs"
	namesMap[536] = "minecraft:smooth_sandstone_stairs"
	namesMap[537] = "minecraft:smooth_quartz_stairs"
	namesMap[538] = "minecraft:granite_stairs"
	namesMap[539] = "minecraft:andesite_stairs"
	namesMap[540] = "minecraft:red_nether_brick_stairs"
	namesMap[541] = "minecraft:polished_andesite_stairs"
	namesMap[542] = "minecraft:diorite_stairs"
	namesMap[543] = "minecraft:polished_granite_slab"
	namesMap[544] = "minecraft:smooth_red_sandstone_slab"
	namesMap[545] = "minecraft:mossy_stone_brick_slab"
	namesMap[546] = "minecraft:polished_diorite_slab"
	namesMap[547] = "minecraft:mossy_cobblestone_slab"
	namesMap[548] = "minecraft:end_stone_brick_slab"
	namesMap[549] = "minecraft:smooth_sandstone_slab"
	namesMap[550] = "minecraft:smooth_quartz_slab"
	namesMap[551] = "minecraft:granite_slab"
	namesMap[552] = "minecraft:andesite_slab"
	namesMap[553] = "minecraft:red_nether_brick_slab"
	namesMap[554] = "minecraft:polished_andesite_slab"
	namesMap[555] = "minecraft:diorite_slab"
	namesMap[556] = "minecraft:scaffolding"
	namesMap[557] = "minecraft:iron_door"
	namesMap[558] = "minecraft:oak_door"
	namesMap[559] = "minecraft:spruce_door"
	namesMap[560] = "minecraft:birch_door"
	namesMap[561] = "minecraft:jungle_door"
	namesMap[562] = "minecraft:acacia_door"
	namesMap[563] = "minecraft:dark_oak_door"
	namesMap[564] = "minecraft:crimson_door"
	namesMap[565] = "minecraft:warped_door"
	namesMap[566] = "minecraft:repeater"
	namesMap[567] = "minecraft:comparator"
	namesMap[568] = "minecraft:structure_block"
	namesMap[569] = "minecraft:jigsaw"
	namesMap[570] = "minecraft:turtle_helmet"
	namesMap[571] = "minecraft:scute"
	namesMap[572] = "minecraft:flint_and_steel"
	namesMap[573] = "minecraft:apple"
	namesMap[574] = "minecraft:bow"
	namesMap[575] = "minecraft:arrow"
	namesMap[576] = "minecraft:coal"
	namesMap[577] = "minecraft:charcoal"
	namesMap[578] = "minecraft:diamond"
	namesMap[579] = "minecraft:iron_ingot"
	namesMap[580] = "minecraft:gold_ingot"
	namesMap[581] = "minecraft:netherite_ingot"
	namesMap[582] = "minecraft:netherite_scrap"
	namesMap[583] = "minecraft:wooden_sword"
	namesMap[584] = "minecraft:wooden_shovel"
	namesMap[585] = "minecraft:wooden_pickaxe"
	namesMap[586] = "minecraft:wooden_axe"
	namesMap[587] = "minecraft:wooden_hoe"
	namesMap[588] = "minecraft:stone_sword"
	namesMap[589] = "minecraft:stone_shovel"
	namesMap[590] = "minecraft:stone_pickaxe"
	namesMap[591] = "minecraft:stone_axe"
	namesMap[592] = "minecraft:stone_hoe"
	namesMap[593] = "minecraft:golden_sword"
	namesMap[594] = "minecraft:golden_shovel"
	namesMap[595] = "minecraft:golden_pickaxe"
	namesMap[596] = "minecraft:golden_axe"
	namesMap[597] = "minecraft:golden_hoe"
	namesMap[598] = "minecraft:iron_sword"
	namesMap[599] = "minecraft:iron_shovel"
	namesMap[600] = "minecraft:iron_pickaxe"
	namesMap[601] = "minecraft:iron_axe"
	namesMap[602] = "minecraft:iron_hoe"
	namesMap[603] = "minecraft:diamond_sword"
	namesMap[604] = "minecraft:diamond_shovel"
	namesMap[605] = "minecraft:diamond_pickaxe"
	namesMap[606] = "minecraft:diamond_axe"
	namesMap[607] = "minecraft:diamond_hoe"
	namesMap[608] = "minecraft:netherite_sword"
	namesMap[609] = "minecraft:netherite_shovel"
	namesMap[610] = "minecraft:netherite_pickaxe"
	namesMap[611] = "minecraft:netherite_axe"
	namesMap[612] = "minecraft:netherite_hoe"
	namesMap[613] = "minecraft:stick"
	namesMap[614] = "minecraft:bowl"
	namesMap[615] = "minecraft:mushroom_stew"
	namesMap[616] = "minecraft:string"
	namesMap[617] = "minecraft:feather"
	namesMap[618] = "minecraft:gunpowder"
	namesMap[619] = "minecraft:wheat_seeds"
	namesMap[620] = "minecraft:wheat"
	namesMap[621] = "minecraft:bread"
	namesMap[622] = "minecraft:leather_helmet"
	namesMap[623] = "minecraft:leather_chestplate"
	namesMap[624] = "minecraft:leather_leggings"
	namesMap[625] = "minecraft:leather_boots"
	namesMap[626] = "minecraft:chainmail_helmet"
	namesMap[627] = "minecraft:chainmail_chestplate"
	namesMap[628] = "minecraft:chainmail_leggings"
	namesMap[629] = "minecraft:chainmail_boots"
	namesMap[630] = "minecraft:iron_helmet"
	namesMap[631] = "minecraft:iron_chestplate"
	namesMap[632] = "minecraft:iron_leggings"
	namesMap[633] = "minecraft:iron_boots"
	namesMap[634] = "minecraft:diamond_helmet"
	namesMap[635] = "minecraft:diamond_chestplate"
	namesMap[636] = "minecraft:diamond_leggings"
	namesMap[637] = "minecraft:diamond_boots"
	namesMap[638] = "minecraft:golden_helmet"
	namesMap[639] = "minecraft:golden_chestplate"
	namesMap[640] = "minecraft:golden_leggings"
	namesMap[641] = "minecraft:golden_boots"
	namesMap[642] = "minecraft:netherite_helmet"
	namesMap[643] = "minecraft:netherite_chestplate"
	namesMap[644] = "minecraft:netherite_leggings"
	namesMap[645] = "minecraft:netherite_boots"
	namesMap[646] = "minecraft:flint"
	namesMap[647] = "minecraft:porkchop"
	namesMap[648] = "minecraft:cooked_porkchop"
	namesMap[649] = "minecraft:painting"
	namesMap[650] = "minecraft:golden_apple"
	namesMap[651] = "minecraft:enchanted_golden_apple"
	namesMap[652] = "minecraft:oak_sign"
	namesMap[653] = "minecraft:spruce_sign"
	namesMap[654] = "minecraft:birch_sign"
	namesMap[655] = "minecraft:jungle_sign"
	namesMap[656] = "minecraft:acacia_sign"
	namesMap[657] = "minecraft:dark_oak_sign"
	namesMap[658] = "minecraft:crimson_sign"
	namesMap[659] = "minecraft:warped_sign"
	namesMap[660] = "minecraft:bucket"
	namesMap[661] = "minecraft:water_bucket"
	namesMap[662] = "minecraft:lava_bucket"
	namesMap[663] = "minecraft:minecart"
	namesMap[664] = "minecraft:saddle"
	namesMap[665] = "minecraft:redstone"
	namesMap[666] = "minecraft:snowball"
	namesMap[667] = "minecraft:oak_boat"
	namesMap[668] = "minecraft:leather"
	namesMap[669] = "minecraft:milk_bucket"
	namesMap[670] = "minecraft:pufferfish_bucket"
	namesMap[671] = "minecraft:salmon_bucket"
	namesMap[672] = "minecraft:cod_bucket"
	namesMap[673] = "minecraft:tropical_fish_bucket"
	namesMap[674] = "minecraft:brick"
	namesMap[675] = "minecraft:clay_ball"
	namesMap[676] = "minecraft:dried_kelp_block"
	namesMap[677] = "minecraft:paper"
	namesMap[678] = "minecraft:book"
	namesMap[679] = "minecraft:slime_ball"
	namesMap[680] = "minecraft:chest_minecart"
	namesMap[681] = "minecraft:furnace_minecart"
	namesMap[682] = "minecraft:egg"
	namesMap[683] = "minecraft:compass"
	namesMap[684] = "minecraft:fishing_rod"
	namesMap[685] = "minecraft:clock"
	namesMap[686] = "minecraft:glowstone_dust"
	namesMap[687] = "minecraft:cod"
	namesMap[688] = "minecraft:salmon"
	namesMap[689] = "minecraft:tropical_fish"
	namesMap[690] = "minecraft:pufferfish"
	namesMap[691] = "minecraft:cooked_cod"
	namesMap[692] = "minecraft:cooked_salmon"
	namesMap[693] = "minecraft:ink_sac"
	namesMap[694] = "minecraft:cocoa_beans"
	namesMap[695] = "minecraft:lapis_lazuli"
	namesMap[696] = "minecraft:white_dye"
	namesMap[697] = "minecraft:orange_dye"
	namesMap[698] = "minecraft:magenta_dye"
	namesMap[699] = "minecraft:light_blue_dye"
	namesMap[700] = "minecraft:yellow_dye"
	namesMap[701] = "minecraft:lime_dye"
	namesMap[702] = "minecraft:pink_dye"
	namesMap[703] = "minecraft:gray_dye"
	namesMap[704] = "minecraft:light_gray_dye"
	namesMap[705] = "minecraft:cyan_dye"
	namesMap[706] = "minecraft:purple_dye"
	namesMap[707] = "minecraft:blue_dye"
	namesMap[708] = "minecraft:brown_dye"
	namesMap[709] = "minecraft:green_dye"
	namesMap[710] = "minecraft:red_dye"
	namesMap[711] = "minecraft:black_dye"
	namesMap[712] = "minecraft:bone_meal"
	namesMap[713] = "minecraft:bone"
	namesMap[714] = "minecraft:sugar"
	namesMap[715] = "minecraft:cake"
	namesMap[716] = "minecraft:white_bed"
	namesMap[717] = "minecraft:orange_bed"
	namesMap[718] = "minecraft:magenta_bed"
	namesMap[719] = "minecraft:light_blue_bed"
	namesMap[720] = "minecraft:yellow_bed"
	namesMap[721] = "minecraft:lime_bed"
	namesMap[722] = "minecraft:pink_bed"
	namesMap[723] = "minecraft:gray_bed"
	namesMap[724] = "minecraft:light_gray_bed"
	namesMap[725] = "minecraft:cyan_bed"
	namesMap[726] = "minecraft:purple_bed"
	namesMap[727] = "minecraft:blue_bed"
	namesMap[728] = "minecraft:brown_bed"
	namesMap[729] = "minecraft:green_bed"
	namesMap[730] = "minecraft:red_bed"
	namesMap[731] = "minecraft:black_bed"
	namesMap[732] = "minecraft:cookie"
	namesMap[733] = "minecraft:filled_map"
	namesMap[734] = "minecraft:shears"
	namesMap[735] = "minecraft:melon_slice"
	namesMap[736] = "minecraft:dried_kelp"
	namesMap[737] = "minecraft:pumpkin_seeds"
	namesMap[738] = "minecraft:melon_seeds"
	namesMap[739] = "minecraft:beef"
	namesMap[740] = "minecraft:cooked_beef"
	namesMap[741] = "minecraft:chicken"
	namesMap[742] = "minecraft:cooked_chicken"
	namesMap[743] = "minecraft:rotten_flesh"
	namesMap[744] = "minecraft:ender_pearl"
	namesMap[745] = "minecraft:blaze_rod"
	namesMap[746] = "minecraft:ghast_tear"
	namesMap[747] = "minecraft:gold_nugget"
	namesMap[748] = "minecraft:nether_wart"
	namesMap[749] = "minecraft:potion"
	namesMap[750] = "minecraft:glass_bottle"
	namesMap[751] = "minecraft:spider_eye"
	namesMap[752] = "minecraft:fermented_spider_eye"
	namesMap[753] = "minecraft:blaze_powder"
	namesMap[754] = "minecraft:magma_cream"
	namesMap[755] = "minecraft:brewing_stand"
	namesMap[756] = "minecraft:cauldron"
	namesMap[757] = "minecraft:ender_eye"
	namesMap[758] = "minecraft:glistering_melon_slice"
	namesMap[759] = "minecraft:bat_spawn_egg"
	namesMap[760] = "minecraft:bee_spawn_egg"
	namesMap[761] = "minecraft:blaze_spawn_egg"
	namesMap[762] = "minecraft:cat_spawn_egg"
	namesMap[763] = "minecraft:cave_spider_spawn_egg"
	namesMap[764] = "minecraft:chicken_spawn_egg"
	namesMap[765] = "minecraft:cod_spawn_egg"
	namesMap[766] = "minecraft:cow_spawn_egg"
	namesMap[767] = "minecraft:creeper_spawn_egg"
	namesMap[768] = "minecraft:dolphin_spawn_egg"
	namesMap[769] = "minecraft:donkey_spawn_egg"
	namesMap[770] = "minecraft:drowned_spawn_egg"
	namesMap[771] = "minecraft:elder_guardian_spawn_egg"
	namesMap[772] = "minecraft:enderman_spawn_egg"
	namesMap[773] = "minecraft:endermite_spawn_egg"
	namesMap[774] = "minecraft:evoker_spawn_egg"
	namesMap[775] = "minecraft:fox_spawn_egg"
	namesMap[776] = "minecraft:ghast_spawn_egg"
	namesMap[777] = "minecraft:guardian_spawn_egg"
	namesMap[778] = "minecraft:hoglin_spawn_egg"
	namesMap[779] = "minecraft:horse_spawn_egg"
	namesMap[780] = "minecraft:husk_spawn_egg"
	namesMap[781] = "minecraft:llama_spawn_egg"
	namesMap[782] = "minecraft:magma_cube_spawn_egg"
	namesMap[783] = "minecraft:mooshroom_spawn_egg"
	namesMap[784] = "minecraft:mule_spawn_egg"
	namesMap[785] = "minecraft:ocelot_spawn_egg"
	namesMap[786] = "minecraft:panda_spawn_egg"
	namesMap[787] = "minecraft:parrot_spawn_egg"
	namesMap[788] = "minecraft:phantom_spawn_egg"
	namesMap[789] = "minecraft:pig_spawn_egg"
	namesMap[790] = "minecraft:piglin_spawn_egg"
	namesMap[791] = "minecraft:piglin_brute_spawn_egg"
	namesMap[792] = "minecraft:pillager_spawn_egg"
	namesMap[793] = "minecraft:polar_bear_spawn_egg"
	namesMap[794] = "minecraft:pufferfish_spawn_egg"
	namesMap[795] = "minecraft:rabbit_spawn_egg"
	namesMap[796] = "minecraft:ravager_spawn_egg"
	namesMap[797] = "minecraft:salmon_spawn_egg"
	namesMap[798] = "minecraft:sheep_spawn_egg"
	namesMap[799] = "minecraft:shulker_spawn_egg"
	namesMap[800] = "minecraft:silverfish_spawn_egg"
	namesMap[801] = "minecraft:skeleton_spawn_egg"
	namesMap[802] = "minecraft:skeleton_horse_spawn_egg"
	namesMap[803] = "minecraft:slime_spawn_egg"
	namesMap[804] = "minecraft:spider_spawn_egg"
	namesMap[805] = "minecraft:squid_spawn_egg"
	namesMap[806] = "minecraft:stray_spawn_egg"
	namesMap[807] = "minecraft:strider_spawn_egg"
	namesMap[808] = "minecraft:trader_llama_spawn_egg"
	namesMap[809] = "minecraft:tropical_fish_spawn_egg"
	namesMap[810] = "minecraft:turtle_spawn_egg"
	namesMap[811] = "minecraft:vex_spawn_egg"
	namesMap[812] = "minecraft:villager_spawn_egg"
	namesMap[813] = "minecraft:vindicator_spawn_egg"
	namesMap[814] = "minecraft:wandering_trader_spawn_egg"
	namesMap[815] = "minecraft:witch_spawn_egg"
	namesMap[816] = "minecraft:wither_skeleton_spawn_egg"
	namesMap[817] = "minecraft:wolf_spawn_egg"
	namesMap[818] = "minecraft:zoglin_spawn_egg"
	namesMap[819] = "minecraft:zombie_spawn_egg"
	namesMap[820] = "minecraft:zombie_horse_spawn_egg"
	namesMap[821] = "minecraft:zombie_villager_spawn_egg"
	namesMap[822] = "minecraft:zombified_piglin_spawn_egg"
	namesMap[823] = "minecraft:experience_bottle"
	namesMap[824] = "minecraft:fire_charge"
	namesMap[825] = "minecraft:writable_book"
	namesMap[826] = "minecraft:written_book"
	namesMap[827] = "minecraft:emerald"
	namesMap[828] = "minecraft:item_frame"
	namesMap[829] = "minecraft:flower_pot"
	namesMap[830] = "minecraft:carrot"
	namesMap[831] = "minecraft:potato"
	namesMap[832] = "minecraft:baked_potato"
	namesMap[833] = "minecraft:poisonous_potato"
	namesMap[834] = "minecraft:map"
	namesMap[835] = "minecraft:golden_carrot"
	namesMap[836] = "minecraft:skeleton_skull"
	namesMap[837] = "minecraft:wither_skeleton_skull"
	namesMap[838] = "minecraft:player_head"
	namesMap[839] = "minecraft:zombie_head"
	namesMap[840] = "minecraft:creeper_head"
	namesMap[841] = "minecraft:dragon_head"
	namesMap[842] = "minecraft:carrot_on_a_stick"
	namesMap[843] = "minecraft:warped_fungus_on_a_stick"
	namesMap[844] = "minecraft:nether_star"
	namesMap[845] = "minecraft:pumpkin_pie"
	namesMap[846] = "minecraft:firework_rocket"
	namesMap[847] = "minecraft:firework_star"
	namesMap[848] = "minecraft:enchanted_book"
	namesMap[849] = "minecraft:nether_brick"
	namesMap[850] = "minecraft:quartz"
	namesMap[851] = "minecraft:tnt_minecart"
	namesMap[852] = "minecraft:hopper_minecart"
	namesMap[853] = "minecraft:prismarine_shard"
	namesMap[854] = "minecraft:prismarine_crystals"
	namesMap[855] = "minecraft:rabbit"
	namesMap[856] = "minecraft:cooked_rabbit"
	namesMap[857] = "minecraft:rabbit_stew"
	namesMap[858] = "minecraft:rabbit_foot"
	namesMap[859] = "minecraft:rabbit_hide"
	namesMap[860] = "minecraft:armor_stand"
	namesMap[861] = "minecraft:iron_horse_armor"
	namesMap[862] = "minecraft:golden_horse_armor"
	namesMap[863] = "minecraft:diamond_horse_armor"
	namesMap[864] = "minecraft:leather_horse_armor"
	namesMap[865] = "minecraft:lead"
	namesMap[866] = "minecraft:name_tag"
	namesMap[867] = "minecraft:command_block_minecart"
	namesMap[868] = "minecraft:mutton"
	namesMap[869] = "minecraft:cooked_mutton"
	namesMap[870] = "minecraft:white_banner"
	namesMap[871] = "minecraft:orange_banner"
	namesMap[872] = "minecraft:magenta_banner"
	namesMap[873] = "minecraft:light_blue_banner"
	namesMap[874] = "minecraft:yellow_banner"
	namesMap[875] = "minecraft:lime_banner"
	namesMap[876] = "minecraft:pink_banner"
	namesMap[877] = "minecraft:gray_banner"
	namesMap[878] = "minecraft:light_gray_banner"
	namesMap[879] = "minecraft:cyan_banner"
	namesMap[880] = "minecraft:purple_banner"
	namesMap[881] = "minecraft:blue_banner"
	namesMap[882] = "minecraft:brown_banner"
	namesMap[883] = "minecraft:green_banner"
	namesMap[884] = "minecraft:red_banner"
	namesMap[885] = "minecraft:black_banner"
	namesMap[886] = "minecraft:end_crystal"
	namesMap[887] = "minecraft:chorus_fruit"
	namesMap[888] = "minecraft:popped_chorus_fruit"
	namesMap[889] = "minecraft:beetroot"
	namesMap[890] = "minecraft:beetroot_seeds"
	namesMap[891] = "minecraft:beetroot_soup"
	namesMap[892] = "minecraft:dragon_breath"
	namesMap[893] = "minecraft:splash_potion"
	namesMap[894] = "minecraft:spectral_arrow"
	namesMap[895] = "minecraft:tipped_arrow"
	namesMap[896] = "minecraft:lingering_potion"
	namesMap[897] = "minecraft:shield"
	namesMap[898] = "minecraft:elytra"
	namesMap[899] = "minecraft:spruce_boat"
	namesMap[900] = "minecraft:birch_boat"
	namesMap[901] = "minecraft:jungle_boat"
	namesMap[902] = "minecraft:acacia_boat"
	namesMap[903] = "minecraft:dark_oak_boat"
	namesMap[904] = "minecraft:totem_of_undying"
	namesMap[905] = "minecraft:shulker_shell"
	namesMap[906] = "minecraft:iron_nugget"
	namesMap[907] = "minecraft:knowledge_book"
	namesMap[908] = "minecraft:debug_stick"
	namesMap[909] = "minecraft:music_disc_13"
	namesMap[910] = "minecraft:music_disc_cat"
	namesMap[911] = "minecraft:music_disc_blocks"
	namesMap[912] = "minecraft:music_disc_chirp"
	namesMap[913] = "minecraft:music_disc_far"
	namesMap[914] = "minecraft:music_disc_mall"
	namesMap[915] = "minecraft:music_disc_mellohi"
	namesMap[916] = "minecraft:music_disc_stal"
	namesMap[917] = "minecraft:music_disc_strad"
	namesMap[918] = "minecraft:music_disc_ward"
	namesMap[919] = "minecraft:music_disc_11"
	namesMap[920] = "minecraft:music_disc_wait"
	namesMap[921] = "minecraft:music_disc_pigstep"
	namesMap[922] = "minecraft:trident"
	namesMap[923] = "minecraft:phantom_membrane"
	namesMap[924] = "minecraft:nautilus_shell"
	namesMap[925] = "minecraft:heart_of_the_sea"
	namesMap[926] = "minecraft:crossbow"
	namesMap[927] = "minecraft:suspicious_stew"
	namesMap[928] = "minecraft:loom"
	namesMap[929] = "minecraft:flower_banner_pattern"
	namesMap[930] = "minecraft:creeper_banner_pattern"
	namesMap[931] = "minecraft:skull_banner_pattern"
	namesMap[932] = "minecraft:mojang_banner_pattern"
	namesMap[933] = "minecraft:globe_banner_pattern"
	namesMap[934] = "minecraft:piglin_banner_pattern"
	namesMap[935] = "minecraft:composter"
	namesMap[936] = "minecraft:barrel"
	namesMap[937] = "minecraft:smoker"
	namesMap[938] = "minecraft:blast_furnace"
	namesMap[939] = "minecraft:cartography_table"
	namesMap[940] = "minecraft:fletching_table"
	namesMap[941] = "minecraft:grindstone"
	namesMap[942] = "minecraft:lectern"
	namesMap[943] = "minecraft:smithing_table"
	namesMap[944] = "minecraft:stonecutter"
	namesMap[945] = "minecraft:bell"
	namesMap[946] = "minecraft:lantern"
	namesMap[947] = "minecraft:soul_lantern"
	namesMap[948] = "minecraft:sweet_berries"
	namesMap[949] = "minecraft:campfire"
	namesMap[950] = "minecraft:soul_campfire"
	namesMap[951] = "minecraft:shroomlight"
	namesMap[952] = "minecraft:honeycomb"
	namesMap[953] = "minecraft:bee_nest"
	namesMap[954] = "minecraft:beehive"
	namesMap[955] = "minecraft:honey_bottle"
	namesMap[956] = "minecraft:honey_block"
	namesMap[957] = "minecraft:honeycomb_block"
	namesMap[958] = "minecraft:lodestone"
	namesMap[959] = "minecraft:netherite_block"
	namesMap[960] = "minecraft:ancient_debris"
	namesMap[961] = "minecraft:target"
	namesMap[962] = "minecraft:crying_obsidian"
	namesMap[963] = "minecraft:blackstone"
	namesMap[964] = "minecraft:blackstone_slab"
	namesMap[965] = "minecraft:blackstone_stairs"
	namesMap[966] = "minecraft:gilded_blackstone"
	namesMap[967] = "minecraft:polished_blackstone"
	namesMap[968] = "minecraft:polished_blackstone_slab"
	namesMap[969] = "minecraft:polished_blackstone_stairs"
	namesMap[970] = "minecraft:chiseled_polished_blackstone"
	namesMap[971] = "minecraft:polished_blackstone_bricks"
	namesMap[972] = "minecraft:polished_blackstone_brick_slab"
	namesMap[973] = "minecraft:polished_blackstone_brick_stairs"
	namesMap[974] = "minecraft:cracked_polished_blackstone_bricks"
	namesMap[975] = "minecraft:respawn_anchor"

}
